#0: Complex_bw merge to TTNN
tenstorrent/tt-metal pull request #10003
Opened 2024-07-08 03:33 UTC by Aswinmcw

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-07-08 12:53 UTC, eyonland requested changes
Given that we have a completely different type of Tensor, can we not simply overload the same name for the function?

2024-07-08 14:38 UTC, TT-BrianLiu approved these changes

2024-07-08 14:38 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/eltwise/complex_binary_backward/device/complex_binary_backward_op.cpp
> +
Remove

2024-07-17 05:19 UTC, eyonland approved these changes

2024-07-17 14:42 UTC, ayerofieiev-tt approved these changes

2024-07-18 07:53 UTC, merged