#8764: Additional set of changes for WH readiness, including new installation steps
tenstorrent/tt-metal pull request #10420
Opened 2024-07-17 22:44 UTC by tt-rkim

### Ticket

#8764 

### Problem description

More complete installation steps for WH single card, and probably T3000.

### What's changed

Update docs.

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-07-25 16:31 UTC, ayerofieiev-tt commented on CONTRIBUTING.md
> +For T3000 (QuietBox, LoudBox etc.): `tt-smi -r 0,1,2,3`
any chance tt-smi team can add support for `-r all`?

2024-07-25 16:32 UTC, ayerofieiev-tt approved these changes

2024-08-01 23:02 UTC, dvartaniansTT requested changes
I confirm build from whl from main with the latest firmware works now. `[fw_pack-80.10.0.0.fwbundle](https://github.com/tenstorrent/tt-firmware/blob/main/fw_pack-80.10.0.0.fwbundle)`

However, v50 tag will fail with the FW and main will fail with the previous firmware. We tested this on a N150 machine. 

Also please note my comment on the review regarding adding instructions for CMAKE install which is necessary to build from src.

2024-08-21 14:29 UTC, tt-rkim commented on INSTALLING.md
> +export PYTHONPATH=$(pwd)
Please check now

2024-08-21 14:30 UTC, tt-rkim commented
@dvartaniansTT We will focus on cutting a release soon.
@uaydonat @skhorasganiTT any chance we can get a release candidate to line up? Recall we should be treating demo models drifting / failing from main as P0s.

2024-08-21 15:02 UTC, skhorasganiTT commented
@tt-rkim If you need one now, it looks like the last set of demo runs (single-card and t3k) on main (d8957c8) passed. Could a release be generated from that? Alternatively, we can have one for our next round of model updates on Monday. 
Also unrelated observation, it looks like the package and release workflow schedule is now slightly out of sync with single-card/t3k demos. Should it be aligned?

2024-08-21 15:06 UTC, tt-rkim commented
@skhorasganiTT No need to be aligned, unless you want to make sure every pipeline you look at for those is at the same time. It grabs the commit at which the tag is being generated - which makes sense. You have to test at the tag

2024-08-21 15:07 UTC, tt-rkim commented
I have started a release generation. Unfortunately I haven't gotten the package and release changes approved yet to start a run of the demos on the same pipeline, but once the tag is made, I will kick off the demo pipelines on that tag. I can show you in person what that looks like @skhorasganiTT

2024-08-21 15:21 UTC, dvartaniansTT approved these changes
LGTM. thanks @tt-rkim

2024-08-21 15:46 UTC, merged