#9750: Move Repeat_interleave to TTNN
tenstorrent/tt-metal pull request #10517
Opened 2024-07-22 12:54 UTC by mouliraj-mcw

Ticket : #9750

### Work Done

- Moved Repeat_Interleave to TTNN.
- Replaced it s usage in CPP and Python files
- Removed tt_lib bindings

2024-07-22 15:33 UTC, umadevimcw commented on models/experimental/stable_diffusion/tt/upsample_nearest2d.py
> +        input = ttnn.repeat_interleave(input, self.scale_factor, dim=3)
Check if ttl can be removed and use ttnn?

2024-07-24 14:24 UTC, boris-drazic approved these changes

2024-07-24 15:46 UTC, ayerofieiev-tt commented on models/experimental/mistral/tt/mistral_attention.py
> +        values = ttnn.repeat_interleave(values, repeats, dim, output_mem_config=self.args.out_mem_config)
kw args in ttnn are
output_mem_config --> memory_config
output_dtype -> dtype

Please update

2024-07-24 15:46 UTC, ayerofieiev-tt commented on tests/tt_eager/python_api_testing/sweep_tests/tt_lib_ops.py
> +    t1 = ttnn.repeat_interleave(t0, repeat, dim, memory_config=output_mem_config)
👍

2024-07-24 15:48 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/data_movement.hpp
> +inline Tensor repeat_interleave(const Tensor& input_a, uint32_t repeat, int32_t dim, const std::optional<MemoryConfig>& output_mem_config) {
no no. please place in https://github.com/tenstorrent/tt-metal/tree/main/ttnn/cpp/ttnn/operations/data_movement as a separate folder `repeat_interleave` and follow the proper op structure as described in the ticket / docs

2024-07-24 15:48 UTC, ayerofieiev-tt requested changes
need to follow the structure

2024-07-25 05:33 UTC, closed without merging