#10385: Migrate Unary forward ops to TTNN
tenstorrent/tt-metal pull request #10512
Opened 2024-07-22 10:28 UTC by mouliraj-mcw

Issue : https://github.com/tenstorrent/tt-metal/issues/10385

Work Done:

Migrated 2 Unary ops to TTNN.
List of Ops:

- [ ] Row
- [ ] Normalize_global

2024-07-22 15:31 UTC, umadevimcw requested changes

2024-07-22 15:31 UTC, umadevimcw commented on tests/tt_eager/python_api_testing/sweep_tests/tt_lib_ops.py
> +# normalize_global = make_unary_op(ttl.tensor.normalize_global)
Remove the commented code

2024-07-22 17:11 UTC, VirdhatchaniKN commented on tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_normalize_global.py
>          [
Please implement golden function for this op

2024-07-23 15:53 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
> +Tensor _normalize_global(const Tensor& y,  const std::optional<MemoryConfig>& output_mem_config) {
https://github.com/tenstorrent/tt-metal/blob/953d2c504d9f1d4f5917888f422e10f13f5377c1/tests/tt_eager/python_api_testing/sweep_tests/pytorch_ops.py#L83

https://github.com/tenstorrent/tt-metal/blob/953d2c504d9f1d4f5917888f422e10f13f5377c1/tests/tt_eager/python_api_testing/sweep_tests/pytorch_ops.py#L1447

attach golden function for both ops in unary.py

2024-07-23 15:54 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
> +Tensor _normalize_global(const Tensor& y,  const std::optional<MemoryConfig>& output_mem_config) {
use above links for golden fn  reference

2024-07-24 05:28 UTC, umadevimcw approved these changes

2024-07-25 05:55 UTC, eyonland approved these changes

2024-07-26 16:03 UTC, merged