#10567: Remove std::function for bw ops
tenstorrent/tt-metal pull request #10698
Opened 2024-07-24 19:02 UTC by VirdhatchaniKN

Issue : #10567

2024-07-25 01:37 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/device/binary_backward_op.hpp
> +    static std::vector<Tensor> handle( const Tensor& grad, const Tensor& input, const Tensor& other, const std::optional<MemoryConfig>& output_mem_config ) {
Please fix this.

2024-07-25 01:37 UTC, eyonland requested changes
https://github.com/tenstorrent/tt-metal/pull/10710

2024-07-25 14:37 UTC, TT-BrianLiu approved these changes

2024-07-25 17:11 UTC, VirdhatchaniKN commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/device/binary_backward_op.hpp
> +    static std::vector<Tensor> handle( const Tensor& grad, const Tensor& input, const Tensor& other, const std::optional<MemoryConfig>& output_mem_config ) {
Issue fixed in PR #10725

2024-07-25 23:39 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/device/binary_backward_op.cpp
>      std::vector<Tensor> grad_tensor;
At some point we need to change output_mem_config to just memory_config

2024-07-25 23:40 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/complex_unary/complex_unary.hpp
>      static ComplexTensor operator()(const ComplexTensor &input_tensor_arg, const MemoryConfig &memory_config) {
Please remove Type2

2024-07-25 23:41 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/device/unary_backward_op.cpp
>      switch (OpType) {
Please remove get_function_type1

2024-07-25 23:43 UTC, eyonland approved these changes
Please remove get_function_type1 either on this PR or another.

2024-07-26 17:54 UTC, VirdhatchaniKN commented
https://github.com/tenstorrent/tt-metal/actions/runs/10114444391 - passed

2024-07-26 17:56 UTC, merged