#0: Cleanup binary backward
tenstorrent/tt-metal pull request #10725
Opened 2024-07-25 08:01 UTC by Aswinmcw

Cleanup OpHandlers in backward ops

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-07-25 17:00 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/binary_backward.hpp
> +    }
I am a bit unfamiliar with this. Why is this needed?

2024-07-25 17:02 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/binary_backward_pybind.hpp
> +    );
Why is this needed? The only difference I see is with queue_id, but it is a kw_only arg with a default value

2024-07-25 17:05 UTC, ayerofieiev-tt reviewed
PR title should include ticket number

2024-07-25 18:37 UTC, ayerofieiev-tt approved these changes

2024-07-25 18:45 UTC, ayerofieiev-tt requested changes
Please remove `create_async_output_tensors`

2024-07-25 23:52 UTC, eyonland approved these changes

2024-07-26 04:33 UTC, ayerofieiev-tt approved these changes

2024-07-26 04:48 UTC, ayerofieiev-tt approved these changes

2024-07-26 13:37 UTC, merged