#10121: migrate indexed fill op into ttnn
tenstorrent/tt-metal pull request #11151
Opened 2024-08-07 13:02 UTC by bharane-ab

### Ticket
Link to Github Issue #10121 

### Problem description
Migrate indexed_fill op into TTNN

### What's changed

Migrated indexed_fill op to ttnn/operations/data_movement

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-08-07 18:04 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill_pybind.cpp
> +namespace py = pybind11;
Please follow the ccl/all_gather example:
* Remove heavy includes, use pybind_fwd instead
* Move implementation to cpp

2024-08-07 18:04 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill_pybind.cpp
> +}
you can remove this :D

2024-08-07 18:05 UTC, ayerofieiev-tt commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill_pybind.cpp
> +namespace py = pybind11;
You can remove this and just use pybind11 as it is used in a single place

2024-08-08 04:45 UTC, eyonland requested changes, later dismissed
Please have this reviewed by an MCW colleague prior to posting the PR.

2024-08-09 04:25 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/deprecated/tt_lib/csrc/tt_lib_bindings_tensor_dm_ops.cpp
> +        // //MOE ops
remove

2024-08-09 04:47 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill_pybind.cpp
> +                pybind11::arg("queue_id") = 0});
py::arg("dim") = 0 is missing. please compare with the  tt_lib binding

2024-08-09 04:48 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill.hpp
> +        const std::optional<ttnn::MemoryConfig>& memory_config = std::nullopt);
dim parameter is missing

2024-08-09 04:52 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/data_movement/indexed_fill/indexed_fill.cpp
> +    std::int64_t dim=0;
this should be a part of input params with an assert.

2024-08-09 10:56 UTC, KalaivaniMCW approved these changes
Review comments have been addressed. Approved.

2024-08-09 15:23 UTC, ayerofieiev-tt approved these changes
nice and clean. thank you!

2024-08-10 16:22 UTC, tarafdarTT approved these changes

2024-08-12 05:01 UTC, merged