Tarafdar tt/split op
tenstorrent/tt-metal pull request #1129
Opened 2023-06-13 18:19 UTC by ntarafdar

This implements a split on the last dimension. 

I have tested the 4 variations seen in stable diffusion `(1x2x1024x2560, 1x2x256x5120, 1x2x64x10240, 1x2x16x10240)`.

To view the tests, refer to the pytests in file: `tests/python_api_testing/models/stable_diffusion/test_split_last_dim_tiled.py`

The kernels are currently  running on a single-core. This will be parallelized in a future PR (by parallelizing the host's invocation of these kernels). The host code is `libs/tt_dnn/op_library/split/split_last_dim_qk_tiled.cpp`

If the dimensions are not tilized, this will run auto pad and then run the split operation. 

The kernels are the following:
```
tt_metal/kernels/dataflow/reader_tm_tile_layout_split_qk.cpp
tt_metal/kernels/dataflow/writer_tm_tile_layout_split_qk.cpp
```

Also wanted to thank @tt-aho , @kkwong10 and @TT-BrianLiu for your help.

2023-06-16 19:59 UTC, ashayestehmanesh submitted a review, later dismissed

2023-06-16 20:05 UTC, tt-rkim requested changes

2023-06-16 20:17 UTC, arakhmati requested changes

2023-06-19 12:44 UTC, tt-rkim submitted a review, later dismissed

2023-06-19 13:36 UTC, tt-aho requested changes

2023-06-19 14:24 UTC, boris-drazic submitted a review, later dismissed

2023-06-19 20:58 UTC, arakhmati requested changes

2023-06-19 21:59 UTC, tt-aho submitted a review, later dismissed
LGTM. Please squash some of your commits together before merging.

2023-06-20 13:09 UTC, tt-rkim submitted a review, later dismissed
LGTM but please squash your commits.

a bunch of "address comments" is not something we'd like in the main branch history.

2023-06-20 14:21 UTC, boris-drazic submitted a review, later dismissed

2023-06-20 15:53 UTC, tt-rkim approved these changes

2023-06-20 16:03 UTC, arakhmati approved these changes

2023-06-21 14:50 UTC, merged