#8150: Fix unary docs
tenstorrent/tt-metal pull request #11339
Opened 2024-08-13 05:48 UTC by Aswinmcw

Tracking Issue : #8150 

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-08-13 14:24 UTC, VirdhatchaniKN commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +        Supported dtypes and layouts:
Can you add a sweep test for `celu` ?

2024-08-13 14:26 UTC, VirdhatchaniKN requested changes

2024-08-13 14:26 UTC, VirdhatchaniKN commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +
Can you add a sweep test for `celu` ?

2024-08-14 11:20 UTC, VirdhatchaniKN approved these changes
Approved

2024-08-14 14:57 UTC, eyonland approved these changes

2024-08-16 10:15 UTC, merged