Compiling TTNN with GCC-12
tenstorrent/tt-metal pull request #11482
Opened 2024-08-14 20:02 UTC by cfjchu

### Ticket
[Link to Github Issue
](https://github.com/tenstorrent/tt-metal/issues/11278)

### Problem description
Our GCC-12 build is broken and our intention is to support GCC-12. 

### What's changed
1. We were using C++23 extension features like `static operator()` but this is not supported in GCC-12 I've removed instances of this.
2. Unfortunately our `MAX_CACHED_PROGRAM_SIZE` needs to be upsized because GCC seems to create larger program binaries.
3. Compiler flags for GCC build to ignore errors/warnings for template-friend declarations
4. `DISABLE_NAMESPACE_ASSERT` build flag added to side-step problems with static asserts on operations are in correct namespace

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-08-14 20:51 UTC, arakhmati approved these changes

2024-08-14 23:54 UTC, TT-billteng requested changes
you should revert the changes in `build_metal.sh`, no one is developing on 22.04 yet

2024-08-15 00:29 UTC, TT-billteng approved these changes

2024-08-15 02:51 UTC, marty1885 commented
Thanks @TT-billteng! I can confirm TTNN now builds with GCC on my machine.

2024-08-15 03:46 UTC, TT-billteng commented
> Thanks @TT-billteng! I can confirm TTNN now builds with GCC on my machine.

You can thank @cfjchu for doing most of the work :D

2024-08-15 03:50 UTC, merged

2024-08-15 04:29 UTC, marty1885 commented
Oopsd tagged the wrong guy :) Thanks @cfjchu !