#11247: Remove in-place flag in binary operations
tenstorrent/tt-metal pull request #11604
Opened 2024-08-19 14:15 UTC by mouliraj-mcw

Ticket : #11247 

### Work Done:

- Removed the in-place flags in binary operations

### Checklist
- [ ] All Post commit CI 
- [ ] Fast Dispatch
- [ ] slow Dispatch

2024-08-20 11:03 UTC, KalaivaniMCW commented on tests/ttnn/unit_tests/operations/test_add.py
> +    output_tensor = ttnn.prim.binary(input_tensor_a, input_tensor_b, ttnn.BinaryOpType.ADD)
need to find a way to use output_tensor arg and perform inlace instead, since we are passing BinaryOpType directly

2024-08-20 12:55 UTC, KalaivaniMCW approved these changes
Approved.

2024-08-20 14:05 UTC, VirdhatchaniKN approved these changes

2024-08-20 14:12 UTC, bharane-ab approved these changes

2024-08-20 15:44 UTC, tt-aho approved these changes

2024-08-21 13:39 UTC, eyonland approved these changes

2024-08-21 13:40 UTC, eyonland requested changes
Please add unit tests.

2024-08-21 13:43 UTC, eyonland approved these changes

2024-08-23 12:11 UTC, mouliraj-mcw commented
Status: Will add Test unit test and then merge.

2024-08-25 01:12 UTC, dmakoviichuk-tt commented
What is the current status of inplace now for binary op?

2024-08-25 02:32 UTC, dmakoviichuk-tt commented
What I see:
new function ttnn.add_ and new tests for it.
What PR says: "remove inpalce flag in binaru operations"
@mouliraj-mcw  please always add in the description all new registered functions.
Also there should be added any changes to the api. 
Unfortunately right now it is impossible to track changes.

2024-08-26 04:51 UTC, mouliraj-mcw commented
> What I see: new function ttnn.add_ and new tests for it. What PR says: "remove inpalce flag in binaru operations" @mouliraj-mcw please always add in the description all new registered functions. Also there should be added any changes to the api. Unfortunately right now it is impossible to track changes.

Hi @dmakoviichuk-tt .

- The ttnn.add_ and other in-place operations were already available. I updated the structure by removing the in-place flag, and since it's an in-place version, I added the required unit tests.
- Let me Update the Description Clearly. Thankyou.

2024-08-28 09:44 UTC, merged