#1205: primary comparison binops - eltwise comparison, cosh, sinh
tenstorrent/tt-metal pull request #1208
Opened 2023-06-16 18:20 UTC by muthutt

- [eltwise-binop compare] comparison binops - <, >, >=, <=, ==, != needed
- we don't want these as composite ops
- relational ops are next step of LTZ, GTZ, EZ, NEZ, LEZ, GEZ ops implemented in #938 and #978
- fix fmt

Part of Torch PRIM IR:
- prims.eq
- prims.ge
- prims.gt
- prims.le
- prims.lt
- prims.ne
- cosh (composite)
- sinh (composite)

2023-06-16 18:44 UTC, arakhmati requested changes

2023-06-16 19:21 UTC, arakhmati requested changes

2023-06-16 19:22 UTC, arakhmati requested changes

2023-06-16 22:35 UTC, tt-aho requested changes

2023-06-20 16:00 UTC, arakhmati requested changes

2023-06-27 16:49 UTC, tt-aho requested changes
You seem to have merged/reverted a number of changes on main including things like transpose, files that were deleted, etc. Please clean up this branch to only have your changes.

I'd also recommend making your concat op/tests to a separate PR from this one

2023-06-27 22:39 UTC, tt-aho requested changes

2023-07-12 15:26 UTC, arakhmati approved these changes

2023-07-12 16:49 UTC, tt-aho approved these changes
Please fix the description in the table for the new comparison ops. They all say add instead of what the op is.

Otherwise lgtm once pipelines pass

2023-07-12 16:58 UTC, mywoodstock approved these changes

2023-07-12 17:00 UTC, tt-nshanker approved these changes

2023-07-12 17:05 UTC, TT-BrianLiu approved these changes

2023-07-12 17:24 UTC, merged