#12146: Add optional output tensor to silu
tenstorrent/tt-metal pull request #12209
Opened 2024-09-04 11:42 UTC by Aswinmcw

Tracking Issue : #12146 

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-09-05 06:37 UTC, VirdhatchaniKN requested changes

2024-09-05 06:37 UTC, VirdhatchaniKN commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/device/unary_backward_op.cpp
> +std::vector<std::optional<ttnn::Tensor>> _silu_bw(uint8_t cq_id, const Tensor& grad, const Tensor& input, const std::optional<MemoryConfig>& output_mem_config, std::optional<Tensor> input_grad) {
To maintain consistency, can we follow the `queue_id` instead of `cq_id `?

2024-09-05 14:03 UTC, VirdhatchaniKN approved these changes
LGTM

2024-09-05 20:45 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/device/unary_backward_op.cpp
> +    }
since this code is being duplicated for most ops, can we have a single common function that does this ?

2024-09-05 20:47 UTC, KalaivaniMCW commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.hpp
> +        return OpHandler<unary_backward_op_type>::handle(queue_id, grad_tensor_arg, input_tensor_arg, parameter, output_memory_config, input_grad);
is it possible to remove OpHandler usage for the ops in this PR and use ::invoke instead ?

2024-09-10 06:12 UTC, eyonland approved these changes

2024-09-10 12:22 UTC, merged