#10226: Added or refactored BH SFPU functions
tenstorrent/tt-metal pull request #12379
Opened 2024-09-09 07:31 UTC by ncvetkovicTT

### Ticket
#10226 

### Problem description
Some functions are not added/enabled for BH.

### What's changed
Within the scope of this PR, the following changes are introduced:

1. SFPU mask - added _int version
2. SFPU reshuffle rows - added missing files 
       * A follow-up coming soon for test infra fix
3. SFPU reciprocal - modified to use submodule LLKs
4. SFPU sqrt - modified to use submodule LLKs
5. SFPU trunc OP - enabled for BH

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-09-09 14:22 UTC, rtawfik01 commented
Since Blackhole only has SD/FD C++ tests on pipelines, can you also run this `pytest -svv tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py` and make sure it still passes since it has not been added to CI yet?

2024-09-09 14:22 UTC, rtawfik01 commented
Also how has the `reshuffle_rows` been tested?

2024-09-09 14:55 UTC, ncvetkovicTT commented
> Since Blackhole only has SD/FD C++ tests on pipelines, can you also run this `pytest -svv tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py` and make sure it still passes since it has not been added to CI yet?

Tested, pass ✅

2024-09-09 14:56 UTC, ncvetkovicTT commented
> Also how has the `reshuffle_rows` been tested?

No, the work will be continued as a part of [#11816](https://github.com/tenstorrent/tt-metal/tree/ncvetkovic/11816-reshuffle_rows_support)

2024-09-09 15:23 UTC, rtawfik01 approved these changes

2024-09-10 13:06 UTC, tt-aho approved these changes

2024-09-10 17:43 UTC, abhullar-tt approved these changes
I believe this should unblock some of the ops that are failing in #12349

2024-09-10 17:46 UTC, eyonland requested changes
I'd like to request that some port of the sweep tests mentioned by @rtawfik01  be added to tests/ttnn/unit_tests

2024-09-10 17:54 UTC, abhullar-tt commented
> I'd like to request that some sample of the uses cases of the sweep tests mentioned by @rtawfik01 be added to tests/ttnn/unit_tests

We are working to enable the fast-dispatch-post-commit workflow on BH CI which should cover these cases, there is a PR up where we are disabling the current failing tests on BH (see https://github.com/tenstorrent/tt-metal/tree/mchiou/11919-enable-ttnntteager-on-bh-ci)

2024-09-10 20:56 UTC, eyonland approved these changes
Based on conversation with @abhullar-tt it sounds like we have a parallel effort and we will get unit tests turned on eventually.

2024-09-11 07:18 UTC, merged