All gather expose params
tenstorrent/tt-metal pull request #12389
Opened 2024-09-09 12:21 UTC by caixunshiren

### Ticket
#11855 

### Problem description
Expose num workers and num buffers attributes at op level

2024-09-11 02:33 UTC, SeanNijjar requested changes

2024-09-11 20:41 UTC, SeanNijjar requested changes

2024-09-11 20:41 UTC, SeanNijjar commented on tests/ttnn/unit_tests/operations/test_all_gather_llama_perf_sweep.py
> +def run_all_gather_sharded(
Is it possible to just reuse the existing run all gather sharded functions from `test_all_gather` and add the trace mode to that instead?

2024-09-11 20:41 UTC, SeanNijjar commented on ttnn/cpp/ttnn/operations/ccl/line_all_gather/line_all_gather.hpp
> +        const std::optional<size_t> num_buffers_per_channel = 2);
std::nullopt

2024-09-11 20:41 UTC, SeanNijjar commented on ttnn/cpp/ttnn/operations/ccl/line_all_gather/line_all_gather.hpp
> +        const std::optional<size_t> num_buffers_per_channel = 2);
std::nullopt

2024-09-11 20:41 UTC, SeanNijjar commented on tests/ttnn/unit_tests/operations/test_all_gather_llama_perf_sweep.py
> +def is_unsupported_case(input_shape, dim, mem_config, num_devices, num_links, input_dtype, layout):
This should be reused from test_all_gather too

2024-09-12 20:20 UTC, SeanNijjar approved these changes
Looks good!

2024-09-13 01:39 UTC, caixunshiren commented
t3k frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10841532333
all post commit: https://github.com/tenstorrent/tt-metal/actions/runs/10841539264
t3k nightly: https://github.com/tenstorrent/tt-metal/actions/runs/10841543402

2024-09-16 15:07 UTC, TT-BrianLiu approved these changes

2024-09-16 15:24 UTC, merged