#12375: Add qid and optional tensor output to ttnn.gelu_bw
tenstorrent/tt-metal pull request #12509
Opened 2024-09-11 11:18 UTC by mcw-anasuya

### Ticket
Link to Github Issue: #12375 

### Problem description
Add queue_id and optional output tensors to ttnn.gelu_bw

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-09-11 11:22 UTC, Aswinmcw requested changes

2024-09-11 11:22 UTC, Aswinmcw commented on tests/ttnn/unit_tests/operations/backward/test_backward_gelu.py
> +    _, input_grad = data_gen_with_range(input_shapes, -1, 1, device)
use L1 mem config

2024-09-11 11:22 UTC, Aswinmcw commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/device/binary_backward_op.cpp
> +    // grad_tensor = ttnn::gelu_bw(grad, input, approximate = approximate, output_mem_config);
comment can be removed?

2024-09-11 11:22 UTC, Aswinmcw commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/device/binary_backward_op.cpp
> +    }
it looks like unary op, why added in binary?

2024-09-11 16:57 UTC, Aswinmcw approved these changes
LGTM

2024-09-12 05:28 UTC, eyonland approved these changes

2024-09-12 09:12 UTC, merged