Relu, gelu and logical_or_ new infrastructure sweeps
tenstorrent/tt-metal pull request #12672
Opened 2024-09-13 20:55 UTC by npetrovic-tenstorrent

Add new Python sweeps for ops:
- relu
- gelu
- logical_or_

2024-09-17 16:09 UTC, jdesousa-TT requested changes

2024-09-17 16:09 UTC, jdesousa-TT commented on .github/workflows/ttnn-run-sweeps.yaml
> +          - eltwise.cos
eltwise.sin is missing from this list

2024-09-17 16:14 UTC, jdesousa-TT commented
Running the new sweeps here:
logical_or https://github.com/tenstorrent/tt-metal/actions/runs/10906953084
relu https://github.com/tenstorrent/tt-metal/actions/runs/10906956537
gelu https://github.com/tenstorrent/tt-metal/actions/runs/10906958671
cos https://github.com/tenstorrent/tt-metal/actions/runs/10906960913

2024-09-18 09:05 UTC, npetrovic-tenstorrent commented on .github/workflows/ttnn-run-sweeps.yaml
> +          - eltwise.cos
Thanks! I will correct this!

2024-09-18 09:14 UTC, npetrovic-tenstorrent commented on .github/workflows/ttnn-run-sweeps.yaml
> +          - eltwise.cos
Corrected in the latest commit

2024-09-18 19:15 UTC, jdesousa-TT approved these changes

2024-09-19 09:17 UTC, merged