#11512: move sqrt and square to new sweep infrastructure
tenstorrent/tt-metal pull request #13041
Opened 2024-09-24 08:55 UTC by dveizovicTT

### Ticket
https://github.com/tenstorrent/tt-metal/issues/11512

### Problem description
Missing sweeps in new sweeps infrastructure for eltwise ops:
1. square
2. sqrt

### What's changed
Added .py sweeps to new sweeps infrastructure for the above mentioned eltwise ops. 
Added functions for tensor type casting and numbers generation without a given range in sweep_framework/utils.py.
Imported these functions in all eltwise sweeps.
Modified .github/workflows/ttnn-run-sweeps.yaml file to include above mentioned eltwise ops.

### Checklist
- [x] ttnn sweeps CI passes 
- [x] Post commit CI passes
- [x] Blackhole Post commit (if applicable)
- [x] Model regression CI testing passes (if applicable)
- [x] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

2024-09-26 15:29 UTC, rtawfik01 commented
@dveizovicTT Please rebase to get the correct submodule pointer

2024-10-01 10:03 UTC, dveizovicTT commented
> @dveizovicTT Please rebase to get the correct submodule pointer

Rebased.

2024-10-01 15:53 UTC, jdesousa-TT approved these changes

2024-10-10 14:56 UTC, rtawfik01 requested changes
Hi @dveizovicTT , you have to take away your changes that were done to the submodules in your earlier commits, because right now your PR will delete 3 submodules that are necessary. In your case the easiest thing that can be done is squash all of your commits, do a git soft reset, remove the submodules changes from staged, then re-commit your changes.

2024-10-16 12:13 UTC, closed without merging