#8151: update sweep test and doc for reglu
tenstorrent/tt-metal pull request #13101
Opened 2024-09-25 12:21 UTC by bharane-ab

### Ticket
Link to Github Issue #8151 

### Problem description
Update doc with supported dtype and layout

### What's changed
Document have been updated with supported data type and supported layout and sweeps test have been updated accordingly.

### Checklist
- [ ] Post commit CI passes

2024-10-01 04:48 UTC, VirdhatchaniKN approved these changes
Minor comment

2024-10-01 04:48 UTC, VirdhatchaniKN commented on tests/ttnn/sweep_tests/sweeps/sweeps/reglu.py
> +        return True, "This combination is not supported"
Can you please change this statement?

2024-10-01 04:55 UTC, VirdhatchaniKN requested changes
Please remove older sweeps and migrate to new infra

2024-10-05 04:32 UTC, VirdhatchaniKN approved these changes
LGTM

2024-10-05 06:30 UTC, Aswinmcw approved these changes
LGTM

2024-10-16 15:34 UTC, jdesousa-TT approved these changes
Please run sweeps pipeline on this branch for reglu before merging.

2024-10-17 06:18 UTC, eyonland approved these changes

2024-10-18 09:32 UTC, merged