#13142: Add documentation for device ops, memory config
tenstorrent/tt-metal pull request #13166
Opened 2024-09-26 16:18 UTC by mcw-anasuya

### Ticket
Link to Github Issue: #13142

### What's changed
- Updated description according to PyTorch Reference
- Added examples to ops
- Fixed additional bugs

### List of Ops
- [ ] ttnn.open_device
- [ ] ttnn.close_device
- [ ] ttnn.manage_device
- [ ] ttnn.synchronize_device
- [ ] ttnn.SetDefaultDevice
- [ ] ttnn.GetDefaultDevice
- [ ] ttnn.format_input_tensor
- [ ] ttnn.format_output_tensor
- [ ] ttnn.pad_to_tile_shape
- [ ] ttnn.create_sharded_memory_config

### Checklist
- [ ] Post commit CI passes

2024-09-26 16:34 UTC, bharane-ab approved these changes

2024-09-26 17:22 UTC, mouliraj-mcw approved these changes

2024-09-27 09:26 UTC, umadevimcw requested changes

2024-09-27 09:35 UTC, mcw-anasuya commented on ttnn/ttnn/device.py
> +        with manage_device(device_id=0) as device:
Hi @umadevimcw 
I removed it to check what the output in the webpage would look like out of curiosity. But, I was unable to connect to the website yesterday through any port I tried. I've added them to back to all examples.

2024-09-27 14:05 UTC, umadevimcw approved these changes

2024-09-28 14:26 UTC, VirdhatchaniKN approved these changes

2024-09-28 15:16 UTC, ayerofieiev-tt approved these changes

2024-10-01 20:37 UTC, merged