#7826: Add doc for abs
tenstorrent/tt-metal pull request #13171
Opened 2024-09-26 17:10 UTC by ruthreshx

### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/7826)

### Problem description
Add doc for abs

### Checklist
- [ ] Post commit CI passes

2024-09-26 17:11 UTC, VirdhatchaniKN approved these changes
LGTM

2024-09-27 11:52 UTC, umadevimcw approved these changes

2024-09-27 13:20 UTC, VirdhatchaniKN approved these changes

2024-09-30 15:43 UTC, Aswinmcw approved these changes
LGTM, please check the failing static check

2024-09-30 16:22 UTC, umadevimcw requested changes

2024-09-30 16:22 UTC, umadevimcw commented on tests/sweep_framework/sweeps/eltwise/unary/abs/abs.py
> +    "abs": {
change suite name to `nightly`

2024-10-01 15:58 UTC, jdesousa-TT approved these changes

2024-10-05 06:29 UTC, umadevimcw approved these changes

2024-10-05 15:02 UTC, jdesousa-TT approved these changes

2024-10-07 04:56 UTC, eyonland approved these changes

2024-10-15 11:10 UTC, merged