#13143: Add documentation for core, set_printoptions ops
tenstorrent/tt-metal pull request #13199
Opened 2024-09-27 12:54 UTC by mcw-anasuya

### Ticket
Link to Github Issue: #13143

### What's changed
- Updated description according to PyTorch Reference
- Added examples to ops
- Fixed additional bugs

### List of Ops

- [x] ttnn.as_tensor
- [x] ttnn.from_torch
- [x] ttnn.to_torch
- [x] ttnn.to_device
- [x] ttnn.from_device
- [x] ttnn.to_layout
- [x] ttnn.dump_tensor
- [x] ttnn.load_tensor
- [x] ttnn.deallocate
- [x] ttnn.reallocate
- [x] ttnn.to_memory_config
- [x] ttnn.set_printoptions

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/11072314301) - PASSED

2024-09-27 13:44 UTC, umadevimcw requested changes

2024-09-27 13:44 UTC, umadevimcw commented on ttnn/cpp/pybind11/operations/core.hpp
> +            Example:
Can you add blocking param in the example?

2024-09-27 13:44 UTC, umadevimcw commented on ttnn/cpp/pybind11/operations/core.hpp
> +        Example:
Can we add `force` flag in example as well?

2024-09-27 14:04 UTC, umadevimcw approved these changes

2024-09-27 14:08 UTC, Aswinmcw approved these changes
LGTM

2024-09-27 14:08 UTC, VirdhatchaniKN approved these changes

2024-09-30 05:24 UTC, eyonland approved these changes

2024-10-04 06:11 UTC, ayerofieiev-tt approved these changes

2024-10-04 07:16 UTC, cfjchu approved these changes

2024-10-04 09:35 UTC, merged