#344: Allow CBs to have multiple buffer indices to enable CBs sharing address spaces
tenstorrent/tt-metal pull request #1319
Opened 2023-06-22 20:22 UTC by abhullar-tt

This is an interim change until CB is refactored to separate CB config from the underlying buffer

2023-06-22 21:16 UTC, arakhmati approved these changes

2023-06-22 21:20 UTC, arakhmati requested changes

2023-06-22 22:26 UTC, davorchap approved these changes

2023-06-23 15:45 UTC, DrJessop approved these changes
Just approving changes to command_queue.cpp

2023-06-23 16:14 UTC, arakhmati approved these changes

2023-06-23 16:19 UTC, merged