Add doc for tensor creation ops
tenstorrent/tt-metal pull request #13198
Opened 2024-09-27 11:42 UTC by ruthreshx

### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/7957)

### Problem description
Add doc for tensor creation ops

### Checklist
- [ ] Post commit CI passes

2024-09-27 11:49 UTC, umadevimcw requested changes

2024-09-27 11:49 UTC, umadevimcw commented on ttnn/cpp/pybind11/operations/creation.hpp
> +        +----------------------------+---------------------------------+-------------------+
@ruthreshx if Zeros is not supporting the Row Major kindly update the layout column in the table

2024-10-01 15:58 UTC, jdesousa-TT requested changes

2024-10-01 15:58 UTC, jdesousa-TT commented on tests/sweep_framework/sweeps/eltwise/unary/zeros/zeros.py
> +    "zeros": {
I'd suggest making this nightly so it will run automatically in CI.

2024-10-01 15:58 UTC, jdesousa-TT commented on tests/sweep_framework/sweeps/eltwise/unary/zeros_like/zeros_like.py
> +    "zeros_like": {
Same comment as above.

2025-04-03 00:29 UTC, closed without merging