#10347: Update documentation and sweep config for rsub and rdiv
tenstorrent/tt-metal pull request #13501
Opened 2024-10-04 21:48 UTC by mcw-anasuya

### Ticket
#10347  

### Problem description
Documentation incomplete for rsub and rdiv ops with supported params

### What's changed
Updated doc and corresponding sweep test files

### Checklist
- [ ] Post commit CI passes
- [ ] Run Sweeps

2024-10-05 06:32 UTC, Aswinmcw requested changes

2024-10-05 06:32 UTC, Aswinmcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +void bind_unary_rdiv(py::module& module, const unary_operation_t& operation, const std::string& parameter_name_a, const std::string& parameter_a_doc, const std::string& parameter_name_b, const std::s
Please add note=" "

2024-10-05 06:32 UTC, Aswinmcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +    detail::bind_unary_operation_with_float_parameter(module, ttnn::elu, "alpha", "The alpha parameter for the ELU function", "",
And remove here

2024-10-05 09:11 UTC, Aswinmcw approved these changes
LGTM

2024-10-05 12:30 UTC, VirdhatchaniKN approved these changes

2024-10-08 18:51 UTC, jdesousa-TT approved these changes
Pls run sweeps pipeline before merging

2024-10-09 05:06 UTC, eyonland approved these changes

2024-10-09 06:39 UTC, merged