#0: remove device arg from maxpool2d
tenstorrent/tt-metal pull request #13615
Opened 2024-10-09 01:16 UTC by mywoodstock

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-10-09 23:15 UTC, tt-aho approved these changes

2024-10-10 01:03 UTC, esmalTT approved these changes

2024-10-10 11:44 UTC, pavlejosipovic approved these changes

2024-10-10 13:03 UTC, tt-rkim requested changes

2024-10-10 18:23 UTC, tt-rkim approved these changes

2024-10-10 18:23 UTC, tt-rkim commented
awesome , hope no pipes break lol i hate these kinds of changes, you never know what'll happen

2024-10-10 18:50 UTC, ayerofieiev-tt approved these changes

2024-10-10 18:52 UTC, merged