#13404: Add data parallel support for lenet  model- WIP
tenstorrent/tt-metal pull request #13679
Opened 2024-10-10 12:54 UTC by sabira-mcw

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-11-20 16:17 UTC, tt-rkim commented
Do you have CI links?

2024-11-21 05:21 UTC, sabira-mcw commented
@tt-rkim 
We don't have CI links at the moment. I've been updating the code by replacing torch ops with ttnn ops, which are supported in the latest main branch for single-device implementations. However, I'm encountering issues when trying to run it in a data parallel setup. Once these issues are resolved, we can provide the CI links.

2024-11-27 18:38 UTC, tt-rkim commented
OK

2024-11-27 18:38 UTC, tt-rkim commented
Please message when done

2024-11-28 20:38 UTC, tt-rkim commented
Still blocking on you. Thanks

2024-11-29 14:05 UTC, sabira-mcw commented
We are currently blocked on this  due to a reshape issue - [#15422](https://github.com/tenstorrent/tt-metal/issues/15422) in the model and have not triggered the CIs furthur.

2024-12-02 15:58 UTC, tt-rkim commented
OK thanks. Please message in #tt-metal-pr-review-requests when ready

2024-12-03 04:01 UTC, saichandax commented
Currently blocked due to reshape issue: https://github.com/tenstorrent/tt-metal/issues/15422 (expected to be fixed by this week, as mentioned by @naif)
cc: @boris-drazic , @uaydonat , @tt-rkim

2024-12-03 18:13 UTC, uaydonat requested changes
blocked until @esmalTT reviews

2025-06-11 16:17 UTC, bbradelTT commented
@uaydonat should this be closed?

2025-06-27 21:29 UTC, nsextonTT commented
Closing as stale.

2025-06-27 21:29 UTC, closed without merging