Output memory config for conv2d and max_pool2d
tenstorrent/tt-metal pull request #13708
Opened 2024-10-10 21:03 UTC by mywoodstock

### Ticket
#13106 

### Problem description
Need optional output memory config

### What's changed
`memory_config` parameter added (optional).

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-10-10 21:12 UTC, bbradelTT commented on tests/ttnn/unit_tests/operations/test_maxpool2d.py
> +        # memory_config=ttnn.DRAM_MEMORY_CONFIG,
Please don't add commented out code.

If you want to test a specific memory config add code for it. If you want to say that a specific config will be used just add a comment stating that.

2024-10-10 22:09 UTC, bbradelTT approved these changes

2024-10-10 22:23 UTC, cfjchu approved these changes

2024-10-11 07:07 UTC, pavlejosipovic requested changes
Add at least some tests to make sure that optional mem config is applied

2024-10-14 07:50 UTC, pavlejosipovic requested changes
> Add at least some tests to make sure that optional mem config is applied 

I still don't see any tests for maxpool?

2024-10-14 07:50 UTC, pavlejosipovic commented on tests/ttnn/unit_tests/operations/test_new_conv2d.py
> +@pytest.mark.parametrize(
No need for params that have only one option, they just polute the file

2024-10-14 07:50 UTC, pavlejosipovic commented on tests/ttnn/unit_tests/operations/test_new_conv2d.py
> +        memory_config=memory_config,
if we don't assert that this is the memory layout of the output tensor, there is no much point in having this test

2024-10-15 06:46 UTC, pavlejosipovic approved these changes

2024-10-16 03:45 UTC, sankarmanoj-tt approved these changes

2024-10-16 16:47 UTC, merged