#13609: Uplift dram and l1 allocators to use dram/l1 specific alignment
tenstorrent/tt-metal pull request #13762
Opened 2024-10-11 21:17 UTC by abhullar-tt

### Ticket
#13609

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-10-22 05:27 UTC, tt-aho submitted a review, later dismissed
Changes look good.

Will the op changes be added to this PR before merge?
Want to make sure no models break with these changes

2024-10-22 05:27 UTC, tt-aho commented on tt_metal/hw/inc/dataflow_api.h
> +    const uint32_t log_base_2_of_allocator_alignment = interleaved_addr_gen::get_log_base2_of_allocator_alignment<DRAM>();
`log_base_2_of_allocator_alignment` can be constexpr?

2024-10-22 05:27 UTC, tt-aho commented on tt_metal/hw/inc/dataflow_api.h
> +    const uint32_t log_base_2_of_allocator_alignment = interleaved_addr_gen::get_log_base2_of_allocator_alignment<DRAM>();
`log_base_2_of_allocator_alignment` can be constexpr?

2024-10-22 05:29 UTC, abhullar-tt commented
> Changes look good.
> 
> Will the op changes be added to this PR before merge? Want to make sure no models break with these changes

yes, before merging we will run all the model tests

2024-10-28 14:27 UTC, arikTT commented on tt_metal/hw/inc/dataflow_api.h
> +    uint32_t addr = (bank_offset_index * align(page_size, interleaved_addr_gen::get_allocator_alignment<true>())) + bank_base_address + offset + bank_to_dram_offset[bank_index];
Is there a reason you use true/flase in lines 580/589 where you use DRAM/ in line 915. I find the latter much more readable

2024-12-20 16:42 UTC, bbradelTT approved these changes

2024-12-20 16:42 UTC, bbradelTT commented on ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp
>      // FIXME: assumes that this was sharded using DRAM alignment so that gaps are left in the tensor.
Should this comment be udpated as well?

2024-12-20 16:42 UTC, bbradelTT commented on tech_reports/prog_examples/shard_data_rm/shard_data_rm.md
> +uint32_t padded_offset_bytes = align(input_unit_size, device->get_allocator_alignment(BufferType::L1));
It might be good to add more info about when you need or when the infra uses different alignments and why.

2024-12-20 17:21 UTC, tt-aho commented on ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp
> +    uint32_t alignment = device->get_allocator_alignment(dst_buffer->buffer_type());
Use `dst_buffer->alignment()` instead

2024-12-20 17:21 UTC, tt-aho commented on ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp
> +    auto dram_alignment_bytes = tt::tt_metal::hal.get_alignment(tt::tt_metal::HalMemType::L1);
Should be renamed to `l1_alignment_bytes`?

2024-12-20 17:21 UTC, tt-aho commented on tt_metal/impl/device/device.hpp
> +    uint32_t get_allocator_alignment(SubDeviceId sub_device_id, const BufferType &buffer_type) const;
Can you make sub_device_id the last arg to keep it consistent with other apis?

2024-12-20 17:46 UTC, abhullar-tt commented on tt_metal/impl/device/device.cpp
> +    return (buffer_type == BufferType::DRAM) ? this->allocator_->config.dram_alignment : this->allocator_->config.l1_alignment;
will update

2025-01-02 21:39 UTC, yugaoTT approved these changes

2025-01-02 21:39 UTC, yugaoTT commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py
> +    yt = ttnn.interleaved_to_sharded(xt, grid_size, shard_size, shard_scheme, shard_orientation, keep_l1_aligned=True)
will keep_l1_aligned be removed in the final PR (ie, always use L1 alignment for sharded in L1)?

2025-01-02 21:39 UTC, yugaoTT commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py
> +        is_l1_aligned=True,
same here

2025-01-02 21:44 UTC, llongTT commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py
> +    yt = ttnn.interleaved_to_sharded(xt, grid_size, shard_size, shard_scheme, shard_orientation, keep_l1_aligned=True)
Maybe in a different PR. To avoid making this PR super heavy.

2025-01-06 17:23 UTC, sjameelTT commented on tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/common.h
>      uint32_t start_page,
we probably want to change this to buffer_type at some point (unrelated to this PR)

2025-01-06 17:23 UTC, sjameelTT commented on ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp
> +    uint32_t per_core_N_bytes_padded = round_up_to_mul16(per_core_N * datum_size_bytes);
do we have a tt::round_up(value, alignment)?

2025-01-06 17:25 UTC, abhullar-tt commented
@llongTT could you re-run post-commit, BH post commit, Model tests, and ttnn sweeps and update the links in the PR description

2025-01-06 17:25 UTC, yugaoTT commented
Please also run the device perf and model pipelines, there are CNN models using group norm so need to make sure those are passing

2025-01-06 17:26 UTC, abhullar-tt commented
@cmaryanTT we may need to announce when this change goes in because using l1/dram specific alignment for allocating buffers could expose noc violations when doing misaligned dram -> l1 reads. We could explain how ops are handling this

2025-01-06 17:27 UTC, llongTT commented on ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp
> +    uint32_t per_core_N_bytes_padded = round_up_to_mul16(per_core_N * datum_size_bytes);
Yeah I think there are multiple implementation of the same functionality.

2025-01-06 17:29 UTC, jvegaTT commented on tt_metal/impl/dispatch/memcpy.hpp
> +        if ((uintptr_t)dst8 % sizeof(__m256i) != 0) {
Modulo can be quite expensive op and since sizeof is used I don't know how well the optimizer is at realizing this can be done very quickly using bitwise rather than division. I am assuming this is a 256b datatype, if so you could use bitwise operations itself

2025-01-06 17:31 UTC, jvegaTT approved these changes

2025-01-06 17:31 UTC, jvegaTT commented on tt_metal/impl/dispatch/memcpy.hpp
> +        if ((uintptr_t)dst8 % sizeof(__m256i) != 0) {
Same applies to __m128i below

2025-01-06 17:40 UTC, llongTT commented on tt_metal/impl/dispatch/memcpy.hpp
> +        if ((uintptr_t)dst8 % sizeof(__m256i) != 0) {
This is host side code so I think it's OK

2025-01-06 17:45 UTC, llongTT commented on tech_reports/prog_examples/shard_data_rm/shard_data_rm.md
> +uint32_t padded_offset_bytes = align(input_unit_size, device->get_allocator_alignment(BufferType::L1));
Added a bit more info regarding the get_allocator_alignment() call

2025-01-06 17:50 UTC, llongTT commented on ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp
> +    auto dram_alignment_bytes = tt::tt_metal::hal.get_alignment(tt::tt_metal::HalMemType::L1);
Renamed

2025-01-06 17:53 UTC, llongTT commented on ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp
> +    uint32_t alignment = device->get_allocator_alignment(dst_buffer->buffer_type());
function call switched

2025-01-06 18:00 UTC, jvegaTT commented on tt_metal/impl/dispatch/memcpy.hpp
> +        if ((uintptr_t)dst8 % sizeof(__m256i) != 0) {
Its host side but it is in the memory copy to device function which I don't think can be parallelized away, however given that it is not inside the for loop I think your right, the gain is way too small to matter.

2025-01-06 18:03 UTC, llongTT commented on ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp
> +    uint32_t per_core_N_bytes_padded = round_up_to_mul16(per_core_N * datum_size_bytes);
changed to tt::round_up

2025-01-06 18:30 UTC, llongTT commented
> @llongTT could you re-run post-commit, BH post commit, Model tests, and ttnn sweeps and update the links in the PR description

Have them running now.

2025-01-06 18:31 UTC, llongTT commented
> Please also run the device perf and model pipelines, there are CNN models using group norm so need to make sure those are passing

Have them running now.

2025-01-06 18:35 UTC, cmaryanTT commented
> @cmaryanTT we may need to announce when this change goes in because using l1/dram specific alignment for allocating buffers could expose noc violations when doing misaligned dram -> l1 reads. We could explain how ops are handling this

Noted. @llongTT - please announce on #tt-metal-developers with a brief description of the change and the risks.

Also, @llongTT will be presenting this in the learning forum in a couple of weeks.

2025-01-06 18:43 UTC, sjameelTT approved these changes

2025-01-13 18:13 UTC, pgkeller approved these changes

2025-01-14 16:20 UTC, aliuTT approved these changes

2025-01-15 20:00 UTC, llongTT approved these changes

2025-01-15 22:35 UTC, mywoodstock approved these changes

2025-01-16 03:13 UTC, omilyutin-tt requested changes
Changes to mesh device lgtm

2025-01-16 03:13 UTC, omilyutin-tt commented on tt_metal/impl/device/device.hpp
Please fix the clang diagnostic errors

2025-01-16 23:59 UTC, llongTT commented on tt_metal/impl/device/device.hpp
Those are out of date

2025-01-17 21:11 UTC, llongTT commented on ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp
> +    uint32_t alignment = dst_buffer->buffer_type() == tt::tt_metal::BufferType::DRAM ? hal::get_dram_alignment();
out of date

2025-01-17 21:14 UTC, omilyutin-tt approved these changes

2025-01-25 05:40 UTC, merged