Expose conv2d weight/bias preparation as ops.
tenstorrent/tt-metal pull request #13828
Opened 2024-10-15 20:48 UTC by LPanosTT

Issue: https://github.com/tenstorrent/tt-metal/issues/13219

Work in progress.

2024-10-17 05:25 UTC, sankarmanoj-tt requested changes
Can we move the new prepare weights/bias functions to another file?

2024-10-17 08:14 UTC, pavlejosipovic reviewed
Should we use these metods internally as well?

2024-10-18 13:09 UTC, LPanosTT commented
> Should we use these metods internally as well?

Not sure. If It were up to me I'd say it's probably a good idea to phase out the old conv2d and replace its use with this newer, more explicit one. But I'm not on this team so, up to you guys.

2024-10-18 13:12 UTC, pavlejosipovic commented
> > Should we use these metods internally as well?
> 
> Not sure. If It were up to me I'd say it's probably a good idea to phase out the old conv2d and replace its use with this newer, more explicit one. But I'm not on this team so, up to you guys.

Maybe I'm not following this well enough, but it seems to me that with your change we get c/p code?

2024-10-18 13:53 UTC, LPanosTT commented
> > > Should we use these metods internally as well?
> > 
> > 
> > Not sure. If It were up to me I'd say it's probably a good idea to phase out the old conv2d and replace its use with this newer, more explicit one. But I'm not on this team so, up to you guys.
> 
> Maybe I'm not following this well enough, but it seems to me that with your change we get c/p code?

Yes we do, certainly. I can replace the old weight/bias preparation function with calls to this new one.

2024-10-18 15:27 UTC, bbradelTT commented
This change looks a lot bigger than exposing weight/bias preparation as ops.

Why are all the changes and extra code needed?

2024-10-18 15:31 UTC, LPanosTT commented
> This change looks a lot bigger than exposing weight/bias preparation as ops.
> 
> Why are all the changes and extra code needed?

The added ops are mostly copied from the old `prepare_conv_weights_biases_and_move_to_device` function. Other than that I'm not sure what you mean by code changes. No logic has been changed. I've pybinded he new op(s) aswell which took a fair number of added lines.

2024-10-18 15:37 UTC, bbradelTT commented
> > This change looks a lot bigger than exposing weight/bias preparation as ops.
> > Why are all the changes and extra code needed?
> 
> The added ops are mostly copied from the old `prepare_conv_weights_biases_and_move_to_device` function. Other than that I'm not sure what you mean by code changes. No logic has been changed. I've pybinded he new op(s) aswell which took a fair number of added lines.
> 
> This change is necessary because we want to model the weight preparation in MLIR so that we may push all weights to device before runtime.

conv2d.cpp seems to get 597 new lines. An example of the change is
![image](https://github.com/user-attachments/assets/188d537d-c677-4b51-8e16-0bc02ef2cfa5)

2024-10-18 15:44 UTC, LPanosTT commented
@bbradelTT The weight and bias preparation require data held by pre-computed `ParrallelConfig`s, `OptimizedConvBlockConfig`, etc... These were computed in the `conv2d` function and then the specific data was passed to `prepare_conv_weights_biases_and_move_to_device`. These configs are ultimately generated using information about the convolution (dtype, image dimensions, filter dimensions, padding, groups, ...) and the device (grid size, etc). So in order to expose the weight and bias preparation as ops that are user friendly, I'd need to allow them to prepare the weights/bias using the convolution data they already have defined. 

I will do some cleanup to compartmentalize duplicated code that are used by `prepare_conv_bias_for_ttnn` and `prepare_conv_weight_for_ttnn`

2024-10-18 16:03 UTC, bbradelTT commented
> @bbradelTT The weight and bias preparation require data held by pre-computed `ParrallelConfig`s, `OptimizedConvBlockConfig`, etc... These were computed in the `conv2d` function and then the specific data was passed to `prepare_conv_weights_biases_and_move_to_device`. These configs are ultimately generated using information about the convolution (dtype, image dimensions, filter dimensions, padding, groups, ...) and the device (grid size, etc). So in order to expose the weight and bias preparation as ops that are user friendly, I'd need to allow them to prepare the weights/bias using the convolution data they already have defined.
> 
> I will do some cleanup to compartmentalize duplicated code that are used by `prepare_conv_bias_for_ttnn` and `prepare_conv_weight_for_ttnn`

Cleanup will be good. Thanks.

2024-10-18 17:05 UTC, mywoodstock commented
> > Should we use these metods internally as well?
> 
> Not sure. If It were up to me I'd say it's probably a good idea to phase out the old conv2d and replace its use with this newer, more explicit one. But I'm not on this team so, up to you guys.

Yes we need to -- might be better to do it as a subsequent PR.

2024-10-21 13:14 UTC, bbradelTT approved these changes

2024-10-21 15:52 UTC, pavlejosipovic commented on ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp
> +std::tuple<OptimizedConvBlockConfig, TensorMemoryLayout> get_opt_conv_op_block_config_and_shard_layout(
is this function still c/p code?

2024-10-21 15:53 UTC, pavlejosipovic reviewed
Can you maybe abandon this PR and send new one which doesn't have this clang tidy crap (it's off now)?

2024-10-21 15:54 UTC, LPanosTT commented
> Can you maybe abandon this PR and send new one which doesn't have this clang tidy crap (it's off now)?

Sure no problem.

2024-10-21 15:54 UTC, closed without merging