#1397: Refactor yolov3 model dir structure. Add new modules.
tenstorrent/tt-metal pull request #1398
Opened 2023-06-27 17:19 UTC by JelenaTosicJtosic

Adding new ported modules and refactoring Yolo v3 model directory structure so that it matches the newest guidelines.

- Replaced old reference model scripts with new, so that the reference model structure matches the original one (from Ultralytics)
- Moved tests to tests folder
- Moved module implementations to tt folder
- Also cpu demo was added in demo folder.

2023-06-28 14:28 UTC, farbabi requested changes
This refactoring is not following the standards. Is the reference implementations from hugging face? If so, it should be removed. Why there is a utils folder? Where is the GS demo?
Request re-review when it is according to standards.

2023-06-28 19:53 UTC, ashayestehmanesh requested changes
Also run black on all your files.

2023-06-29 19:02 UTC, ashayestehmanesh approved these changes

2023-06-29 19:12 UTC, farbabi approved these changes

2023-06-29 19:37 UTC, tt-nshanker approved these changes

2023-06-30 13:40 UTC, merged