Multiple op hang issue
tenstorrent/tt-metal pull request #14318
Opened 2024-10-26 07:30 UTC by umadevimcw

### Ticket
#4702 

### Problem description
- Test was hanging and Row Major layout was used

### What's changed
- Updated the layput in test files

### Checklist
- [ ] Post commit CI passes

2024-10-26 09:32 UTC, Aswinmcw approved these changes
LGTM

2024-10-26 18:55 UTC, VirdhatchaniKN approved these changes

2024-10-29 02:14 UTC, eyonland requested changes
Please update the documentation to reflect that we only support TILE here.
It seems to be missing on pointwise ops.  Example https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/gelu.html but I do see it on the binary ones.

2024-10-29 10:54 UTC, umadevimcw commented
> ###
> 1 review requesting changes and 2 approving reviews by reviewers with write access. [Learn more about pull request reviews.](https://docs.github.com/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews)
> ** 1 change requested **
> [<img alt="@eyonland" width="20" height="20" src="https://avatars.githubusercontent.com/u/41128502?s=40&amp;v=4">](/eyonland)
> ** eyonland ** requested c

Updated @eyonland

2024-10-29 10:56 UTC, umadevimcw commented
> Please update the documentation to reflect that we only support TILE here. It seems to be missing on pointwise ops. Example https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/gelu.html but I do see it on the binary ones.

Updated @eyonland

![Uploading Screenshot 2024-10-29 at 4.18.24 PM.png…]()

2024-10-30 14:30 UTC, eyonland approved these changes

2024-11-03 03:07 UTC, ayerofieiev-tt commented
Reading the ticket, this change is.. hiding the issue???
Why does it hang? 
Why switching to Tiled layout helps? 
When will Row Major case be fixed?

2024-11-03 03:08 UTC, ayerofieiev-tt commented
Also if the op does not support the input, it must gracefully handle that.

2024-11-03 03:53 UTC, dmakoviichuk-tt requested changes
Ill take a look on Monday. please don't merge.
It looks super strange.
In general we fix issue if tests fails but not the test :-D

2024-11-04 05:16 UTC, umadevimcw commented
@ayerofieiev-tt @dmakoviichuk-tt FYI, the #4702 was created few months back(before the new infra we have now) and team has done some analysis and added the comments as well https://github.com/tenstorrent/tt-metal/issues/4702#issuecomment-2084901737. 

With the new infra since we don't have RM support yet, now the test failed with Layout issue. Hence in this PR, updated the test files and documentation as well.

2024-11-15 09:18 UTC, closed without merging