#0: Add MEM_MAILBOX_BASE to Hal
tenstorrent/tt-metal pull request #14362
Opened 2024-10-28 16:46 UTC by blozano-tt

### Ticket
closes #14329
#596 

### Problem description
To make cpp file not directly include dev_mem_map.h avoid need for ARCH_NAME include path here.

### What's changed
Added the L1 address MEM_MAILBOX_BASE available behind Hal.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-10-28 17:01 UTC, abhullar-tt requested changes, later dismissed

2024-10-28 17:01 UTC, abhullar-tt commented on tt_metal/llrt/blackhole/bh_hal_idle_eth.cpp
> +    mem_map_bases[utils::underlying_type<HalL1MemAddrType>(HalL1MemAddrType::MAILBOX)] = MEM_MAILBOX_BASE;
this should be `MEM_IERISC_MAILBOX_BASE` same for for the wh idle eth

2024-10-28 17:01 UTC, abhullar-tt commented on tt_metal/llrt/blackhole/bh_hal_active_eth.cpp
> +    mem_map_bases[utils::underlying_type<HalL1MemAddrType>(HalL1MemAddrType::MAILBOX)] = MEM_MAILBOX_BASE;
this should be `eth_l1_mem::address_map::ERISC_MEM_MAILBOX_BASE` same for wh active eth

2024-10-29 17:02 UTC, pgkeller approved these changes

2024-10-29 17:22 UTC, merged