#11086: Update bind unary backward documentation
tenstorrent/tt-metal pull request #14376
Opened 2024-10-28 18:32 UTC by mcw-anasuya

### Ticket
#11086 

### Problem description
Incomplete/missing Documentation on supported params

### What's changed
Updated supported dtypes, layouts and ranks for unary backward ops

### Checklist
- [ ] Post commit CI passes
- [ ] New/Existing tests provide coverage for changes

2024-11-06 12:00 UTC, Aswinmcw approved these changes
LGTM

2024-11-06 12:25 UTC, umadevimcw approved these changes

2024-11-06 12:25 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Remove this table and use the list table format.

2024-11-06 12:25 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Remove this table and use the list table format.

2024-11-06 12:25 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Remove this table and use the list table format.

2024-11-06 12:25 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT8_B               |       TILE                      |      2, 3, 4      |
Remove this table and use the list table format.

2024-11-06 12:25 UTC, umadevimcw approved these changes

2024-11-06 12:26 UTC, mouliraj-mcw approved these changes

2024-11-06 12:31 UTC, umadevimcw requested changes

2024-11-06 12:31 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Replace this table with list table format

2024-11-06 12:31 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           +----------------------------+---------------------------------+-------------------+
Replace this table with list table format

2024-11-06 12:31 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Replace this table with list table format

2024-11-06 12:31 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward_pybind.hpp
> +           |    BFLOAT16, BFLOAT8_B     |       TILE                      |      2, 3, 4      |
Replace this table with list table format

2024-11-06 12:50 UTC, umadevimcw approved these changes

2024-11-06 13:05 UTC, VirdhatchaniKN approved these changes

2024-11-07 05:46 UTC, eyonland approved these changes

2024-11-07 10:15 UTC, merged