#1460: new operators for on-device tensor, activations, ternary selection where, unary tied version of binops
tenstorrent/tt-metal pull request #1454
Opened 2023-06-29 18:30 UTC by muthutt

#1460: new operators for on-device tensor, activations, ternary selection where, unary tied version of binops

operators for unary tied version of binops, on-device tensor creation, ternary where + tests

Creation
---------
- zeros
- ones
- full
- zeros_like
- ones_like
- full_like
- arange

Activation
----------
- clip
- clamp
- hardtanh
- where

Unary (tied to Binary)
---------------------
- {add,sub,mul,div}_unary

Testing
-------
- update compilation and bindings for add/sub/div/mul _unary operations
- still tests TBD
- add tests for unary add, sub, div, and mul
- add tests for zeros, ones and full on-chip operators
- add test for clip, hardtanh activation
- add tests (passing) for add, sub, mul, div unary
- fix clip implementation
- add tests for zeros, ones and full
- use where function implementation - https://pytorch.org/docs/stable/generated/torch.where.html

2023-06-29 22:07 UTC, arakhmati requested changes

2023-06-29 22:36 UTC, tt-aho requested changes

2023-06-29 23:18 UTC, mywoodstock approved these changes
lgtm

2023-06-30 14:42 UTC, TT-BrianLiu approved these changes

2023-06-30 16:20 UTC, arakhmati approved these changes
Looks good!

2023-06-30 16:22 UTC, tt-nshanker approved these changes

2023-06-30 16:42 UTC, tt-aho approved these changes
lgtm. If we are binding the versions with the scaler first, then just add tests and rerun pipelines. Otherwise if we want to do this in a separate pr/when we need it then this looks good to merge

2023-06-30 19:53 UTC, merged