#1320: Add Multicore support split of tensor (W,Z,Y,X)
tenstorrent/tt-metal pull request #1461
Opened 2023-06-29 21:50 UTC by ntarafdar

- First parallelized on z
 - Second parallelized on y
 - Lastly parallelized on X
 

Z,Y Parallelized on the 12 Cores
X Parallelized on 8 Cores

@tt-aho , @TT-BrianLiu could you guys have a look at the small changes to the kernel 

@TT-BrianLiu , I think you have some experience parallelizing this particular op, so could you look at the host function where I set up my runtime arguments

@arakhmati , I didn't touch the code you added but could you make sure my code doesn't interfere with your override, runtime args

2023-07-07 17:16 UTC, arakhmati approved these changes

2023-07-07 18:01 UTC, mywoodstock approved these changes
lgtm! Do we have some runtime numbers to see if the multi-core version is performing as expected?

2023-07-07 18:09 UTC, tt-aho approved these changes

2023-07-07 20:44 UTC, TT-BrianLiu requested changes

2023-07-12 14:09 UTC, TT-BrianLiu approved these changes
I still see lots of commented out code and DPRINTS as well as references to q, k in the DataMovement kernels. After we clean this up, it LGTM.

2023-07-12 14:48 UTC, merged