[documentation update]: update docs to reflect new operators in tt_dnn library
tenstorrent/tt-metal pull request #1475
Opened 2023-07-01 00:05 UTC by muthutt

- Update tt_dnn.rst
- update of docs for various 20+ eltwise ops added to tt_dnn library
- update softplus table fmt

![image](https://github.com/tenstorrent-metal/tt-metal/assets/135061812/9a04dcc6-9612-4bc5-b6bd-1ca96e664a1b)

2023-07-01 00:16 UTC, tt-aho requested changes
These ops haven't been swept yet so I would put them in experimental. I will be running sweeps for the new ops over the weekend so we can add the passing ones to the appropriate section after they pass sweep tests.

So we can either put them in experimental or wait for sweep tests to pass

2023-07-07 00:45 UTC, mywoodstock approved these changes

2023-07-07 00:45 UTC, tt-nshanker approved these changes

2023-07-07 18:04 UTC, tt-aho approved these changes
All ops here have now been swept. Lgtm after you rebase and move/add these ops in my comments, then just run post commit to make sure docs correctly build.

2023-07-07 22:19 UTC, merged