Add device specific defines to kernel build command and hash
tenstorrent/tt-metal pull request #14753
Opened 2024-11-05 18:59 UTC by spoojaryTT

### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/13869)

### Problem description
Kernel build is dependent on header files generated from the device.

### What's changed
Removed NUM_DRAM_BANKS, NUM_L1_BANKS, LOG_BASE_2_OF_NUM_DRAM_BANKS, LOG_BASE_2_OF_NUM_L1_BANKS, IS_NOT_POW2_NUM_DRAM_BANKS and IS_NOT_POW2_NUM_L1_BANKS from gentiles.cpp and added them to the kernel build command.
Also added above defines to kernel build hash.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-11-05 22:35 UTC, pgkeller requested changes
minor

2024-11-05 22:35 UTC, pgkeller commented on tt_metal/impl/device/device.hpp
> +    std::map<std::string, std::string> device_kernel_defines;
use trailing "_" for class members

2024-11-07 16:23 UTC, pgkeller commented on tt_metal/impl/device/device.cpp
> +    this->device_kernel_defines_.clear();
I assume this is the fix for this getting called multiple times.  Can you add a comment about why the clear is needed and what it addresses?

2024-11-08 15:17 UTC, pgkeller approved these changes

2024-11-08 16:44 UTC, abhullar-tt approved these changes

2024-11-08 16:46 UTC, merged