#1483: leaky_relu, soft shrink, and soft sign
tenstorrent/tt-metal pull request #1485
Opened 2023-07-04 01:02 UTC by muthutt

1483: leaky_relu, soft shrink, and soft sign
- leaky_relu, soft shrink, soft sign - operators implementation
[operators] leaky_relu, softshrink, hardshrink
- add support and tests

2023-07-05 14:36 UTC, tt-aho requested changes

2023-07-05 16:17 UTC, mywoodstock approved these changes
LGTM after addressing @tt-aho 's comments.

2023-07-06 00:06 UTC, tt-aho approved these changes
lgtm once pipelines pass

2023-07-06 19:21 UTC, TT-BrianLiu approved these changes

2023-07-06 19:47 UTC, tt-nshanker approved these changes

2023-07-06 20:15 UTC, arakhmati approved these changes
LGTM!

2023-07-10 18:49 UTC, merged