#15395: update CB to accept 2 byte page size; Should run post-commits
tenstorrent/tt-metal pull request #15397
Opened 2024-11-22 22:31 UTC by yugi957

### Ticket
[#15395](https://github.com/tenstorrent/tt-metal/issues/15395)

### Problem description
CBs don't support page size for single bfloat16/uint16

### What's changed
Updated the Assert to enable 2 byte page sizes

### Checklist
- [ ] Post commit CI passes:

2024-11-22 22:35 UTC, tt-aho requested changes
I left a comment on the original issue but anything that is not a multiple of 16B for CB page/total size is not properly supported in kernels. This assert should have been for 16B because in the circular buffer interface values such as size, page size are stored divided by 16.

2024-11-23 06:26 UTC, tt-aho approved these changes

2024-11-23 06:26 UTC, tt-aho commented on tt_metal/impl/buffers/circular_buffer_types.hpp
>              TT_THROW("Page size must be divisible by sizeof(uint32_t) because buffers holds uint32_t values");
Thanks for fixing. Please fix the throw message as well otherwise lgtm if pipelines pass

2025-06-19 02:07 UTC, nsextonTT commented
@yugi957 @tt-aho  Is this PR stale or is there something you still want to merge?

2025-06-19 13:32 UTC, tt-aho commented
> @yugi957 @tt-aho Is this PR stale or is there something you still want to merge?

I believe this is stale and should be closed along with the corresponding issue.
There is an outstanding issue for adding proper assertions for compute kernel CB page size since that still has some restrictions https://github.com/tenstorrent/tt-metal/issues/15834, but otherwise this restriction/assert is no longer on main

2025-06-19 16:31 UTC, nsextonTT commented
Closing as stale.

2025-06-19 16:31 UTC, closed without merging