#12253: Support for Batch normalization
tenstorrent/tt-metal pull request #15595
Opened 2024-12-02 12:42 UTC by VirdhatchaniKN

### Ticket
https://github.com/tenstorrent/tt-metal/issues/12253
https://github.com/tenstorrent/tt-metal/issues/15372

### Problem description
Provide support for batch normalization 
https://pytorch.org/docs/stable/generated/torch.nn.functional.batch_norm.html

### What's changed

- Provided support for batch normalization 
- `data_gen_with_range_batch_norm ` to generate shape as in pytorch and pad the inputs to pass to `ttnn::batch_norm`
- Return running stats when in training - In Progress

### Checklist
- [ ] Post commit CI passes

2024-12-02 13:02 UTC, Aswinmcw approved these changes
LGTM

2024-12-02 13:31 UTC, mouliraj-mcw approved these changes

2024-12-02 13:49 UTC, umadevimcw requested changes

2024-12-02 13:49 UTC, umadevimcw commented on tests/ttnn/unit_tests/operations/eltwise/test_batch_norm.py
> +    # ttnn.set_printoptions(profile="full")
Add sweep test as well

2025-03-13 11:17 UTC, VirdhatchaniKN commented
Closing PR as device version is merged to main

2025-03-13 11:17 UTC, closed without merging