#15290: Fix UAF issue with Singleton destruction order
tenstorrent/tt-metal pull request #15689
Opened 2024-12-04 04:29 UTC by cfjchu

- Decouple MeshDevice destruction from SystemMesh destruction.
- Refactor SystemMesh to encapsulate internals in pImpl class.
- Added a new test case for SystemMesh tear down with static mesh in the distributed tests.

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-12-04 16:07 UTC, omilyutin-tt requested changes
Looks good, mostly nits. Fwiw, I don't think that storing a mesh device in a static global is a good pattern:)

2024-12-04 18:21 UTC, cfjchu commented
> Looks good, mostly nits. Fwiw, I don't think that storing a mesh device in a static global is a good pattern:)

Yeah, agreed. The reason I'm refactoring this and restricting the interface is to make it easier to change this in a follow-on PR.

2024-12-04 18:25 UTC, cfjchu commented on tests/ttnn/distributed/test_distributed_atexit.cpp
> +static std::shared_ptr<ttnn::MeshDevice> mesh;
I wanted to capture the unit test that was in the original issue request, but I think file-scoped static should work as well. Thanks!

2024-12-04 18:28 UTC, cfjchu commented on tt_metal/distributed/mesh_device.cpp
> +    std::unordered_map<chip_id_t, PhysicalCoordinate> physical_device_id_to_coordinate;
Yes, the code-style is inconsistent but there are a few patterns I see for class attributes:
1) `_` suffix
2) `this`
3) neither (1) or (2)

We should make it consistent at least with all the code within `distributed` so I'd be fine to adopt (1)

2024-12-04 18:30 UTC, cfjchu commented on tt_metal/distributed/mesh_device.cpp
> +        if (assigned_devices.count(mesh_id)) {
yeah, should be fine. I'll udpate.

2024-12-04 18:34 UTC, omilyutin-tt commented on tt_metal/distributed/mesh_device.cpp
> +    std::unordered_map<chip_id_t, PhysicalCoordinate> physical_device_id_to_coordinate;
Yeah, I'd say (1) has a big advantage that once you put the name down there is no place for ambiguity. While `this->` is completely optional and requires you to always think about it.

2024-12-04 21:40 UTC, cfjchu commented on tt_metal/distributed/mesh_device.hpp
> +    std::unique_ptr<Impl> pimpl;
done

2024-12-04 21:40 UTC, cfjchu commented on tt_metal/distributed/mesh_device.cpp
> +    std::vector<MeshDeviceID> stale_ids;
done

2024-12-04 21:40 UTC, cfjchu commented on tt_metal/distributed/mesh_device.hpp
>      // Return the shape of the logical mesh
done

2024-12-04 21:42 UTC, cfjchu commented on tt_metal/distributed/mesh_device.cpp
> +    std::unordered_map<chip_id_t, PhysicalCoordinate> physical_device_id_to_coordinate;
Agreed. I've switched it for SystemMesh attributes and will follow-up in another PR for the other classes.

2024-12-04 21:42 UTC, cfjchu commented on tt_metal/distributed/mesh_device.cpp
> +    this->register_mesh_device(mesh_device, mapped_devices);  // here
Removed and replaced with a comment

2024-12-05 09:34 UTC, cfjchu commented on tests/ttnn/distributed/test_distributed_atexit.cpp
> +static std::shared_ptr<ttnn::MeshDevice> mesh;
done

2024-12-05 09:34 UTC, cfjchu commented on tests/ttnn/distributed/test_distributed_atexit.cpp
> +};
done

2024-12-05 20:25 UTC, omilyutin-tt approved these changes
Looks good!

2024-12-06 19:14 UTC, merged