Formating conv2d output
tenstorrent/tt-metal pull request #15741
Opened 2024-12-05 13:27 UTC by shwetankTT

### Ticket
#14179 

### Problem description
Parameterized conv2d output from the Python side:
Users can select the desired output. By default, the function returns the convolution output (conv_output). However, users have the option to receive additional outputs, including the output dimensions, weights, and biases, depending on their needs.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-12-06 04:55 UTC, shwetankTT commented
[(Single-card) Demo tests](https://github.com/tenstorrent/tt-metal/actions/runs/12180275847)
[(Single-card) Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/runs/12180270772)
[(Single-card) Model perf tests](https://github.com/tenstorrent/tt-metal/actions/runs/12180238600)
[Nightly fast dispatch tests](https://github.com/tenstorrent/tt-metal/actions/runs/12180236565)

2024-12-06 16:09 UTC, tt-aho approved these changes

2024-12-06 16:12 UTC, esmalTT requested changes
I am seeing failures in Mamba on the nightly pipeline that don't appear on main: https://github.com/tenstorrent/tt-metal/actions/runs/12180236565/job/33990661239#step:9:964

Can you rebase with latest and try again?

2024-12-06 16:14 UTC, sjameelTT approved these changes

2024-12-06 17:08 UTC, kpaigwar approved these changes

2024-12-06 18:43 UTC, shwetankTT commented
@esmalTT Hey Evan Can you please unblock me so that I can merge the PR over the weekend. I am running all the pipelines again. Hopefully they pass.
https://github.com/tenstorrent/tt-metal/actions/runs/12203020768/job/34046783895

2024-12-06 18:49 UTC, esmalTT approved these changes

2024-12-06 19:52 UTC, mywoodstock approved these changes

2024-12-07 04:54 UTC, ayerofieiev-tt approved these changes
No review, unblocking.

2024-12-09 02:18 UTC, uaydonat approved these changes

2024-12-09 15:32 UTC, bbradelTT approved these changes

2024-12-09 16:58 UTC, dvartaniansTT approved these changes
LGTM

2024-12-09 19:11 UTC, merged