Revert "#1365: Split/restructure dataflow kernel api"
tenstorrent/tt-metal pull request #1591
Opened 2023-07-11 22:53 UTC by mywoodstock

This reverts commit 1764a2407df32b69ffe5e2c93502fc2822f5e304 as it caused perf regression in BERT.

2023-07-11 23:35 UTC, DrJessop approved these changes

2023-07-11 23:46 UTC, muthutt approved these changes
LGTM -

please add a reason as to why this is being reverted.

2023-07-12 05:08 UTC, davorchap approved these changes

2023-07-12 11:48 UTC, tt-rkim approved these changes

2023-07-12 12:43 UTC, tt-rkim requested changes
Whoa actually hold up please redo your commits to have no merge commits and redo your messages to have issues numbers during reverts
Good thing we caught this

2023-07-12 15:57 UTC, tt-rkim approved these changes

2023-07-12 17:05 UTC, merged