#16012: Revert mm changes because we see instability in tt-train tests
tenstorrent/tt-metal pull request #16020
Opened 2024-12-13 20:35 UTC by tt-rkim

### Ticket

#16012 

### Problem description

Something in these changes causes instability in tt-train tests

### What's changed

Discussed with @yugaoTT , @bbradelTT , and @dmakoviichuk-tt 

We decided to revert, file issue, and investigate after the holidays.
Will re-enable tt-train tests

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

2024-12-13 20:37 UTC, bbradelTT approved these changes

2024-12-13 20:41 UTC, afuller-TT approved these changes

2024-12-13 22:44 UTC, bbradelTT requested changes
Need to see if https://github.com/tenstorrent/tt-metal/pull/15982 unblocks pipelines. If it does, then this PR is not needed.

2025-01-08 08:45 UTC, pavlejosipovic reviewed
Hi what is going on here can someone fill me in?
I really need these conv related changes in main, I don't think they are cause instabitlity for tt-train?

2025-01-08 08:46 UTC, pavlejosipovic commented on ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp
> -            mm_output_memory_config = conv_out_memory_config;
Pls dont' revert conv2d related stuff, 
we should decouple conv changes and matmul changes

2025-01-08 19:26 UTC, bbradelTT commented
> Hi what is going on here can someone fill me in? I really need these conv related changes in main, I don't think they are cause instabitlity for tt-train?

tt-train tests were not waiting for results of ops and not closing the device at the end of tests. After a change to matmuls (https://github.com/tenstorrent/tt-metal/pull/15864), that caused a problem because the device got to a bad state.

I don't know why a conv commit was in the revert list.

@tt-rkim I think this PR is no longer necessary. If that's the case, could you please close this PR to not confuse others?

2025-01-08 19:54 UTC, tt-rkim commented
Sorry everyone.

This was not meant to go in, and I kept it open just in case.

Closing.

2025-01-08 19:54 UTC, closed without merging