Clamp op update
tenstorrent/tt-metal pull request #16091
Opened 2024-12-17 10:52 UTC by umadevimcw

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

2025-04-29 09:51 UTC, Aswinmcw requested changes
Few changes

2025-04-29 09:51 UTC, Aswinmcw commented on tests/sweep_framework/sweeps/eltwise/unary/clamp/clamp_forge.py
> +        "input_a_dtype": [ttnn.float32, ttnn.int32],  # [ttnn.int32, ttnn.float32],
remove comment?

2025-04-29 09:51 UTC, Aswinmcw commented on tests/ttnn/unit_tests/operations/eltwise/test_composite.py
> +        # (torch.Size([1, 3, 320, 384])),
enable?

2025-04-29 09:51 UTC, Aswinmcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
> +        return ttnn::maximum(a_max, min.value(), std::nullopt, output_memory_config);
returning as int not required?

2025-04-30 04:55 UTC, mouliraj-mcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
> +        return ttnn::maximum(a_max, min.value(), std::nullopt, output_memory_config);
In this case, since the min and max values are floats, the output will also be of float type. All other scenarios are covered under [#21352](https://github.com/tenstorrent/tt-metal/issues/21352).

2025-04-30 05:03 UTC, Aswinmcw approved these changes
LGTM

2025-04-30 09:59 UTC, VirdhatchaniKN approved these changes

2025-05-02 23:55 UTC, dchenTT commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
>          return full_like(a, max.value());
Should this be a run time error?

2025-05-05 16:11 UTC, mouliraj-mcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
>          return full_like(a, max.value());
No, it won’t, because a typecast is used.

2025-05-05 20:23 UTC, dchenTT commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
>          return full_like(a, max.value());
Sorry, I did not get it. Why does it have anything to do with typecast? Behavior wise, if min > max, isn't it a illegal behavior?

2025-05-07 17:06 UTC, mouliraj-mcw approved these changes

2025-05-09 09:23 UTC, mouliraj-mcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
>          return full_like(a, max.value());
Hi @dchenTT,
Apologies for the earlier misunderstanding.

In our case, having min > max is not considered illegal behavior, as PyTorch explicitly handles this scenario. When min is greater than max, [torch.clamp](https://pytorch.org/docs/stable/generated/torch.clamp.html#torch.clamp) sets all elements in the input to the value of max.

2025-05-12 21:21 UTC, dchenTT approved these changes

2025-05-13 13:52 UTC, merged