Support subcoregrids in concat_heads
tenstorrent/tt-metal pull request #16223
Opened 2024-12-20 06:17 UTC by kpaigwar

### Problem description
For DRAM Prefetcher project, we have a requirement to move compute and storage to custom coregrid which can have arbitrary start or disjoint core ranges. This PR address the assumption of singular rectangular coregrid in `ttnn.nlp_concat_heads`

### What's changed
Based on input shard spec, a bool variable `on_subcoregrid` is defined. This helps to chose right program factory.

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/12436765431
- [x] New/Existing tests provide coverage for changes

2025-01-08 15:59 UTC, cglagovichTT commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_decode_subcoregrid.cpp
> +// #include "debug/dprint.h"  // required in all kernels using DPRINT
remove comment

2025-01-08 15:59 UTC, cglagovichTT commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_decode_subcoregrid.cpp
> +                // noc_async_read_barrier();
remove commented lines

2025-01-08 19:01 UTC, cglagovichTT approved these changes

2025-01-10 16:45 UTC, TT-BrianLiu requested changes

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_device_operation.cpp
> +    }
I really don't like how ops need to fork behaviour for subcoregrids based on a flag inside a program. Is it not possible to query some generic api to setup core grids?

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    const auto& input_shape = input_tensor.get_legacy_shape();
Don't use `get_legacy_shape`

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    const uint32_t head_tiles = head_dim / TILE_WIDTH;
Don't use hard-coded tile sizes.

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    const uint32_t sub_tile_line_bytes = 16 * element_size;
Don't use hardcoded constants. You want to get face width here

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    const auto in_num_tiles = in_shard_spec.shape[0] * in_shard_spec.shape[1] / TILE_HW;
Get tile sizes instead of TILE_HW

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    // tile respectively)
What does phase1 and phase2 of a tile refer to?

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +            i < 16 ? i * sub_tile_line_bytes : (i - 16) * sub_tile_line_bytes + 512 * element_size;
Please remove hard-coded constants and add a comment explaining things like this

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +        reader_runtime_args.insert(reader_runtime_args.end(), noc_y_coords.begin(), noc_y_coords.end());
Really bad code. I think you want:
```
        std::vector<uint32_t> reader_runtime_args = {
            in_tile_offset_by_batch,
            q_start_addr,
        };
        reader_runtime_args.reserve(reader_runtime_args.size() + 2 * in_num_cores);
        reader_runtime_args.insert(reader_runtime_args.end(), noc_x_coords.begin(), noc_x_coords.end());
        reader_runtime_args.insert(reader_runtime_args.end(), noc_y_coords.begin(), noc_y_coords.end());
```

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +    uint32_t q_base_addr = input_tensor.buffer()->address();
Unnecessary variable. Just assign to `q_start_addr`.

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +            uint32_t q_base_addr = input_tensors[0].buffer()->address();
Same comment

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +                    i < 16 ? i * sub_tile_line_bytes : (i - 16) * sub_tile_line_bytes + 512 * element_size;
Same comment

2025-01-10 16:45 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/nlp_concat_heads_decode.cpp
> +    const bool on_subcoregrids = on_subcoregrids_val;
`on_subcoregrids_val` is unnecessary. Just use `on_subcoregrids`.

2025-01-10 18:06 UTC, kpaigwar commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_device_operation.cpp
> +    }
Yeah, I feel like we need to modify/add some apis on device side which is aware about given subcoregrids.
For example, we have this api which we rely on to get compute grid size which assumes we always have singular rectangular grid.
input_tensor.device()->compute_with_storage_grid_size()
Techinally, if have an api which returns  custom corerangeset initialized during device creation. Life would be simpler. For e.g.
 input_tensor.device()->compute_with_storage_corerangeset()

2025-01-10 18:43 UTC, kpaigwar commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +        reader_runtime_args.insert(reader_runtime_args.end(), noc_y_coords.begin(), noc_y_coords.end());
Missed multiplication by 2. It should be reader_runtime_args.reserve(2 + 2*in_num_cores);
Why bad code? Reserving space for two args and (x,y) numcores before hand.
In your case, it involves resizing vector space twice

2025-01-10 20:46 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_device_operation.cpp
> +    }
yea APIs need to be revisited so subdevice is analogous to device. We need cleaner abstraction

2025-01-10 20:47 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_device_operation.cpp
> +    }
Won't block for this PR, but as an op writer it's worth driving further discussions to make programming subdevice ops cleaner

2025-01-10 20:49 UTC, kpaigwar commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_device_operation.cpp
> +    }
Yeah totally agree

2025-01-10 20:53 UTC, TT-BrianLiu requested changes

2025-01-10 20:53 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_decode_subcoregrid.cpp
> +            }
Same comment about hard-coded constants applies here. Please fix

2025-01-10 20:53 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +            i < face_h ? i * sub_tile_line_bytes : (i - face_h) * sub_tile_line_bytes + face_h * tile_w * element_size;
I gave @xuncaiTT a better way of calculating this: https://github.com/tenstorrent/tt-metal/pull/16362/files#diff-7011b98f678a5086871290a5fdc3683642c2cf02cd39f536dbb92a5ad006ccacR338-R341

IMO, this is way more readable

2025-01-10 20:53 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +                               : (i - face_h) * sub_tile_line_bytes + face_h * tile_w * element_size;
Same comment

2025-01-10 21:27 UTC, kpaigwar commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_decode_subcoregrid.cpp
> +            }
fixed

2025-01-10 21:27 UTC, kpaigwar commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/nlp_concat_heads_decode_program_factory.cpp
> +            i < face_h ? i * sub_tile_line_bytes : (i - face_h) * sub_tile_line_bytes + face_h * tile_w * element_size;
how about now?

2025-01-10 21:49 UTC, TT-BrianLiu approved these changes
Please change

2025-01-10 21:49 UTC, TT-BrianLiu commented on ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_decode/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_decode_subcoregrid.cpp
> +// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
2025

2025-01-10 21:55 UTC, merged