Spoojary/envbuiltpath
tenstorrent/tt-metal pull request #16240
Opened 2024-12-20 18:05 UTC by spoojaryTT

### Ticket
https://github.com/tenstorrent/tt-metal/issues/15871

### Problem description
We currently cannot build metal over network while having runtime builds in local disk.

### What's changed
Change the runtime build cache path to /tmp/${USER}-matal-cache.
Add a env variable if user wants to change it to some custom path.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

2024-12-20 18:19 UTC, pgkeller requested changes

2024-12-23 08:28 UTC, marty1885 reviewed
I believe this is related to #13062. Can the default path be put into the user's home directory? In terms of GGML's use pattern. A lot of users would not be deploying in a 24/7 setting so would lead to recompilation each time the system is rebooted. Caching somewhere under home would result in better overall UX.

Home may not necessarily exist so `/tmp` can be used as a fallback.

Happy holidays! Just reply when you are back :)

2024-12-23 08:28 UTC, marty1885 commented on tt_metal/jit_build/build.cpp
> +    if (user_name == emptyString) {
simply `user_name.empty()` should be enough

2025-01-06 16:05 UTC, tt-rkim commented on tt_metal/jit_build/build.cpp
> +    if (user_name == emptyString) {
I wonder if we should start moving logic to use this `TT_METAL_HOME` and therefore make `TT_METAL_HOME` finally an optional variable?

@tenstorrent/metalium-developers-infra @pgkeller

2025-01-08 14:12 UTC, tt-rkim commented on tt_metal/jit_build/build.cpp
> +    std::string user_name = parse_env<std::string>("USER", emptyString);
Take a look at this file @tenstorrent/metalium-developers-infra @ttmchiou 

This deprecates `_build`. It looks like current logic is:

- Check `TT_METAL_CACHE`. 
- If not set and no user, use `/tmp/tt-metal-cache`
- If we have a user, use `"/tmp/" + user_name + "-metal-cache/"`

I think `/tmp` is better convention, however this means another piece of the filesystem that the CI system won't automagically clean out for us. Remember only things in the repo directory get `git clean -xffd`'d at the end of a job run.

The current ask from @spoojaryTT is to put a `rm -rf /tmp/tt-metal-cache` and potentially a `rm -rf /home/ubuntu/.cache/tenstorrent` in the reset and cleanup scripts. thoughts?

Personally, I think it's whatever, given light of future CI runners being truly ephemeral, on the host side. However, this would be more places to look if a disk of a current runs out of space. I don't *think* the kernels are that large, though.

2025-01-08 14:37 UTC, spoojaryTT commented on tt_metal/jit_build/build.cpp
> +    std::string user_name = parse_env<std::string>("USER", emptyString);
HI Ray, This PR is slightly outdated and I will update this based on recent discussion. My request is to clean these two places in CI, 
1. $HOME/.cache/tenstorrent/metal-cache
2. /tmp/tenstorrent/metal-cache

2025-01-09 15:10 UTC, tt-rkim commented on tt_metal/jit_build/build.cpp
> +    if (!home_path.empty() && std::filesystem::exists(home_path)) {
Take a look at this file @tenstorrent/metalium-developers-infra @ttmchiou

This deprecates `built`. It looks like current logic is:

- Check TT_METAL_CACHE.
- If not set and no user, use `$HOME/.cache/tenstorrent/metal-cache`
- If we have a user, use "/tmp/tenstorrent/metal-cache/"

I think `/tmp` is better convention, however this means another piece of the filesystem that the CI system won't automagically clean out for us. Remember only things in the repo directory get `git clean -xffd`'d at the end of a job run.

The current ask from @spoojaryTT is to put a `rm -rf /tmp/tenstorrent/metal-cache` and potentially a rm -rf `/home/ubuntu/.cache/tenstorrent` in the reset and cleanup scripts. thoughts?

Personally, I think it's whatever, given light of future CI runners being truly ephemeral, on the host side. However, this would be more places to look if a disk of a current runs out of space. I don't think the kernels are that large, though.

2025-01-09 17:51 UTC, blozano-tt commented on tt_metal/jit_build/build.cpp
> +    if (!home_path.empty() && std::filesystem::exists(home_path)) {
I'm okay with adding the two `rm -rf`.

2025-01-09 17:52 UTC, blozano-tt commented on tt_metal/jit_build/build.cpp
> +    const std::string home_path = parse_env<std::string>("HOME", emptyString);
This code would not port to Windows, as there is no $HOME environment variable there.

2025-01-09 18:10 UTC, spoojaryTT commented on tt_metal/jit_build/build.cpp
> +        return "/tmp/tenstorrent/metal-cache/";
create_directories() would throw an error in that case.In that case, user has an option to select their own cache path, with TT_METAL_CACHE env variable. 
Do you think we should be dealing with that situation ourselves, instead of returning error to the user?

2025-01-09 18:15 UTC, spoojaryTT commented on tt_metal/jit_build/build.cpp
> +    const std::string home_path = parse_env<std::string>("HOME", emptyString);
Yes, Unfortunately there is no common env variable between Linux and Windows. We can use %USERPROFILE% for windows.

2025-01-09 19:01 UTC, blozano-tt commented on tt_metal/jit_build/build.cpp
> +        return "/tmp/tenstorrent/metal-cache/";
Ideally, I think we should have an understandable error message.

2025-01-09 19:05 UTC, blozano-tt commented on tt_metal/jit_build/build.cpp
> +    const std::string home_path = parse_env<std::string>("HOME", emptyString);
I have been the poor soul who had to port an entire library meant for linux to MSVC. Hence my comment.

But, lets just table this one for when we land a major customer that demands Windows support.

2025-01-09 19:44 UTC, ttmchiou commented on tt_metal/llrt/rtoptions.cpp
> +        TT_THROW("Env var {} is not set.", TT_METAL_CACHE_ENV_VAR);
would suggest mentioning in error message what ENV variable is expected

2025-01-09 19:50 UTC, ttmchiou commented on tt_metal/jit_build/build.cpp
> +    if (!home_path.empty() && std::filesystem::exists(home_path)) {
I'm not opposed to adding the two `rm -rf` commands
Since we are going towards ephemeral runners, its just front-loading the work here and eases the transition.

do we have anything in the codebase relyong on the built folder atm?
does it affect our caching for building tt-metal?

2025-01-09 20:13 UTC, spoojaryTT commented on tt_metal/llrt/rtoptions.cpp
> +        TT_THROW("Env var {} is not set.", TT_METAL_CACHE_ENV_VAR);
The error message contains the ENV variable - TT_METAL_CACHE_ENV_VAR is set to TT_METAL_CACHE.

2025-01-09 20:29 UTC, tt-rkim commented on tt_metal/llrt/rtoptions.cpp
> +        TT_THROW("Env var {} is not set.", TT_METAL_CACHE_ENV_VAR);
I think we could put some description here explaining to the user what this is for and why.

2025-01-09 20:30 UTC, tt-rkim commented on tt_metal/jit_build/build.cpp
> +    if (!home_path.empty() && std::filesystem::exists(home_path)) {
> do we have anything in the codebase relyong on the built folder atm?

I don't think so, although @spoojaryTT should be testing that out?

> does it affect our caching for building tt-metal?

It should not.

2025-01-15 16:34 UTC, tt-rkim commented
New reset script blasted out

Should be ready to go

2025-01-15 18:44 UTC, abhullar-tt approved these changes

2025-01-15 19:07 UTC, tt-rkim approved these changes

2025-03-10 17:21 UTC, arikTT commented on tt_metal/jit_build/build.cpp
> +        return "/tmp/metal-cache/";
@pgkeller Sanjay changed the path to "/tmp/tenstorrent/metal-cache/" is that good enough or you still want the prefix? or maybe prefix without "tenstorrent"?

2025-03-10 20:01 UTC, blozano-tt commented on build_metal.sh
> +    rm -rf ~/.cache/tenstorrent/metal-cache /tmp/tenstorrent/metal-cache $TT_METAL_CACHE
What happens if someone accidentally sets `TT_METAL_CACHE` to `/home`?

Isn't this unsafe?

2025-03-10 20:05 UTC, arikTT commented on build_metal.sh
> +    rm -rf ~/.cache/tenstorrent/metal-cache /tmp/tenstorrent/metal-cache $TT_METAL_CACHE
Without it the clean command won't clean the cache if the env var is defined. With my change or without we put the responsibility on the user. I guess without this change is safer

2025-03-10 20:19 UTC, arikTT commented on build_metal.sh
> +    rm -rf ~/.cache/tenstorrent/metal-cache /tmp/tenstorrent/metal-cache $TT_METAL_CACHE
Good idea, just pushed an update

2025-03-10 20:38 UTC, pgkeller commented on tt_metal/jit_build/build.cpp
> +        return "/tmp/metal-cache/";
let's use tt-metal

2025-03-10 20:45 UTC, afuller-TT commented on tt_metal/jit_build/build.cpp
> +        return "/tmp/metal-cache/";
I heard there are issues with the term `metal` and we're supposed to move away from it, TT-Metalium being the replacement.  Is that not the case?

2025-03-10 20:47 UTC, blozano-tt approved these changes

2025-03-10 20:52 UTC, pgkeller approved these changes

2025-03-10 21:31 UTC, tt-rkim commented on build_metal.sh
> +    if [[ ! -z $TT_METAL_CACHE ]]; then
What's the plan to provide state not via environment variables?

2025-03-10 21:31 UTC, tt-rkim commented on build_metal.sh
> +    if [[ ! -z $TT_METAL_CACHE ]]; then
By the looks of it - because we had in a previous PR - it's not that urgent.

2025-03-10 22:06 UTC, arikTT commented on build_metal.sh
> +    if [[ ! -z $TT_METAL_CACHE ]]; then
I don't know, the ticket specifically required env var

2025-03-10 22:22 UTC, tt-rkim commented on build_metal.sh
> +    if [[ ! -z $TT_METAL_CACHE ]]; then
Is there no general plan across the metal runtime org?

2025-03-11 01:01 UTC, merged

2025-03-11 10:58 UTC, tt-rkim commented on build_metal.sh
> +    if [[ ! -z $TT_METAL_CACHE ]]; then
Discussed offline, plan is
- default no env vars to run metal
- keep as much runtime input state in RTOptions