Fix padding issues
tenstorrent/tt-metal pull request #16347
Opened 2024-12-30 05:58 UTC by Aswinmcw

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

2025-01-03 15:17 UTC, SeanNijjar commented on tests/ttnn/unit_tests/operations/ccl/test_all_gather.py
> +        (8, 1, [1, 1, 1, 8], 3, ttnn.TILE_LAYOUT),
```suggestion
        (8, 1, [1, 1, 1, 8], 3, ttnn.TILE_LAYOUT),
        (8, 1, [1, 1, 1, 1], 3, ttnn.TILE_LAYOUT),
```

2025-01-03 15:22 UTC, Aswinmcw commented on tests/ttnn/unit_tests/operations/ccl/test_all_gather.py
> +        (8, 1, [1, 1, 1, 8], 3, ttnn.TILE_LAYOUT),
@SeanNijjar the case with shape [1,1,1,1], will get skipped, is that what we need? As it is not per chip shape this will try to split the shapes to all chips

2025-01-03 15:26 UTC, SeanNijjar requested changes
Overall looking pretty good but there is one bug fix that needs attention and some minor cleanup I'm recommending.

2025-01-03 15:26 UTC, SeanNijjar commented on ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp
> +            if (input_tensor.get_logical_shape()[-2] < tt::constants::TILE_HEIGHT ||
This can be cleaned up a little but also the condition should be expanded to also include shapes that are > TILE size but still not tile aligned (so they will still have padding)
```suggestion
            bool needs_padding = input_tensor.get_logical_shape()[-2] % tt::constants::TILE_HEIGHT != 0 || input_tensor.get_logical_shape()[-1] % tt::constants::TILE_WIDTH != 0;
```

2025-01-03 15:26 UTC, SeanNijjar commented on ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp
> +            uint32_t total_elements = input_tensor.get_logical_shape()[dim];
The naming of this is confusing. I suggest renaming it to something like unpadded_concat_dim_size_in_elements (or something more concise if you can think of one :) )

2025-01-03 15:26 UTC, SeanNijjar commented on ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp
> +            if (needs_padding) {
Can you please move this block to a helper function?

2025-01-03 15:26 UTC, SeanNijjar commented on tests/ttnn/unit_tests/operations/ccl/test_all_gather.py
> +        (8, 1, [1, 1, 1, 8], 3, ttnn.TILE_LAYOUT),
Also after taking into account the recommended bug fix below - can you also please add some test cases that are  > TILE_HEIGHT and TILE_WIDTH but not a multiple of tile size?

2025-01-06 14:40 UTC, SeanNijjar approved these changes
Thanks Aswin, this will help a lot

2025-01-06 14:44 UTC, SeanNijjar commented
Before merging - please run t3k model perf and demos. The model team was aware of the previously incorrect all-gather concatenation behaviour of padded tensors and manually sliced out the real data from the all-gather output tensor. Those code-paths will likely need to change.

@johanna-rock-tt Can you please point us to where we'll need to update to no longer manually slice out on the model side?

2025-01-06 14:45 UTC, SeanNijjar commented
> Before merging - please run t3k model perf and demos. The model team was aware of the previously incorrect all-gather concatenation behaviour of padded tensors and manually sliced out the real data from the all-gather output tensor. Those code-paths will likely need to change.
> 
> @johanna-rock-tt Can you please point us to where we'll need to update to no longer manually slice out on the model side?

Also ping @cglagovich, @kpaigwar either of you are familiar with this and and point out where we need to update.

2025-01-07 09:15 UTC, johanna-rock-tt commented
@SeanNijjar We slice out the 8 users [here](https://github.com/tenstorrent/tt-metal/blob/932ee217e76b153985f6c5928ce0ac79a30bffdc/models/demos/llama3/tt/llama_attention.py#L269) (would require sub tile all reduce) and put them back together [here](https://github.com/tenstorrent/tt-metal/blob/932ee217e76b153985f6c5928ce0ac79a30bffdc/models/demos/llama3/tt/llama_attention.py#L410) <-- this should not be necessary if we have padding support in all gather.

2025-01-08 09:39 UTC, merged

2025-01-08 14:59 UTC, bbradelTT commented
@Aswinmcw did this break all post commits?

https://github.com/tenstorrent/tt-metal/actions/runs/12667918875/job/35305343660