TT-Fabric Bringup Initial Check-in
tenstorrent/tt-metal pull request #16343
Opened 2024-12-29 05:55 UTC by aliuTT

### Ticket
https://github.com/tenstorrent/tt-metal/issues/13844
https://github.com/tenstorrent/tt-metal/issues/13845

### Problem description
Combined work for initial bringup of TT-FABRIC, by @aagarwalTT @ubcheema @aliuTT

### What's changed
In first check-in of TT-FABRIC, we have only added new components and tests for it. There should be no functional changes to existing runtime/FD/ops etc.

Still need to rebase and run CI, but from top of my head there are some known issues:
- @ubcheema currently, I've added the eth chan noc encoding map to the `generated_bank_to_noc_coord_mapping.h`, which is removed on latest main. Need to figure out where to load this. Commit `d9f211596` needs special attention.
- we should add the passing tests to the respective CIs
- some commented out code, can be removed

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

2024-12-30 18:31 UTC, ubcheema commented
@Allan, the eth channel to noc x/y mapping is fixed. We can add the mapping look up table to tt_faric header, instead of generating it on the fly.
What do you think?

2024-12-30 18:34 UTC, ubcheema approved these changes

2024-12-30 18:34 UTC, ubcheema commented on tt_fabric/mesh_graph_descriptors/t3k_mesh_graph_descriptor.yaml
> +  host_mapping: [[sjc-lab-t3005]]}
Is this descriptor tied to this specific host?

2024-12-30 18:34 UTC, ubcheema commented on tt_fabric/mesh_graph_descriptors/tg_mesh_graph_descriptor.yaml
> +  host_mapping: [[aus-glx-11]]},
Is this tg descriptor tied to aus-glx-11?
I suppose control plane is not currently using this field, so it does not matter...

2025-01-03 00:24 UTC, tt-rkim submitted a review, later dismissed
First pass at CMake, but I'll definitely have stuff to say about the others

2025-01-03 00:24 UTC, tt-rkim commented on tt_fabric/CMakeLists.txt
> +    PUBLIC
Why does this need to be public?

2025-01-03 00:24 UTC, tt-rkim commented on tt_fabric/CMakeLists.txt
> +    PUBLIC
Why does this need to be public? Too much pollution

2025-01-03 00:24 UTC, tt-rkim commented on tt_fabric/CMakeLists.txt
> +    PUBLIC
Do you want people to be able to use metal via fabric? Seems like reaching around to me

2025-01-03 00:24 UTC, tt-rkim commented on tt_fabric/CMakeLists.txt
> +            "${PROJECT_BINARY_DIR}/lib"
Please use `$ORIGIN` like we do for `_ttnn`

2025-01-07 17:45 UTC, aliuTT commented on tt_fabric/mesh_graph_descriptors/tg_mesh_graph_descriptor.yaml
> +  host_mapping: [[aus-glx-11]]},
Yea, I can remove the names of the hosts.

2025-01-07 17:45 UTC, aliuTT commented
> @allan, the eth channel to noc x/y mapping is fixed. We can add the mapping look up table to tt_faric header, instead of generating it on the fly. What do you think?

We can do that for now.

2025-01-08 22:41 UTC, aliuTT commented on tt_fabric/CMakeLists.txt
> +    PUBLIC
moved to private

2025-01-09 00:25 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +add_library(Metalium::Fabric ALIAS tt_fabric)
I started this nomenclature based on the assumption that Metal == Metalium.

Since recently finding a doc that spells out the (current) names for everything, I now come to understand that "tt-metal" repo is actually "TT-Metalium And Friends".

To reflect that, I think this would be more in line with intended names:

```suggestion
add_library(TT::Fabric ALIAS tt_fabric)
```

2025-01-09 00:28 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +target_sources(
Thank you for modern and clean CMake 🙏 

FYI: the `${CMAKE_CURRENT_SOURCE_DIR}` is redundant and actually preferred to be omitted so that in the rare case that we we build a generated file, `${CMAKE_CURRENT_BINARY_DIR}` actually stands out as an exception rather than blends in to the noise.

2025-01-09 00:30 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}
Please no.  I'm in the process of cleaning this up.  Nobody consuming TT-Fabric should know anything about anything outside the scope of TT-Fabric and we shouldn't enable it.  If they need TT-Metalium, then should ask TT-Metalium; if they need TT-NN, they should ask for TT-NN.

Do you remember what prompted this?  Or just a copy/paste of the status-quo elsewhere?

2025-01-09 00:33 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}
Is this the location of the TT-Fabric API for consumers?  There's no `api/` directory?  The target should only expose what's actually public and keep the private bits out of reach from consumers.

This is for the benefit of both the consumer (easy to see what's actually the API) and also for the maintainers (can YOLO internal files, but be more careful/meticulous with the exposed API).  Also tooling is available to more thoroughly test published headers.

2025-01-09 00:34 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${UMD_HOME}
Shouldn't need this.  If you need UMD, then add a dependency on UMD.  I see line 24 has `umd::device`.  That should provide you what UMD deems its public API.  No need to manually set include dirs.

2025-01-09 00:36 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}/tt_metal
This one's more questionable whether it's in a suitable shape.  Ideally `Metalium::Metal` on line 23 is providing you everything you need.  I'm currently going through to ensure that's the case.  Does TT-Fabric work if you drop the line?  Or are bits missing from Metalium::Metal?

2025-01-09 00:38 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +            "${PROJECT_BINARY_DIR}/lib;${PROJECT_BINARY_DIR}/obj"
Are we manually placing files here (haven't looked that far yet)?  Or why do we need to tell CMake about files if we're not doing it behind CMake's back?

2025-01-09 00:40 UTC, afuller-TT commented on tt_metal/hw/inc/wormhole/eth_l1_address_map.h
> +#include "tt_fabric/hw/inc/routing_table.h"
Whoa!  We're creating a circular dependency from TT-Metalium reaching into TT-Fabric while TT-Fabric uses TT-Metalium?

Is this necessary/intentional?  If so, then it's time to think about extracting whatever this bit of logic is into a common dependency.  We really don't want circular deps.

2025-01-09 00:46 UTC, afuller-TT requested changes
Marking 'changes wanted' primarily for the circular dep, but also for tighter encapsulation of TT-Fabric.

Have only looked at the build structure of the library proper.

2025-01-09 16:35 UTC, aliuTT commented on tt_fabric/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}
Copy paste :) I've redone the CMakeList after rebasing to get the cleanup you've put in for existing ones. Is your cleanup PR likely to hit main this week? If not, can you paste the changes here so I can put into this PR?

2025-01-09 16:45 UTC, aliuTT commented on tt_fabric/CMakeLists.txt
> +add_library(Metalium::Fabric ALIAS tt_fabric)
I can make this change.

2025-01-09 17:20 UTC, aliuTT commented on tt_fabric/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}
This is just an initial bringup of Fabric, all the major components of Fabric are getting checked in, but we haven't switched existing SW to use it yet (that is coming in the next month or so). We'll have a better idea of what APIs makes sense to expose as Fabric settles into the codebase more. I can remove the PUBLIC section of the includes, and add back a public API folder in the future.

2025-01-09 21:34 UTC, aliuTT commented
@afuller-TT (I think) I've addressed all your feedback on CMakeLists, please take a look. Appreciate the feedback :)

2025-01-09 21:49 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}
The cleanup is a 800+ file PR: #16578 

We'll coordinate the final cleanup either in whichever PR lands later or in a fresh pass after both land.

2025-01-09 21:52 UTC, afuller-TT commented on tt_fabric/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}
It's 1000x easier to turn a private header public than to turn a public header private.  I suggest starting with nothing public, and then cherry-pick into public exposure on a case-by-case basis.  It also provides a natural gate to tidy up the header when it's promoted, especially if only half ought to be public.

2025-01-10 02:12 UTC, afuller-TT reviewed
Removing my "Request changes" status.  LMK if you need help addressing the clang-tidy error.

2025-01-10 02:13 UTC, afuller-TT approved these changes
Scratch that; the only way to remove it is to turn it into an actual Approve 🙃 
Still pending some updates; but I don't want to be blocking it once those are in.

2025-01-10 20:00 UTC, aliuTT commented on tt_fabric/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}/tt_metal
Dropped both UMD_HOME and tt_metal, in latest changes

2025-01-10 20:00 UTC, aliuTT commented on tt_metal/hw/inc/wormhole/eth_l1_address_map.h
> +#include "tt_fabric/hw/inc/routing_table.h"
I fixed this in latest changes.

2025-01-10 21:51 UTC, tt-rkim commented
@afuller-TT You can dismiss your review, by the way, since you're an admin :) 
<img width="862" alt="Screenshot 2025-01-10 at 4 51 03 PM" src="https://github.com/user-attachments/assets/1dfb8d53-f567-4e33-b251-a0a28299efd0" />

2025-01-10 21:53 UTC, tt-rkim commented on .github/workflows/t3000-unit-tests-impl.yaml
> +          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttfabric_tests, timeout: 30, owner_id: XXXXX}, # Add owner
Please add someone here - no `XXXXX`

2025-01-10 21:53 UTC, tt-rkim commented on CODEOWNERS
> +tt_fabric/ @ubcheema @aliuTT
I would recommend another person, but at this point it won't be a big deal.

Until it becomes one.

2025-01-10 21:53 UTC, tt-rkim commented on tests/tt_metal/tt_fabric/common/n300_cluster_desc.yaml
Are these descriptors new for `tt_fabric`? Where will these be used? And in which cluster object?

2025-01-10 21:55 UTC, aliuTT commented on CODEOWNERS
> +tt_fabric/ @ubcheema @aliuTT
I will add Abhinav and Ellie who will contribute heavily to these files.

2025-01-10 21:56 UTC, aliuTT commented on .github/workflows/t3000-unit-tests-impl.yaml
> +          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttfabric_tests, timeout: 30, owner_id: XXXXX}, # Add owner
Ok, will add myself.

2025-01-10 21:56 UTC, aliuTT commented on tests/tt_metal/tt_fabric/common/n300_cluster_desc.yaml
They are needed for offline testing for the ControlPlane. Will not be used in silicon jobs.

2025-01-10 22:00 UTC, tt-rkim commented on CODEOWNERS
> +tt_fabric/ @ubcheema @aliuTT
Who is Ellie?

2025-01-10 22:00 UTC, tt-rkim approved these changes

2025-01-13 17:08 UTC, aliuTT commented on CODEOWNERS
> +tt_fabric/ @ubcheema @aliuTT
new hire working on Fabric features

2025-01-14 00:25 UTC, omilyutin-tt requested changes

2025-01-14 00:25 UTC, omilyutin-tt commented on tt_fabric/routing_table_generator.cpp
> +        for (chip_id_t src_chip_id = 0; src_chip_id < this->intra_mesh_table_[mesh_id].size(); src_chip_id++) {
An alias like `auto& chip_routing = intra_mesh_table_[mesh_id];` (naming up to you) would makes sense here. Also in other places, where appropriate.

2025-01-14 00:25 UTC, omilyutin-tt commented on tt_fabric/routing_table_generator.cpp
> +        }
This is duplicated? Would a lambda that accepts either `inter_mesh_table_` or `intra_mesh_table_` work here?

2025-01-14 00:25 UTC, omilyutin-tt commented on tt_fabric/mesh_graph.cpp
> +    }
Similar comment about code duplication, I think you can use a generic lambda here to handle both cases cleanly.

2025-01-14 00:25 UTC, omilyutin-tt commented on tt_fabric/routing_table_generator.hpp
> +    std::vector<std::vector<std::vector<RoutingDirection>>>;  // [mesh_id][chip_id][target_chip_or_mesh_id]
The printing functions can also go here.

Ideally we would also use something similar for `directions_` from within the wrapper class, but I think it is ok to construct the data member and set it externally once, but optimize for the nice type safe access API.

2025-01-14 18:51 UTC, omilyutin-tt approved these changes
Approve as per the offline discussion that the comments will be resolved in the follow up PR.

2025-01-14 20:48 UTC, merged