#16367: Added support to enable dram and l1 memory collection without saving to disk
tenstorrent/tt-metal pull request #16368
Opened 2024-12-30 22:47 UTC by tapspatel

### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/16367)

### Problem description
In upstream compiler environments, we need the ability to query a memory view of the device state for DRAM/L1. The current method of saving to csv brings up 2 issues

1. The csv format requires specific parsing algorithms and recent changes to memory allocator have caused the upstream compiler parsing to break. A more robust solution that can dump the memory values without having to implement clever parsing algorithms would be beneficial.

Current memory allocator csv file:
```
,DRAM
,Total allocatable (B):,12884901504
,Total allocated (B):,0
,Total free (B):,12884901504
FreeListOpt allocator info:
segregated free blocks by size:
  Size class 0: (1024 - 2048) blocks: 
  Size class 1: (2048 - 4096) blocks: 
  Size class 2: (4096 - 8192) blocks: 
  Size class 3: (8192 - 16384) blocks: 
  Size class 4: (16384 - 32768) blocks: 
  Size class 5: (32768 - 65536) blocks: 
  Size class 6: (65536 - 131072) blocks: 
  Size class 7: (131072 - 262144) blocks: 
  Size class 8: (262144 - 524288) blocks: 
  Size class 9: (524288 - 1048576) blocks: 
  Size class 10: (1048576 - 2097152) blocks: 
  Size class 11: (2097152 - 4194304) blocks: 
  Size class 12: (4194304 - 8388608) blocks: 
  Size class 13: (8388608 - 16777216) blocks: 
  Size class 14: (16777216 - 33554432) blocks: 
  Size class 15: (33554432 - 67108864) blocks: 
  Size class 16: (67108864 - 134217728) blocks: 
  Size class 17: (134217728 - inf) blocks: 0 
Free slots in block table: 
Block table:
       Block      Address         Size       PrevID       NextID    Allocated 
           0            0   1073741792         none         none           no
,L1
,Total allocatable (B):,87504896
,Total allocated (B):,0
,Total free (B):,87504896
FreeListOpt allocator info:
segregated free blocks by size:
  Size class 0: (1024 - 2048) blocks: 
  Size class 1: (2048 - 4096) blocks: 
  Size class 2: (4096 - 8192) blocks: 
  Size class 3: (8192 - 16384) blocks: 
  Size class 4: (16384 - 32768) blocks: 
  Size class 5: (32768 - 65536) blocks: 
```

2. The second hurdle is having to save to disk + requiring some sort of file opening mechanism to read the stored file. The compiler could issue hundreds of small subgraphs and having to save to disk is extremely time consuming and not efficient. Having the ability to query the device during the runtime is much more beneficial. 

### What's changed
## 2 new tt_metal APIs
`MemoryView GetDramMemoryView(const Device* device);`

`MemoryView GetL1MemoryView(const Device* device);`

## 2 new ttnn pybinded APIs
`ttnn.get_dram_memory_view(device)`
`ttnn.get_l1_memory_view(device)`

### Sample usage from ttnn python POV
```
>>> dram = ttnn.get_dram_memory_view(device)
>>> print(dram)
<ttnn._ttnn.device.MemoryView object at 0x7fe7ee4ecb70>
>>> dram.num_banks
12
>>> dram.total_allocatable_per_bank_size_bytes
1073741792
>>> dram.total_allocated_per_bank_size_bytes
4096
>>> dram.total_free_per_bank_size_bytes
1073737696
>>> dram.total_allocatable_size_bytes
12884901504
>>> dram.total_allocated_size_bytes
49152
>>> dram.total_free_size_bytes
12884852352
>>> dram.largest_contiguous_free_block_per_bank_size_bytes
1073737696
>>> dram.blockTable
[{'blockID': '0', 'address': '0', 'size': '2048', 'prevID': '-1', 'nextID': '1', 'allocated': 'yes'}, {'blockID': '1', 'address': '2048', 'size': '2048', 'prevID': '0', 'nextID': '2', 'allocated': 'yes'}, {'blockID': '2', 'address': '4096', 'size': '1073737696', 'prevID': '1', 'nextID': '-1', 'allocated': 'no'}]
>>> l1 = ttnn.get_l1_memory_view(device)
>>> l1.num_banks
64
```

## MemoryView information being collected
```
struct MemoryView {
    std::uint64_t num_banks;
    size_t total_allocatable_per_bank_size_bytes;
    size_t total_allocated_per_bank_size_bytes;
    size_t total_free_per_bank_size_bytes;
    size_t total_allocatable_size_bytes;  // total_allocatable_per_bank_size_bytes * num_banks
    size_t total_allocated_size_bytes;    // total_allocated_per_bank_size_bytes * num_banks
    size_t total_free_size_bytes;         // total_free_per_bank_size_bytes * num_banks
    size_t largest_contiguous_free_block_per_bank_size_bytes;
    std::vector<std::unordered_map<std::string, std::string>> blockTable;
};
```

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

2024-12-31 19:10 UTC, tapspatel commented
able to repro error in debug mode, investigating

2024-12-31 21:36 UTC, ayerofieiev-tt commented on ttnn/cpp/pybind11/device.cpp
> +            "total_allocatable_per_bank_size_bytes",
what exactly does this mean? amount of memory per bank? or amount of free memory per bank?
why "total" but at the same time "per bank"?

2025-01-02 21:32 UTC, abhullar-tt requested changes

2025-01-02 21:32 UTC, abhullar-tt commented on tt_metal/detail/reports/memory_reporter.cpp
> +        .total_allocatable_per_bank_size_bytes = stats.total_allocatable_size_bytes,
maybe rename this to `bank_size_bytes`

2025-01-02 21:32 UTC, abhullar-tt commented on tt_metal/detail/reports/memory_reporter.cpp
> +        .total_allocated_per_bank_size_bytes = stats.total_allocated_bytes,
```suggestion
        .total_bytes_allocated_per_bank = stats.total_allocated_bytes,
```

2025-01-02 21:32 UTC, abhullar-tt commented on tt_metal/detail/reports/memory_reporter.cpp
> +        .total_free_per_bank_size_bytes = stats.total_free_bytes,
```suggestion
        .total_bytes_free_per_bank = stats.total_free_bytes,
```

2025-01-02 21:32 UTC, abhullar-tt commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +std::vector<std::unordered_map<std::string, std::string>> FreeList::get_block_table() const {
return type is a bit long, could be helpful for it to be `std::vector<BlockDescriptor>`

2025-01-07 20:26 UTC, tapspatel commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +std::vector<std::unordered_map<std::string, std::string>> FreeList::get_block_table() const {
I kept it with default stl values so I wouldn't need extra pybinds for another class, and it makes upstream consumption easier. I'm indifferent to adding another class as I do think the return type is a bit long as well. Let me know your thoughts.

2025-01-07 21:14 UTC, tapspatel commented
@abhullar-tt @ayerofieiev-tt  I updated the variable names

```
std::uint64_t num_banks;
    size_t bytes_allocatable_per_bank;
    size_t bytes_allocated_per_bank;
    size_t bytes_free_per_bank;
    size_t total_bytes_allocatable;  // bytes_allocatable_per_bank * num_banks
    size_t total_bytes_allocated;    // bytes_allocated_per_bank * num_banks
    size_t total_bytes_free;         // bytes_free_per_bank * num_banks
    size_t largest_contiguous_bytes_free_per_bank;
```

2025-01-07 21:48 UTC, abhullar-tt approved these changes
overall looks okay to me

2025-01-08 14:40 UTC, tapspatel commented
post commit pipeline pass: https://github.com/tenstorrent/tt-metal/actions/runs/12660580219

2025-01-08 14:49 UTC, tt-aho commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::vector<std::unordered_map<std::string, std::string>> blockTable;
Nit: Why does this not use snake case like the other attributes?

2025-01-08 14:49 UTC, tt-aho commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +        std::unordered_map<std::string, std::string> blockEntry;
Nit: Similar question as above

2025-01-08 14:49 UTC, tt-aho commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +        blockEntry["address"] = std::to_string(curr_block->address + this->offset_bytes_);  /// bytes
Nit:
```suggestion
        blockEntry["address"] = std::to_string(curr_block->address + this->offset_bytes_);  // bytes
```

2025-01-08 14:49 UTC, tt-aho commented on tech_reports/memory/allocator.md
> +GetL1MemoryView(const Device *device);
Do we not need apis for the other memory types, ex Trace and l1 small?

2025-01-08 14:49 UTC, tt-aho commented on tt_metal/detail/reports/memory_reporter.hpp
> + * blockTable: list of all blocks in dram (blockID, address, size, prevID, nextID, allocated)
These should say L1 instead of dram

2025-01-08 15:02 UTC, tapspatel commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::vector<std::unordered_map<std::string, std::string>> blockTable;
I copied the new allocator changes naming convention `tt_metal/impl/allocator/algorithms/free_list_opt.hpp`

```
private:
    // SoA free list components
    std::vector<DeviceAddr> block_address_;
    std::vector<DeviceAddr> block_size_;
    std::vector<ssize_t> block_prev_block_;
    std::vector<ssize_t> block_next_block_;
    std::vector<uint8_t> block_is_allocated_;       // not using bool to avoid compacting
    std::vector<uint8_t> meta_block_is_allocated_;  // not using bool to avoid compacting
```

2025-01-08 16:17 UTC, tapspatel commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::vector<std::unordered_map<std::string, std::string>> blockTable;
fixed

2025-01-08 16:18 UTC, tapspatel commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +        std::unordered_map<std::string, std::string> blockEntry;
fixed

2025-01-08 16:18 UTC, tapspatel commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +        blockEntry["address"] = std::to_string(curr_block->address + this->offset_bytes_);  /// bytes
fixed

2025-01-08 16:18 UTC, tapspatel commented on tech_reports/memory/allocator.md
> +GetL1MemoryView(const Device *device);
added

2025-01-08 16:18 UTC, tapspatel commented on tt_metal/detail/reports/memory_reporter.hpp
> + * blockTable: list of all blocks in dram (blockID, address, size, prevID, nextID, allocated)
fixed

2025-01-08 16:24 UTC, tt-aho approved these changes
Looks okay to me, but I am not sure why we need dedicated user APIs for each buffer type, instead of just taking the buffer type as a parameter.

2025-01-09 05:26 UTC, tapspatel commented
post commit pass: https://github.com/tenstorrent/tt-metal/actions/runs/12683308047
nightly model and ttnn pass: https://github.com/tenstorrent/tt-metal/actions/runs/12683309017

2025-01-09 17:04 UTC, TT-BrianLiu requested changes

2025-01-09 17:54 UTC, tapspatel commented on tt_metal/impl/allocator/algorithms/free_list_opt.cpp
> +        std::unordered_map<std::string, std::string> blockEntry;
cleaned

2025-01-09 17:54 UTC, tapspatel commented on tt_metal/detail/reports/memory_reporter.cpp
> +}
agree with all your suggestions. updated branch

2025-01-09 17:58 UTC, TT-BrianLiu approved these changes

2025-01-09 18:02 UTC, dmakoviichuk-tt commented on tt_metal/impl/allocator/algorithms/free_list.cpp
> +std::vector<std::unordered_map<std::string, std::string>> FreeList::get_block_table() const {
could make using BlockTable = std::vector<std::unordered_map<std::string, std::string>>

2025-01-09 18:04 UTC, dmakoviichuk-tt commented on tt_metal/include/tt_metal/device.hpp
> +    virtual std::vector<std::unordered_map<std::string, std::string>> get_block_table(
@ayerofieiev-tt  are you good with new api in the IDevice?

2025-01-09 18:05 UTC, dmakoviichuk-tt commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::uint64_t num_banks;
please initialize variables with zeros.

2025-01-10 23:59 UTC, dmakoviichuk-tt approved these changes

2025-01-13 03:24 UTC, ayerofieiev-tt commented on tt_metal/include/tt_metal/device.hpp
> +    virtual std::vector<std::unordered_map<std::string, std::string>> get_block_table(
As class user I have no idea what this method is. 
nor its name nor its return type tell me anything. 

@tapspatel can you please sort this out?
Return type deserves a `using =` and name can likely be improved. 

I assume this method will have to later be moved out from device into something like allocator.

@cfjchu for the new api.

2025-01-13 03:24 UTC, ayerofieiev-tt commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::uint64_t num_banks;
@tapspatel please don’t miss this.

2025-01-13 19:00 UTC, tapspatel commented on tt_metal/detail/reports/memory_reporter.hpp
> +    std::uint64_t num_banks;
updated

2025-01-13 19:01 UTC, tapspatel commented on tt_metal/include/tt_metal/device.hpp
> +    virtual std::vector<std::unordered_map<std::string, std::string>> get_block_table(
I changed this to be more descriptive

```
/*
MemoryBlockTable is a list of memory blocks in the following format:
[{"blockID": "0", "address": "0", "size": "0", "prevID": "0", "nextID": "0", "allocated": true}]
address: bytes
size: bytes
*/
using MemoryBlockTable = std::vector<std::unordered_map<std::string, std::string>>;
```

name of function is
```
virtual MemoryBlockTable get_memory_block_table(const BufferType& buffer_type) const = 0;
```

which is similar to
```
virtual void dump_memory_blocks(const BufferType &buffer_type, std::ofstream &out) const = 0;
```

2025-01-13 19:12 UTC, ayerofieiev-tt approved these changes

2025-01-13 19:32 UTC, merged