#16350: Update reciprocal docs
tenstorrent/tt-metal pull request #16371
Opened 2024-12-31 09:47 UTC by mouliraj-mcw

### Ticket
Link to Github Issue #16350 

### Problem description

- Update the recip documentation to indicate that the bfloat8_b datatype is supported only for non-zero inputs.
- Revise the documentation for recip dependent backward operations to reflect the supported datatype

### What's changed

- Updated the respective docs

### Checklist
- [ ] All Post commit CI

2024-12-31 12:06 UTC, umadevimcw approved these changes

2024-12-31 12:06 UTC, umadevimcw commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +    detail::bind_unary_operation_overload_complex_return_complex(module, ttnn::reciprocal, R"doc(BFLOAT16, BFLOAT8_B)doc", "bfloat8_b is supported only for non-zero inputs. Inputs containing zero may
instead of you can't can add like this or similar to this

 `making it impossible to process them separately`

2024-12-31 13:10 UTC, KalaivaniMCW approved these changes

2025-01-02 14:57 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/binary_backward_pybind.hpp
> +        R"doc(BFLOAT16)doc");
@mouliraj-mcw , after further thought on this, I realized that we could continue to support BFLOAT8_B within the div operation if we do a typecast to BFLOAT16.    This would allow folks to continue to use bfloat8_b during training.

2025-01-02 15:38 UTC, mouliraj-mcw commented on ttnn/cpp/ttnn/operations/eltwise/binary_backward/binary_backward_pybind.hpp
> +        R"doc(BFLOAT16)doc");
Yes, it is possible

2025-01-03 22:09 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +    detail::bind_unary_operation_overload_complex_return_complex(module, ttnn::reciprocal, R"doc(BFLOAT16, BFLOAT8_B)doc", "bfloat8_b is supported only for non-zero inputs. Inputs containing zero may
@mouliraj-mcw ,  is there any way we can squeeze in more details on the documentation?  For example could we say all the points below instead?

The bfloat8_b format utilizes a block-floating point (BFP) representation, where 16 consecutive numbers share a single exponent, determined by the largest value in the group. This shared exponent introduces specific behaviors and limitations during the reciprocal operation:

When the group contains numbers with large magnitude differences, smaller values may be flushed to zero, resulting in inaccurate reciprocal results or numerical instability.

Inputs with extreme values (e.g., zeros or infinities) can dominate the shared exponent, causing other numbers in the group to lose precision or be rounded off to zero.
For inputs that include zero, the reciprocal result is undefined in this format.

Avoid using the bfloat8_b format for reciprocal operations on datasets with high variance in magnitude or frequent occurrences of zero.
Preprocess data to ensure a more uniform distribution of magnitudes within groups of 16.
Validate the outputs using higher precision formats when dealing with critical applications.

The format is optimized for scenarios with homogeneous values across groups but is unsuitable for operations that expand the range, like reciprocal, due to inherent precision constraints.

2025-01-03 22:10 UTC, eyonland commented on ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp
> +    detail::bind_unary_operation_overload_complex_return_complex(module, ttnn::reciprocal, R"doc(BFLOAT16, BFLOAT8_B)doc", "bfloat8_b is supported only for non-zero inputs. Inputs containing zero may
This may be too much detail, let me know how this looks on the docs.

2025-01-08 15:47 UTC, VirdhatchaniKN approved these changes

2025-01-12 08:05 UTC, umadevimcw approved these changes

2025-01-15 05:13 UTC, mcw-anasuya approved these changes

2025-01-16 00:27 UTC, eyonland requested changes
Every backward op is going to get this link to the bfloat8_b documentation warning regardless of whether it uses reciprocal.

2025-01-17 04:52 UTC, eyonland approved these changes

2025-01-20 05:07 UTC, merged