#1599: Added the sfpu implementation of heaviside op
tenstorrent/tt-metal pull request #1656
Opened 2023-07-14 12:26 UTC by VirdhatchaniKN

Please find the heaviside op implementation

2023-07-14 15:31 UTC, muthutt reviewed
Looking good - nice work; 

TODO
------
- add missing documentation update as in (https://github.com/tenstorrent-metal/tt-metal/commit/ce0c9d70b61074e1e145f34c8ce1caf7c8ee10a4 for example)
- run tests locally using,  $ ./tests/scripts/run_pre_and_post_commit_tests.sh  as well as $ ./tests/scripts/run_tests.sh

Once you're done with that you need to run the following pipelines on Github Actions:
- pre/post commit pipeline
- scheduled build pipeline
- model pipeline
you should also post the results of the tests to the PR.

2023-07-19 16:13 UTC, muthutt approved these changes
LGTM

2023-07-19 16:45 UTC, tt-aho requested changes

2023-07-19 16:51 UTC, tt-aho reviewed
Please also fix the second commit message or squash it

2023-07-20 14:47 UTC, closed without merging