1596: Add implementation for Exp2 op
tenstorrent/tt-metal pull request #1684
Opened 2023-07-17 13:34 UTC by umadevimcw

- Implementation for Exp2 op. 
- Tried to re-use the calculate exponential_body function, but the module is not returning the correct value for the exp2.  So copy pasted the exponential code as such in the exp2 module
- Tested the code with different input random range values. Range values such as 100, 1000, 256, and 512 are failing. Increasing the range value decreases the pcc value
- Tested the exp code with the same range and it is also failing for the above-mentioned ranges

2023-07-17 15:15 UTC, tt-aho requested changes

2023-07-17 16:57 UTC, tt-aho approved these changes

2023-07-17 18:19 UTC, muthutt requested changes
- please address comment to reduce copy-paste of code and instead invoke the calculate_exp<...>()
- please add changes to docs in folder docs/sources/ ... as in the PR for square_difference
- run the unit tests and en

2023-07-18 15:58 UTC, arakhmati approved these changes

2023-07-18 17:23 UTC, muthutt approved these changes
lgtm

2023-07-19 16:17 UTC, merged