Ngrujic/conv net mnist
tenstorrent/tt-metal pull request #1818
Opened 2023-07-24 08:19 UTC by nemanjagrujic

[post-commit] models - Run perf regressions on models and output report: https://github.com/tenstorrent-metal/tt-metal/actions/runs/5707531208

[post-commit] all - Post-commit main build and unit tests: https://github.com/tenstorrent-metal/tt-metal/actions/runs/5707532085

[post-commit] all - Fast dispatch post-commit main build and unit tests: https://github.com/tenstorrent-metal/tt-metal/actions/runs/5707532831

Scheduled build and run all regressions and models:  https://github.com/tenstorrent-metal/tt-metal/actions/runs/5707534351

Scheduled fast dispatch build and run all regressions and models: https://github.com/tenstorrent-metal/tt-metal/actions/runs/5712127298

2023-07-24 13:33 UTC, ashayestehmanesh requested changes
there are going to be some changes in enable_compile_cache, disable_compile_cache in main very soon. Make sure your code is up to date when it is going to be merged.

2023-07-26 13:45 UTC, farbabi approved these changes

2023-07-26 17:09 UTC, ashayestehmanesh approved these changes

2023-07-27 07:55 UTC, tt-nshanker approved these changes

2023-07-31 10:32 UTC, merged