Custom relu, add, bcast ops without autoformatting + conv reader better padding implementation + conv 1x1 op variant with matmul
tenstorrent/tt-metal pull request #1900
Opened 2023-07-27 18:14 UTC by tt-nshanker

2023-07-31 17:58 UTC, arakhmati requested changes

2023-07-31 20:07 UTC, tt-aho approved these changes
lgtm after Akhmed's comments are addressed

2023-07-31 20:34 UTC, ashayestehmanesh approved these changes
@tt-nshanker I'll approve, but please change the numbers in perf file.

2023-08-01 01:10 UTC, arakhmati approved these changes

2023-08-01 01:13 UTC, merged