#1587: add support for ERF, ERFC statistics operators
tenstorrent/tt-metal pull request #1918
Opened 2023-07-28 18:02 UTC by VirdhatchaniKN

Implemented ERF , ERFC op with previous comments

2023-08-01 16:55 UTC, muthutt requested changes
this branch looks okay; but WH B0 kernel is not compile ready and causes failure. Please fix it.

2023-08-01 17:05 UTC, muthutt requested changes
lot of small changes requested;
why are we not using this formula directly ? I'm still OK with your implementation 
```erfc(x) = 1 - erf(x)```

2023-08-03 19:18 UTC, muthutt approved these changes

2023-08-03 19:32 UTC, tt-aho approved these changes
Looks good, but update your commit message to say something like adding support for these ops instead of PR

2023-08-04 00:05 UTC, merged