#1587: #1588, #2052: erf, erfc math function implementation for GS, WH_B0
tenstorrent/tt-metal pull request #2031
Opened 2023-08-04 06:26 UTC by muthutt

#1588, #1587: erf, erfc function implementation extracted outside of ckernel_sfpu.h
#2052: enable erf/erfc for GS and WH B0 in the split header representation

2023-08-05 05:13 UTC, tt-aho requested changes

2023-08-07 19:46 UTC, arakhmati approved these changes
LGTM!

2023-08-07 20:42 UTC, mywoodstock approved these changes

2023-08-08 00:46 UTC, tt-nshanker approved these changes

2023-08-08 13:38 UTC, tt-aho requested changes

2023-08-08 15:27 UTC, kkwong10 approved these changes
Two questions regarding ckernels.. I will approve for now, but please address the questions.

2023-08-08 20:03 UTC, tt-aho approved these changes

2023-08-08 20:06 UTC, merged