#1946: Add Falcon Attention, MLP, DecoderLayer, Model, and CausalLM
tenstorrent/tt-metal pull request #2072
Opened 2023-08-08 16:28 UTC by TT-BrianLiu

- Two layers for Model and CausalLM (PCC: 0.988 and 0.986)
- batch=1, seq_len=128, no KV-cache
- Add einops to requirements-dev

2023-08-08 17:17 UTC, davorchap approved these changes

2023-08-08 17:19 UTC, boris-drazic approved these changes

2023-08-09 14:21 UTC, ashayestehmanesh requested changes
This is not up to the standards. 

Please refactor and re-organize your code before merging.

2023-08-09 19:28 UTC, ashayestehmanesh requested changes
additionally, test should be in `tt-metal/tests/.../models/falcon/tests` 

models files should be in `tt-metal/models/falcon/tt`

and this PR is missing `gs_demo` and `cpu_demo`, `test_perf_falcon` files. First two should be located in `tt-metal/models/falcon/demo` and the last in `...falcon/tests`

2023-08-14 16:14 UTC, ashayestehmanesh approved these changes

2023-08-14 17:35 UTC, merged