Asinh and Acosh implementation
tenstorrent/tt-metal pull request #2123
Opened 2023-08-11 10:12 UTC by umadevimcw

- Implemented asinh and acosh as composite op
- Added the reference python code under `reference_eltwise` folder

2023-08-11 15:52 UTC, tt-aho requested changes

2023-08-11 17:02 UTC, muthutt requested changes
- please make changes to run add + 1, sub - 1 type operations to use add_unary or subtract_unary functions in tt_dnn library; they use broadcast and don't create large constant tensors.

- update docs to indicate what is the valid range for these inverse functions; I know we don't support a large range so would be good to capture it for our API users

- update both implementations to use scoped tensors so there is good deallocate strategy

2023-08-14 01:16 UTC, muthutt approved these changes
LGTM

2023-08-14 05:01 UTC, tt-aho approved these changes

2023-08-14 06:50 UTC, merged