#905: update concat doc, use in yolov3, fallback concat in SD, refactor conv utils
tenstorrent/tt-metal pull request #2147
Opened 2023-08-12 01:22 UTC by muthutt

- update concat doc, 
- use on device concat in yolov3, 
- use fallback concat in place of torch.concat for CPU operation in SD

2023-08-12 05:25 UTC, tt-aho requested changes
I don't believe stack and concat are equivalent in pytorch, so I don't think we should be adding stack as just an alias of concat.

Stack concatenates tensors on a new dim, so the number of dims change. As a result, all tensors must be same size.

Concat conatenates along a given existing dim. So tensor sizes must be same except on the concatenating dim.

2023-08-14 04:58 UTC, tt-aho approved these changes
lgtm

2023-08-14 14:01 UTC, farbabi requested changes

2023-08-14 14:13 UTC, ashayestehmanesh approved these changes

2023-08-16 21:22 UTC, tt-nshanker approved these changes

2023-08-16 21:34 UTC, boris-drazic approved these changes
As Faraz suggested, conv_on_device_utils shoul be added to existing utils file rather than separate one for conv.

2023-08-16 21:35 UTC, farbabi requested changes

2023-08-17 17:24 UTC, farbabi approved these changes

2023-08-17 19:29 UTC, merged