Parallelize Input Embeddings + Fuses With Utilization
tenstorrent/tt-metal pull request #2211
Opened 2023-08-17 19:42 UTC by ntarafdar

Parallelized input embeddings and fused with tilization.

Also added tests that test the Embedding table sizes of Falcon, Bert, and Llama.

And everyone else, please double check my parallelism. The table is split up across all RISCV data cores (2 RISCV cores per tennis core). The input specifying which rows to pick out are broadcast across all cores. And then each core filters for the rows that are within its range.

Edit: there are two modes of parallelism. First (the default) splitting the input across multiple cores (input being the indices we wish to include). The second being splitting the weights.

2023-08-21 15:40 UTC, arakhmati requested changes

2023-08-21 15:56 UTC, tt-nshanker approved these changes

2023-08-21 17:18 UTC, mywoodstock approved these changes

2023-09-14 21:41 UTC, arakhmati approved these changes

2023-09-15 14:57 UTC, tt-aho approved these changes
Minor comments, chip_id -> device_id is a required change to prevent breaking on latest main

2023-09-15 15:04 UTC, tt-rkim approved these changes

2023-09-19 22:07 UTC, merged