Matmul relu fusion
tenstorrent/tt-metal pull request #2325
Opened 2023-08-25 19:56 UTC by tt-aho

2023-08-25 21:43 UTC, TT-BrianLiu approved these changes
Minor comments, but please fix

2023-08-25 22:30 UTC, ashayestehmanesh approved these changes

2023-08-26 20:49 UTC, muthutt reviewed
please update wh-b0 code for relu max should enable this PR to go through

2023-08-26 20:49 UTC, muthutt requested changes
please update wh-b0 code for relu max should enable this PR to go through

2023-09-12 15:08 UTC, closed without merging