Remove need to call CompileProgram, ConfigureDeviceWithProgram, InitializeDevice, WriteRuntimeArgsToDevice as they are implicitly called by CreateDevice, LaunchKernels/EnqueueProgram
tenstorrent/tt-metal pull request #2502
Opened 2023-09-07 21:00 UTC by TT-billteng

The functions can still be called if needed, just that they are now part of the `tt::tt_metal::detail` namespace, except for `InitializeDevice`, which has been merged into `Device` constructor.

`LaunchKernels` has been renamed to `LaunchProgram` to match `EnqueueProgram`

2023-09-07 23:26 UTC, tt-nshanker approved these changes

2023-09-14 14:38 UTC, tt-aho approved these changes

2023-09-14 15:12 UTC, ashayestehmanesh approved these changes

2023-09-14 23:02 UTC, tt-rkim approved these changes
My owned portion LGTM

2023-09-14 23:18 UTC, abhullar-tt approved these changes
LGTM so much cleaner

2023-09-14 23:21 UTC, DrJessop requested changes
compileProgram->compile_program and then good to go.

2023-09-16 01:30 UTC, DrJessop approved these changes

2023-09-16 01:49 UTC, merged