Merge resnet updates to main
tenstorrent/tt-metal pull request #2612
Opened 2023-09-13 17:39 UTC by tt-nshanker

CI links coming soon

2023-09-19 18:26 UTC, ashayestehmanesh approved these changes

2023-09-22 14:28 UTC, ashayestehmanesh approved these changes

2023-09-26 19:49 UTC, davorchap approved these changes

2023-10-02 18:53 UTC, farbabi approved these changes

2023-10-02 21:07 UTC, TT-billteng requested changes
Please move the matmul python binding to the right file

2023-10-05 15:43 UTC, closed without merging