Bert Embeddings
tenstorrent/tt-metal pull request #2643
Opened 2023-09-14 15:44 UTC by ntarafdar

Using the TT Embeddings for Bert instead of doing on software. 

Also changed perf measurement to measure embedding time and inference time.

2023-09-20 17:40 UTC, ashayestehmanesh requested changes

2023-09-22 14:25 UTC, ashayestehmanesh approved these changes

2023-10-06 20:35 UTC, farbabi approved these changes
Add passing pipeline tests before merging.

2023-10-06 21:17 UTC, tt-aho approved these changes

2023-10-06 22:03 UTC, merged