#2443: eltwise ops for erfinv, complex tensors support for GS and WH B0; enable ops bug fixes for WH B0
tenstorrent/tt-metal pull request #2715
Opened 2023-09-18 21:20 UTC by muthutt

8532df0: #0: Update license for reference implementation
73e2a33: #2443: Add support for erfinv op
aa6f3cc: #2632: Fix whb0 failures for exp2, expm1, rqrt, logaddexp2 and ldexp  …
078bae8: #0: add SPDX license header to erfinv implementation
ad88bbc: #2563: Add support for unary i0 op
9f0460c: #2632: Remove WHBO test skip for logkind
#2673: unable to make nan inputs on-device for WH B0 
#2715   : update isnan, isinf bug in WH B0 implementation
   : eltwise unary tests unblocked for the same
9dcee0a832cddc6aab3fad34208549451e5744b9 : #1549 complex tensor support and update docs for complex ops
09319e264bc84e4d7b3242ee9eddecba33e22e8b :#2729 Add support for digamma op
Add support tan, lgamma and multigamma ops

2023-09-21 18:49 UTC, tt-rkim requested changes
CODEOWNERS look good, however I'm requesting changes that cannot wait until the next PR or in a future issue.

2023-09-21 19:15 UTC, tt-nshanker approved these changes

2023-09-21 20:34 UTC, tt-rkim approved these changes

2023-09-22 00:35 UTC, tt-aho requested changes

2023-09-22 14:35 UTC, ashayestehmanesh approved these changes

2023-09-25 15:50 UTC, arakhmati requested changes

2023-09-25 16:11 UTC, mywoodstock approved these changes

2023-09-25 21:02 UTC, kkwong10 approved these changes
lgtm

2023-09-25 22:20 UTC, arakhmati approved these changes

2023-09-26 13:23 UTC, tt-aho approved these changes
lgtm. Please fix your first commit message `#0: update rebase to main 09/13` to correctly reflect what the changes actually are.

2023-09-27 05:38 UTC, merged