#2944: reduce min operation
tenstorrent/tt-metal pull request #2726
Opened 2023-09-19 00:00 UTC by muthutt

#2944: reduce min operation: reduce min operation added to the code base

2023-09-28 05:18 UTC, tt-aho requested changes

2023-09-28 18:12 UTC, mywoodstock approved these changes
lgtm contingent on @tt-aho's comments resolution.

2023-09-29 13:30 UTC, tt-aho requested changes
Some of my comments weren't addressed yet.

Also, per contribution guidelines we do not allow commit messages that say they are addressing review / comments. Please remove this from your commit message

2023-09-29 17:55 UTC, arakhmati approved these changes

2023-09-29 18:34 UTC, tt-aho approved these changes
lgtm if pipelines pass. Upstream change makes sense. Was previously written without const to prevent copying buffers, but since tensors can share buffers this is no longer needed so should be made const.

2023-09-29 20:15 UTC, merged