#3040: rsub, rpow, rdiv ops
tenstorrent/tt-metal pull request #3038
Opened 2023-10-05 01:00 UTC by muthutt

#3040: rsub, rpow, rdiv ops
       rdiv op has some numerical issue so not tested as part of this commit

2023-10-05 14:01 UTC, tt-aho requested changes

2023-10-05 16:46 UTC, tt-aho requested changes
I have corrected some of my previous comments as they were made based on the docstring of the rpow op saying the arg is the exponent, when the arg is actually the base.

Please refer to the updated/new comments (emails don't show comment updates)

2023-10-05 23:40 UTC, tt-aho requested changes

2023-10-06 00:17 UTC, mywoodstock approved these changes

2023-10-06 01:32 UTC, closed without merging