#3300: triu, tril and #3276: update empty and #2583 pool 2d enable
tenstorrent/tt-metal pull request #3301
Opened 2023-10-21 00:26 UTC by muthutt

#3300: triu, tril and 
#3276: update empty and #2583 pool 2d enable 
#0: enable more tests to run on WHB0

2023-10-21 01:35 UTC, tt-aho requested changes
mostly lgtm. Minor comments but they should be addressed before merge

2023-10-22 22:29 UTC, tt-aho approved these changes

2023-10-23 16:31 UTC, arakhmati approved these changes

2023-10-23 18:58 UTC, ashayestehmanesh approved these changes

2023-10-23 19:32 UTC, merged