#2931 phase 1 erisc app FW
tenstorrent/tt-metal pull request #3332
Opened 2023-10-24 02:48 UTC by aliuTT

Done:
- erisc FW build on device init
- erisc data transfer protocol, some host driven unit tests passing on N300
- initial eth core L1 memory design
- stripped out open source able tt_eth_api

Major outstanding (P2):
- Program integration somewhat ready, but needs testing
- Load and run reader/writer kernels

2023-10-24 13:37 UTC, pgkeller requested changes
Nice work, that's a lot of stuff to navigate.  Only concern is the tmu-crt0.

2023-10-24 13:56 UTC, abhullar-tt requested changes

2023-10-27 20:23 UTC, TT-billteng approved these changes
Great work!

2023-10-27 20:36 UTC, abhullar-tt approved these changes

2023-10-30 15:53 UTC, pgkeller approved these changes

2023-10-30 17:46 UTC, merged