#2901: Fix log sigmoid
tenstorrent/tt-metal pull request #3367
Opened 2023-10-25 08:47 UTC by VirdhatchaniKN

Change in log_sigmoid range in sweep test

2023-10-25 20:18 UTC, muthutt requested changes
why are we reducing the range ? I thought goal was to improve accuracy of log sigmoid

2023-11-08 06:00 UTC, muthutt approved these changes
accept lower range and documented for users of API

2023-11-08 12:42 UTC, arakhmati approved these changes

2023-11-08 15:10 UTC, tt-aho approved these changes

2023-11-08 15:13 UTC, TT-BrianLiu approved these changes

2023-11-08 15:48 UTC, merged