#2925: Extend reshape for row major layout
tenstorrent/tt-metal pull request #3622
Opened 2023-11-03 16:45 UTC by VirdhatchaniKN

Tested for shapes
- [4, 4, 32, 32] to [-1, 2, 32, 32],
- [4, 4, 32, 32] to [2, -1, 32, 32],
- [4, 4, 32, 32] to [4, 1, -1, 32],
- [4, 4, 32, 32] to [4, 2, 32, -1],
- [2, 3, 4, 4] to [2, 12, 1, 4],
- [1, 3, 6, 4] to [3, 1, 3, 8],
- [1, 1, 60, 768] to [1, 60, 12, 64],
- [2, 4, 128, 4] to [1, 2, 64, 32],
- [1, 11, 64, 2] to [1, 11, 1, 128],
- [1, 2, 64, 32] to[2, 4, 128, 4],
- [3, 2, 2, 32]to [1, 3, 1, -1]

2023-11-03 17:29 UTC, tt-aho requested changes
My overall question is that this is basically just doing CPU copy/reshape, which is basically what fallback reshape does. Just wondering what exactly the purpose of this is because it doesn't really seem to add much value compared to just using fallback reshape since you need to use a different api call anyways? Is it any faster?

2023-11-03 21:10 UTC, tt-aho requested changes

2023-11-07 14:24 UTC, tt-aho requested changes

2023-11-08 14:33 UTC, tt-aho approved these changes

2023-11-09 23:04 UTC, muthutt approved these changes
approve as per Host Operation changes

2023-11-10 01:15 UTC, merged