Vignesh/mistral tt implementation set 2
tenstorrent/tt-metal pull request #3692
Opened 2023-11-08 12:37 UTC by vigneshkeerthivasanx

This branch contains 

- fix for low PCC due to feed-forward submodule.
- Update rotary embedding to use complex_multiplication in TT ops

2023-11-08 23:58 UTC, tt-aho requested changes
Can you fix your git history/commits for this PR? It is showing commits from main as part of your changes which makes it hard to review.

Am also blocking for now as there are still ongoing complex tensor requests/discussions in #3412 to finish discussing/resolving

2023-11-09 14:41 UTC, tt-aho reviewed
lgtm overall, will approve after complex tensor changes are finalized

2023-11-09 15:51 UTC, farbabi approved these changes

2023-11-09 23:50 UTC, tt-aho approved these changes
Approving now since #3412 comments have been mostly addressed so lgtm once integrated with new changes

2023-11-10 16:33 UTC, merged