#229: Restructure tt_metal/src to tt_metal/hw
tenstorrent/tt-metal pull request #3789
Opened 2023-11-14 17:47 UTC by pgkeller

Massive code movement
Simplify firmware structure
Create hw/inc dir
Remove unused code
Don't generate ckernel_ops.h, use pre-generated versions Delete lots of makesfiles
Move debug code under inc/debug

Still a lot to do (ckernels), but gets the structure closer to where we want

2023-11-15 18:17 UTC, DrJessop requested changes
Given you were changing a bad path in cq_interface.hpp, can you just remove it?

2023-11-15 21:41 UTC, muthutt approved these changes
LGTM - approve to unblock

2023-11-15 21:52 UTC, DrJessop approved these changes

2023-11-15 23:26 UTC, tt-rkim approved these changes

2023-11-15 23:27 UTC, davorchap approved these changes
💯

2023-11-16 01:32 UTC, mywoodstock approved these changes

2023-11-16 02:10 UTC, eyonland approved these changes

2023-11-16 03:03 UTC, merged