#0: add split by 2 on last dim 3 or the one before last dim 3
tenstorrent/tt-metal pull request #3793
Opened 2023-11-14 22:07 UTC by muthutt

#0: add split along any specified dim
  - add support for split along dim=2 Y in (i.e. W, Z, Y, X)
  - this enables split along dim Y, in addition to previously exisiting along X.

2023-11-14 22:11 UTC, arakhmati approved these changes

2023-11-14 22:21 UTC, tt-aho requested changes

2023-11-14 23:45 UTC, tt-aho requested changes
I force pushed a reformat of the c++ file using clang-format. We haven't fully confirmed our c++ formatter, @tt-rkim I think was planning on clang-format, but the formatter you used was indenting things like namespaces which we don't do from our style guide.

Only remaining comment I have is for the dim arg description to be added

2023-11-15 06:02 UTC, tt-aho approved these changes

2023-11-15 06:03 UTC, merged