Dma/3467 dprint cleanup
tenstorrent/tt-metal pull request #4018
Opened 2023-11-27 22:25 UTC by tt-dma

A bunch of changes here, each in their own commit:
- Single-thread DPrint server
- DPrint server muting
- Add DEFFAULTFLOAT, DEC, OCT support for DPrint (issue https://github.com/tenstorrent-metal/tt-metal/issues/3929)
- Rename all DPrint macros to match their std counterparts
- Update DPrint gtests to cover all features (some new issues raised here, see https://github.com/orgs/tenstorrent-metal/projects/58/views/1)
- Move and rename llrt/tt_debug_print_server.hpp/cpp
- Add sanitization for invalid core coords sent to the dprint server (issue https://github.com/tenstorrent-metal/tt-metal/issues/2485)
- Cleanup here and there

2023-11-28 00:00 UTC, tt-rkim approved these changes

2023-11-28 13:37 UTC, pgkeller requested changes
Be sure to update the debug.rst file and add new API examples

2023-11-29 00:18 UTC, TT-billteng approved these changes

2023-11-29 15:18 UTC, pgkeller approved these changes

2023-11-29 17:47 UTC, merged