#3894: backward ops for tt-metal
tenstorrent/tt-metal pull request #4054
Opened 2023-11-29 00:59 UTC by muthutt

#0: backward ops for tt-metal

2023-11-29 23:21 UTC, eyonland requested changes

2023-11-30 17:21 UTC, arakhmati approved these changes

2023-11-30 20:30 UTC, tt-aho approved these changes
Generally lgtm.

Some of the docs might not have the right plurality, should give it a quick review before merge.

Ex where_bw has multiple inputs, but says `Input tensor`

2023-12-01 19:03 UTC, eyonland approved these changes

2023-12-01 23:45 UTC, merged