#2860: Init one UMD per MMIO device ID and the remote devices it controls
tenstorrent/tt-metal pull request #4080
Opened 2023-11-29 20:45 UTC by abhullar-tt

This helps enable #2943 and concurrent modes of execution support. (Commit taken from https://github.com/tenstorrent-metal/tt-metal/pull/3114/) 

Helps enable 1 HW CQ by setting `num_host_mem_ch_per_mmio_device` to be 1 (MMIO device) + num of remote devices controlled by MMIO device. 

Currently host mem channel = hugepage 

We could have multiple mmio devices with a diff number of remote devices so this change allows each mmio + remote device grouping to have diff number of hugepages

This will work for N300 but we can only have 4 host channels per mmio device. #4087 is opened to spec out how we can have multiple HW CQs for Galaxy.

2023-11-29 23:09 UTC, davorchap approved these changes

2023-12-01 17:33 UTC, DrJessop requested changes

2023-12-01 20:01 UTC, DrJessop approved these changes

2023-12-02 00:22 UTC, TT-billteng approved these changes
looks good

2023-12-02 21:18 UTC, merged