#4141: Add GetPreferredNOCForDRAMRead, GetPreferredNOCForDRAMWrite and update all ops to use these apis
tenstorrent/tt-metal pull request #4184
Opened 2023-12-05 16:00 UTC by tt-aho

2023-12-05 19:04 UTC, muthutt approved these changes
LGTM

2023-12-05 19:14 UTC, abhullar-tt approved these changes

2023-12-05 21:00 UTC, TT-billteng requested changes
We should create variants of `DatamovementConfig` like `DMReadConfig` and `DMWriteConfig` with  `GetPreferredNOCForDRAMWrite` and `GetPreferredNOCForDRAMRead` implicitly called to avoid extra top-level APIs and also more variables that users need to set

2023-12-06 19:24 UTC, TT-billteng approved these changes
Love it!

2023-12-09 09:18 UTC, merged