#3178: ttl.tensor.reduce_max_w operation breaks with low PCC [Wormhole]
tenstorrent/tt-metal pull request #4220
Opened 2023-12-06 23:15 UTC by muthutt

#3178: ttl.tensor.reduce_max_w operation breaks with low PCC [Wormhole]
 #3564: ttl.tensor.arange op fails in some test cases
#3604: ttl.tensor.var_hw operation breaks with low PCC [Wormhole]
#3606: mean_hw low PCC
#3605: ttl.tensor.std_hw operation breaks with low PCC [Wormhole]

2023-12-08 08:51 UTC, JelenaTosicJtosic commented on tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_arange.py
Thanks for the reply Muthu. 
Well the comment above was meant to address all changes we have here in this PR, in general. So if we are not sure enough why the L1 is does not work in that specific case, it's probably not the best idea to change it with DRAM straight away, because some underlying issue could be masked? But If we are sure, I guess than the documentation for that operation should be updated to mention that the op does has some constraint there, and then the unit will get updated. Another thing to consider also, is lowering pcc threshold value so that the test would pass, because I think this is generally not the best idea, looks like we are again masking the issue. And last thing, the tests for arange, stats_mean, and stats_std/var where deliberately omitted in wormhole subfolder, so that we can avoid code duplication - if we are testing same things of course.

2024-01-02 20:37 UTC, TT-billteng requested changes
don't think you need to update UMD

2024-01-03 02:15 UTC, TT-billteng approved these changes

2024-01-03 02:17 UTC, TT-billteng requested changes
please ensure UMD isn't updated with this PR

2024-01-03 18:59 UTC, TT-billteng approved these changes

2024-02-02 23:04 UTC, tt-aho commented
Can this be closed now that fix is in?

2024-02-20 15:57 UTC, closed without merging