#3974: nanogpt uplift and move weights to weka path
tenstorrent/tt-metal pull request #4221
Opened 2023-12-07 06:54 UTC by punithsekar

This PR has following
- Uplifted nanoGPT model and recorded the ops that do not have TT-ops
- Tilized weights tesnors are stored and loaded from weka path.
- Tests for both sub-modules and the whole model.

2023-12-07 15:32 UTC, boris-drazic approved these changes

2023-12-11 16:51 UTC, farbabi requested changes
As external users do not have access to weka, weights need to be stored/loaded to/from a folder created and called "datasets" under the model's directory **if** weka path was not found. See Falcon7b demo.

2023-12-19 15:22 UTC, farbabi approved these changes

2024-01-12 08:32 UTC, punithsekar commented
Here is the passing CI Links
[post-commit] Run all post-commit workflows [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7498620768)
[post-commit] models - Run device perf regressions on models and output report [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7498628466/job/20414055265)

I have requested for review because i have modified run_models.sh file.

2024-01-12 15:28 UTC, boris-drazic approved these changes

2024-01-19 15:03 UTC, saichandax commented
CI passed. Link [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7582674618)

2024-01-19 15:04 UTC, merged