#4003: Adding whisper functional model
tenstorrent/tt-metal pull request #4277
Opened 2023-12-12 00:13 UTC by eyonland

2023-12-18 19:33 UTC, TT-billteng requested changes
don't think you need to update UMD for this

2023-12-18 21:04 UTC, TT-billteng approved these changes

2023-12-21 21:12 UTC, farbabi approved these changes
Approving... please make sure relevant CI tests pass before merging.

2023-12-21 22:38 UTC, arakhmati approved these changes

2023-12-23 18:15 UTC, merged

2023-12-23 21:55 UTC, davorchap commented
Nice!👍