#4433: part-3 of backward ops for TT Metalium
tenstorrent/tt-metal pull request #4448
Opened 2023-12-20 18:07 UTC by muthutt

Optimizer
========
- 4203 - tt_lib.tensor.lamb_optimizer

TM Ops
======
- tt_lib.tensor.repeat
- tt_lib.tensor.repeat_interleave

Activation
========
- 4373 - tt_lib.tensor.relu_bw

Relational ops
==========
- tt_lib.tensor.gt_bw
- 4377  - tt_lib.tensor.binary_le_bw
- tt_lib.tensor.ne_bw

Clamp
=====
- 4287  - tt_lib.tensor.clamp_bw
- tt_lib.tensor.clamp_min_bw
- tt_lib.tensor.clamp_max_bw

2023-12-21 21:59 UTC, mywoodstock approved these changes

2023-12-21 23:02 UTC, TT-BrianLiu requested changes

2023-12-22 08:05 UTC, umadevimcw commented on tests/tt_eager/python_api_testing/unit_testing/backward_ops/test_backward_abs.py
> -    torch.manual_seed(12386)
Updated

2023-12-22 08:05 UTC, umadevimcw commented on tests/tt_eager/python_api_testing/unit_testing/backward_ops/test_backward_abs.py
> +from tests.tt_eager.python_api_testing.unit_testing.backward_ops.utility_funcs import *
updated

2023-12-22 08:05 UTC, umadevimcw commented on tests/tt_eager/python_api_testing/unit_testing/backward_ops/test_backward_abs.py
> +    golden_tensor.append(in_data.grad)
updated

2023-12-22 15:04 UTC, eyonland approved these changes

2023-12-22 20:39 UTC, TT-BrianLiu approved these changes

2023-12-26 05:59 UTC, merged