#4431: mnist gs_demo benchmark
tenstorrent/tt-metal pull request #4502
Opened 2023-12-27 07:51 UTC by jayasuryamaganuru

This PR contains benchmarking of mnist gs_demo for MNIST Handwritten Digit Classification test dataset.
model is tested with 1000 datapoints extracted from the dataset and the accuracy is listed below:

Metric: Accuracy
Accuracy: 62.2

2023-12-28 01:26 UTC, muthutt requested changes
request to add randomization (in repeatable way) to sample the data set for inference

2023-12-28 13:41 UTC, jayasuryamaganuru commented on models/experimental/mnist/tests/test_perf_accuracy_mnist.py
> +    dataloader = DataLoader(test_dataset, batch_size=1)
committed the suggestion, 
If shuffle=True isn't specified in Dataloader , randomization wasn't happening, even if we specify the generator.
commit link - https://github.com/tenstorrent-metal/tt-metal/compare/main...jayasurya/mnist_gs_demo_benchmarking

2023-12-28 13:46 UTC, jayasuryamaganuru commented
When randomness introduced to the Dataloader with seed set to 213, there's slight increase in accuracy.

metric: Accuracy
Accuracy: 63.9

2023-12-28 19:59 UTC, jayasuryamaganuru commented
Thank you for noting the lower accuracy. I shared the same concern, 
as we're using the torch model's state_dict for weights instead of starting with random values.

I evaluated the accuracy of the torch model and found it matches the accuracy of the tt model, both around 60%. 
After reviewing a [comment](https://github.com/tenstorrent-metal/tt-metal/blob/1de7f848d5c27b830ff4e2a669819d5bb5e6321e/models/experimental/mnist/tt/mnist_model.py#L61), I've become convinced that the model might not have been trained optimally.


> Thanks - Randomness pattern in dataloader for validation testing is important; besides that it seems like very low accuracy for MNIST model which typically runs at 99%; are the weights random or not trained well ? Just curious.
> […](#)
> On Thu, Dec 28, 2023 at 5:46 AM jayasuryamaganuru ***@***.***> wrote: When randomness introduced to the Dataloader with seed set to 213, there's slight increase in accuracy. metric: Accuracy Accuracy: 63.9 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

2024-01-09 15:07 UTC, boris-drazic approved these changes

2024-01-09 21:52 UTC, muthutt approved these changes
LGTM

2024-01-11 11:24 UTC, jayasuryamaganuru commented
@muthutt, the MNIST model weights have been updated in the WEKA path,
with a torch model that was trained to achieve an accuracy of **98.24%** on MNIST test dataset.
Now the tt_model is yielding an accuracy of **80.0%.**, for 1000 iterations

2024-01-12 05:57 UTC, jayasuryamaganuru commented
@muthutt Yes, that's correct. However, the metric used for evaluation is accuracy, not F1 score

2024-01-12 18:08 UTC, farbabi approved these changes

2024-01-17 12:49 UTC, merged