#2470: support reduce max on all dims on WH B0
tenstorrent/tt-metal pull request #4516
Opened 2023-12-28 18:59 UTC by muthutt

#2470: reduce sum, max for dim=[N,C,H,W][2] will need transpose-compute-transpose on the WH B0 architecture today
     : enable test on WHB0 for reduce max

2023-12-28 19:06 UTC, tt-aho requested changes
Can you refactor the body of sum and max into a common function (probably just overload reduce with function signature `Tensor reduce(const Tensor &input_tensor, ReduceOpMath reduce_math, uint dim, const MemoryConfig& output_mem_config = operation::DEFAULT_OUTPUT_MEMORY_CONFIG);` and just have sum and max call it with ReduceOpMath set instead of duplicating code?

2024-01-02 19:41 UTC, tt-aho requested changes
my original request has been addressed and lgtm but you need to revert your umd change

2024-01-02 22:11 UTC, TT-billteng approved these changes

2024-01-02 22:12 UTC, tt-aho approved these changes

2024-01-03 02:01 UTC, merged