#2470: (Updated) reduce sum, max for dim=[N,C,H,W][2] will need trans…
tenstorrent/tt-metal pull request #4546
Opened 2024-01-03 19:10 UTC by muthutt

will need transpose-compute-transpose on the WH B0 architecture today

- This reverts commit 5fc3c9a3cee0ab42fdab1e43a20d34f7a945d341.
- applying workaround strictly once is required

2024-01-03 19:35 UTC, tt-aho approved these changes

2024-01-03 21:27 UTC, arakhmati requested changes

2024-01-03 21:27 UTC, arakhmati commented on tests/tt_eager/ops/test_reduce_op.cpp
> +        tt::tt_metal::program_cache::num_entries() >= 5,
Why is it `>=`?

2024-01-03 23:11 UTC, TT-billteng requested changes
UMD

2024-01-04 00:01 UTC, TT-billteng approved these changes

2024-01-04 04:45 UTC, arakhmati approved these changes

2024-01-22 15:05 UTC, tt-rkim approved these changes

2024-01-22 15:14 UTC, tt-aho requested changes

2024-01-22 15:14 UTC, tt-aho commented on tt_eager/tt_dnn/op_library/reduce/reduce_op.cpp
> +
Why can't this just call `reduce_impl<ReduceOpMath::SUM>` like in the case for max?

What is the difference?

2024-01-22 17:55 UTC, tt-aho commented
So is the plan to move directly to an actual fix for the cause of the issue, and not merge this workaround at all?

2024-01-27 00:37 UTC, closed without merging