#4503: Demo for functional bloom - WIP
tenstorrent/tt-metal pull request #4554
Opened 2024-01-04 03:49 UTC by punithsekar

This PR contains contains end to end demo for ttnn_functional_bloom_model(CausalLM).

2024-01-05 15:43 UTC, boris-drazic requested changes

2024-01-05 15:43 UTC, boris-drazic commented on models/experimental/functional_bloom/README.md
> +If you wish to run the demo with a different input use `pytest --disable-warnings models/experimental/functional_bloom/demo/demo.py::test_demo[address_to_your_json_file.json-path_to_functional_bloom]
I was not able to run the test with different input json file.
E.g., 
```
pytest --disable-warnings models/experimental/functional_bloom/demo/demo.py::test_demo[models/experimental/functional_bloom/demo/input_data.json-models.experimental.functional_bloom.tt.ttnn_optimized_functional_bloom]
```
errors out with 
```
ERROR: not found: /home/boris/tt-metal/models/experimental/functional_bloom/demo/demo.py::test_demo[models/experimental/functional_bloom/demo/input_data22.json-models.experimental.functional_bloom.tt.ttnn_optimized_functional_bloom]
(no name '/home/boris/tt-metal/models/experimental/functional_bloom/demo/demo.py::test_demo[models/experimental/functional_bloom/demo/input_data22.json-models.experimental.functional_bloom.tt.ttnn_optimized_functional_bloom]' in any of [<Module models/experimental/functional_bloom/demo/demo.py>])
```

2024-01-05 15:43 UTC, boris-drazic commented on models/experimental/functional_bloom/README.md
> +Our second demo is designed to run HellaSwag dataset, run this with `pytest --disable-warnings models/experimental/functional_bloom/demo/demo.py::test_demo_hellaswag[4-models.experimental.functional_
Can you explain what is number 4 in parametrers?
And if I change it the test fails immediately.
```
ERROR: not found: /home/boris/tt-metal/models/experimental/functional_bloom/demo/demo.py::test_demo_hellaswag[2-models.experimental.functional_bloom.tt.ttnn_optimized_functional_bloom]
(no name '/home/boris/tt-metal/models/experimental/functional_bloom/demo/demo.py::test_demo_hellaswag[2-models.experimental.functional_bloom.tt.ttnn_optimized_functional_bloom]' in any of [<Module models/experimental/functional_bloom/demo/demo.py>])
```

2024-01-09 15:08 UTC, boris-drazic approved these changes

2024-01-09 19:32 UTC, arakhmati approved these changes

2024-01-17 21:15 UTC, arakhmati approved these changes

2024-01-19 06:15 UTC, punithsekar commented
Here is the passing CI Links
[post-commit] Run all post-commit workflows [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7579435386)

2024-01-19 06:19 UTC, merged