Add Causal Mask support for Softmax
tenstorrent/tt-metal pull request #4559
Opened 2024-01-04 18:08 UTC by yugaoTT

2024-01-04 22:03 UTC, arakhmati approved these changes

2024-01-04 22:03 UTC, arakhmati commented on tests/tt_eager/python_api_testing/unit_testing/test_softmax.py
> +# @skip_for_wormhole_b0()
Did you mean to comment out the tests?

If no longer need this code, we should just delete it

2024-01-04 22:03 UTC, arakhmati commented on tt_eager/tt_dnn/op_library/softmax/softmax_op.hpp
> +    const bool is_causal_mask;
Do we need this attribute?

Can it be inferred by the op instead based on the mask shape?

2024-01-04 22:04 UTC, arakhmati requested changes

2024-01-04 22:04 UTC, arakhmati commented on tt_eager/tt_dnn/op_library/softmax/softmax_op.hpp
> +    const bool is_causal_mask;
Do we need this attribute?

Can it be inferred by the op instead based on the mask shape?

2024-01-04 22:55 UTC, mywoodstock approved these changes

2024-01-10 15:14 UTC, tt-aho commented on tests/tt_eager/python_api_testing/unit_testing/test_softmax_sharded.py
> +        # )
Remove if this isn't used

2024-01-10 15:31 UTC, arakhmati approved these changes

2024-01-10 19:40 UTC, merged