Ttnn 4761 add sweep for repeat interleave
tenstorrent/tt-metal pull request #4841
Opened 2024-01-20 00:20 UTC by eyonland

2024-01-20 00:26 UTC, arakhmati requested changes

2024-01-20 00:26 UTC, arakhmati commented on tests/ttnn/unit_tests/test_repeat_interleave.py
> +    tensor_tensor_2d = torch.tensor([[1, 2], [3, 4]])
Fix this variable name?

2024-01-22 16:22 UTC, eyonland commented on tests/ttnn/unit_tests/test_repeat_interleave.py
> +    tensor_tensor_2d = torch.tensor([[1, 2], [3, 4]])
done

2024-01-22 18:52 UTC, arakhmati approved these changes

2024-01-22 22:58 UTC, merged