#4215: Add Argmax and Argmin Fallback
tenstorrent/tt-metal pull request #4928
Opened 2024-01-25 07:35 UTC by Aswinmcw

Add Fallback support for Argmax and Argmin op
CI Test [link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7651232355)

2024-01-25 15:27 UTC, tt-aho requested changes

2024-01-25 15:27 UTC, tt-aho commented on tt_eager/tt_lib/fallback_ops/fallback_ops.py
> +    | keepdim    | Whether to retain the dimensionality of input | bool        |                 | No       |
dim and keepdim are required args (should say Yes)

2024-01-25 15:27 UTC, tt-aho commented on tt_eager/tt_lib/fallback_ops/fallback_ops.py
> +        result = result.unsqueeze(-1)
I think this should be part of the description since this differs from pytorch.

2024-01-25 15:27 UTC, tt-aho commented on tests/tt_eager/python_api_testing/unit_testing/fallback_ops/test_argmax_min_op.py
> +        _, comp_out = comparison_funcs.comp_allclose_and_pcc(pt_out, output)
comp_equal returns the allclose/pcc output as well so there isn't a need to run these two separately

2024-01-25 16:52 UTC, muthutt approved these changes
LGTM - please add links of testing when you can and address reviewer comments @Aswinmcw

2024-01-26 11:04 UTC, Aswinmcw commented
@muthutt I have addressed the comments and modified the code accordingly.

2024-01-26 14:49 UTC, tt-aho approved these changes

2024-01-26 14:49 UTC, tt-aho commented on tests/tt_eager/python_api_testing/unit_testing/fallback_ops/test_argmax_min_op.py
> +        logger.info(comp_pass)
You can print out the allclose/pcc like this
```
comp_pass, comp_out = comparison_funcs.comp_equal(pt_out, output)
logger.info(comp_out)
```

2024-01-29 05:55 UTC, Aswinmcw commented
CI Test Link [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7690881601)

2024-01-29 16:27 UTC, arakhmati approved these changes

2024-01-29 20:18 UTC, merged