Fix sharded buffers for one core in fast dispatch
tenstorrent/tt-metal pull request #4944
Opened 2024-01-25 19:40 UTC by tarafdarTT

fixes issue : https://github.com/tenstorrent-metal/tt-metal/issues/4706#issuecomment-1909159921

2024-01-25 21:14 UTC, tt-aho approved these changes

2024-01-26 00:07 UTC, DrJessop requested changes
Rebase to get latest changes.

Also, I believe this line in the device command constructor can now go away

```
    this->desc[this->sharded_buffer_num_cores_idx] = 1;
```

2024-01-26 00:07 UTC, DrJessop commented on tt_metal/impl/dispatch/kernels/command_queue_consumer.cpp
> +        bool is_sharded = (bool)command_ptr[DeviceCommand::buffer_type];
weird way of doing things, and potentially error prone. I'm guessing this just works because sharded buffers map to 1, and interleaved to 0.

2024-01-26 00:07 UTC, DrJessop commented on tt_metal/impl/dispatch/kernels/command_queue_consumer.cpp
> +        bool is_sharded = (bool)command_ptr[DeviceCommand::buffer_type];
cleaner way would be is_sharded = command_ptr[DeviceCommand::buffer_type] == (uint32_t)BufferType::SHARDED

2024-01-26 00:36 UTC, DrJessop approved these changes

2024-01-26 00:37 UTC, merged