#4487: Adding Upsample Op. Raising PR for compute kernel Colloboration
tenstorrent/tt-metal pull request #5007
Opened 2024-01-29 18:36 UTC by shwetankTT

!!!!DO NOT MERGE!!!!
I am opening this PR for collaboration on the compute upsample kernel. There are a few print and cout statements; please ignore them. I will remove all of them in a follow-up commit.

2024-01-30 01:46 UTC, mywoodstock requested changes

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/dataflow/writer_twice_interleaved_start_id.cpp
> +    const uint32_t tile_bytes = get_tile_size(8);
What is `8`?

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/dataflow/writer_twice_interleaved_start_id.cpp
> +    #else
remove the `BACKWARDS` portion for now.

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/dataflow/writer_twice_interleaved_start_id.cpp
> +    #else
`#endif`

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/compute/upsample_wh.cpp
> +// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
Move file to `tt_eager/tt_dnn/op_library/upsample/kernels/compute/`

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/dataflow/writer_twice_interleaved_start_id.cpp
> +// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
Move file to `tt_eager/tt_dnn/op_library/upsample/kernels/dataflow`

2024-01-30 01:46 UTC, mywoodstock commented on tt_metal/include/compute_kernel_api/upsample_wh.h
> +// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
Don't create new api files unless necessary. Use the existing apis.

2024-01-30 01:46 UTC, mywoodstock commented on tt_metal/include/compute_kernel_api/tile_move_copy.h
> +ALWI void copy_tile_with_upscale(uint32_t icb, uint32_t itile, uint32_t idst)
don't add new functions here unless cannot use any existing ones.

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/compute/upsample_wh.cpp
> +    uint32_t NHtWt = get_compile_time_arg_val(0);
use variable names with lower case only

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/compute/upsample_wh.cpp
> +    // - assumes the tiles come in in column major order from reader
reader is missing

2024-01-30 01:46 UTC, mywoodstock commented on tt_eager/tt_dnn/kernels/compute/upsample_wh.cpp
> +}
Fos this op, I don't think you need any compute kernel. This can be done by the reader and writer alone.

2024-02-02 08:50 UTC, TT-billteng requested changes
don't think you meant to bump UMD submodule version in this PR

2024-02-02 08:56 UTC, shwetankTT commented
> don't think you meant to bump UMD submodule version in this PR

yeah.. It came as when I was rebasing my changes with mainline. Will see how to remove It or create a fresh PR.

2024-02-02 17:02 UTC, TT-billteng approved these changes

2024-02-02 18:35 UTC, merged