#0: Add support for float to int typecast
tenstorrent/tt-metal pull request #5058
Opened 2024-02-01 12:48 UTC by bharane-ab

2024-02-01 17:38 UTC, muthutt requested changes
overall good start; but important changes needed like,
- make functionality for **typecast_float_int** to be available from **typecast**() at high level - no need for bindings and signature to export a new function
- fix number ladder for the C-kernel to capture unto max range of int32 as per code same I had provided
- fix C-kernel to handle the negative numbers correctly

2024-02-07 00:22 UTC, muthutt approved these changes
LGTM

2024-02-07 00:23 UTC, mywoodstock approved these changes

2024-02-08 00:57 UTC, rtawfik01 approved these changes

2024-02-08 01:09 UTC, merged