Add relational ops support to TTNN
tenstorrent/tt-metal pull request #5120
Opened 2024-02-05 06:36 UTC by Aswinmcw

Add relational ops support to TTNN
Sweep test results:
[eq.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161369/eq.csv)
[eqz.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161372/eqz.csv)
[gez.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161373/gez.csv)
[gt.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161374/gt.csv)
[gte.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161375/gte.csv)
[gtz.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161376/gtz.csv)
[lez.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161377/lez.csv)
[lt.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161378/lt.csv)
[lte.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161379/lte.csv)
[ltz.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161380/ltz.csv)
[ne.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161381/ne.csv)
[nez.csv](https://github.com/tenstorrent-metal/tt-metal/files/14161382/nez.csv)

2024-02-05 18:35 UTC, arakhmati requested changes

2024-02-05 18:35 UTC, arakhmati commented on ttnn/ttnn/operations/relational.py
> +        return torch_function(input_tensor)
Should this be?
```
return torch_function(input_tensor, 0)
```

2024-02-06 03:39 UTC, Aswinmcw commented on ttnn/ttnn/operations/relational.py
> +        return torch_function(input_tensor)
Resolved

2024-02-06 17:31 UTC, muthutt approved these changes
LGTM

2024-02-06 19:09 UTC, arakhmati approved these changes

2024-02-06 19:15 UTC, eyonland approved these changes

2024-02-06 19:31 UTC, merged