#4854: Implement transformer_block sub-module using ttnn for mistral …
tenstorrent/tt-metal pull request #5177
Opened 2024-02-07 15:53 UTC by Sudharsan-V

This PR has the mistral transformer block sub-module implemented using ttnn ops.

2024-02-13 16:47 UTC, farbabi approved these changes

2024-02-16 07:17 UTC, arakhmati requested changes

2024-02-16 07:17 UTC, arakhmati commented on models/experimental/functional_mistral/tt/ttnn_functional_transformer_block.py
> +    )
Please do this instead:

```
att_weight = ttnn.from_torch(parameter.attention_norm.weight, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
```

Also, why is it even necessary. This is a parameter which means we should preprocess it ahead of time. What `torch.nn.module` is this? RmsNorm?x

I might need to update the code in model_preprocessing to convert torch tensors to ttnn tensors. In the meantime, can you use `custom_preprocessor` to convert these weight to `ttnn` tensor in tile layout ahead of time?

2024-02-16 07:17 UTC, arakhmati commented on models/experimental/functional_mistral/tt/ttnn_functional_transformer_block.py
> +    )
Same here. Just use `ttnn.from_torch`

And this parameters should be preprocessed automatically too

2024-05-19 20:31 UTC, closed without merging