#0: Add support for typecast float <-> uint
tenstorrent/tt-metal pull request #5213
Opened 2024-02-08 13:43 UTC by bharane-ab

It have the support for following typecast conversion using ladder method in GS and WhB0

- bf16 -> uint16
- bf16 -> uint32
- uint16 -> float32(as kernel don't have support other than bf16 input dtype I actually perform bf16->float conversion)

Muthu we don't have a separate for uint to float conversion because float to uint and uint to float conversion are almost same. so to avoid code duplication I have called float to uint32 conversion.

2024-02-10 18:34 UTC, muthutt requested changes
please add separate code for uint -> float and float -> uint, as WH has unique capabilities. So we don't want to alias it. I'm OK with ckernel code duplication because it will be compiled anyway and we are exploring capability for better implementation in the future

2024-03-06 19:11 UTC, jliangTT commented
@ttmtrajkovic. Please take a look and see if you are the right person to unblock here. I think developer is waitiing on: 
1. feedback on the PR 
2. issue on debugging PCC [here](https://docs.google.com/document/d/1Ovj0oF-0el4TJxrGRhtn0kFSWvn4Ymk-GDFEAXs7tmc/edit).

2024-03-11 20:54 UTC, jliangTT commented
@bharane-ab @umadevimcw , need your help to full summarize the blocker for you to make forward progress on this PR? Need to be as specific as possible, for example, which reviewer comment, which bug you are running into, what open question you have. 

And please summarize it here.

2024-03-12 05:45 UTC, bharane-ab commented
Hi @jliangTT, Muthu has cherry-picked this commit and created a new branch and a new PR for the typecast from float to int.
Branch name: ma/typecast-second
PR link: https://github.com/tenstorrent-metal/tt-metal/pull/5203

So, the issues we faced are in that PR. Hence, this branch is inactive.
the issue we faced in that branch is documented [here](https://docs.google.com/document/d/1Ovj0oF-0el4TJxrGRhtn0kFSWvn4Ymk-GDFEAXs7tmc/edit)

2024-03-12 06:19 UTC, umadevimcw commented
@jliangTT To avoid conflicts i will close this PR for now. As @bharane-ab mentioned the current work is in another PR

2024-03-12 06:19 UTC, closed without merging