#5246: Add unary math ops to ttnn
tenstorrent/tt-metal pull request #5259
Opened 2024-02-09 18:03 UTC by KalaivaniMCW

Add unary math ops to ttnn
CI test 
Sweep tests: 
[i0.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224807/i0.csv)
[identity.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224809/identity.csv)
[isfinite.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224810/isfinite.csv)
[isinf.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224811/isinf.csv)
[isnan.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224812/isnan.csv)
[isneginf.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224813/isneginf.csv)
[isposinf.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224814/isposinf.csv)
[lgamma.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224815/lgamma.csv)
[log1p.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224816/log1p.csv)
[log2.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224817/log2.csv)
[log10.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224818/log10.csv)
[logical_not_unary.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224819/logical_not_unary.csv)
[logical_noti.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224820/logical_noti.csv)
[logit.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224821/logit.csv)
[move.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224822/move.csv)
[multigammaln.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224823/multigammaln.csv)
[neg.csv](https://github.com/tenstorrent-metal/tt-metal/files/14224824/neg.csv)

2024-02-09 23:32 UTC, arakhmati requested changes
`ttl.tensor.move` was already added as `ttnn.reallocate`. So please remove it.

And we can please rename `ttnn.identity` to `ttnn.clone`?

2024-02-10 01:49 UTC, arakhmati approved these changes

2024-02-10 18:38 UTC, muthutt approved these changes
LGTM

2024-02-10 19:04 UTC, eyonland approved these changes

2024-02-11 00:59 UTC, merged