#5326: Add tensor manip ops to ttnn
tenstorrent/tt-metal pull request #5410
Opened 2024-02-15 11:44 UTC by Aswinmcw

Add tensor manip ops to ttnn
Sweep Test Results:
[full_like.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296286/full_like.csv)
[full.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296287/full.csv)
[maeloss.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296288/maeloss.csv)
[mean_hw.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296290/mean_hw.csv)
[mseloss.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296291/mseloss.csv)
[normalize_global.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296292/normalize_global.csv)
[normalize_hw.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296293/normalize_hw.csv)
[ones.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296294/ones.csv)
[softplus.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296295/softplus.csv)
[std_hw.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296296/std_hw.csv)
[var_hw.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296297/var_hw.csv)
[zeros_like.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296298/zeros_like.csv)
[zeros.csv](https://github.com/tenstorrent-metal/tt-metal/files/14296299/zeros.csv)

2024-02-15 11:58 UTC, Aswinmcw commented
Fast Dispatch Test: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7915488148
Slow Dispatch Test: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7915489277

2024-02-16 03:42 UTC, arakhmati requested changes

2024-02-16 03:42 UTC, arakhmati commented on ttnn/ttnn/operations/others.py
> +def _zeros_like_validate_input_tensors(operation_name, input_tensor, *args, **kwargs):
the newly code should be removed from others.py and moved into creation.py, reduction.py and losses.py

2024-02-16 03:42 UTC, arakhmati commented on tests/ttnn/unit_tests/test_manip.py
> +# SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
this file should be broken down into test_creation.py, test_reduction.py and test_losses.py. And the files should be under tests/ttnn/unit_tests/operations

2024-02-16 15:07 UTC, arakhmati requested changes
I love it! 

But one last thing. Can you please rename `mseloss` to `mse_loss` and `maeloss` to `l1_loss`? We really want to keep our names same as torch

2024-02-17 03:40 UTC, arakhmati approved these changes

2024-02-19 11:41 UTC, merged