Convs in Unet on device
tenstorrent/tt-metal pull request #5482
Opened 2024-02-19 23:18 UTC by tt-nshanker

2024-02-19 23:22 UTC, tt-nshanker commented on tt_eager/tt_lib/fallback_ops/fallback_ops.py
> +        assert False
Added this for local testing to ensure no convs are run on the fallback path. I will remove this later before running CI tests.

2024-02-19 23:22 UTC, tt-nshanker commented on ttnn/ttnn/__init__.py
> +    unpad,
TODO: Need to move this unpad op to __get_item__

2024-02-20 13:31 UTC, boris-drazic approved these changes

2024-02-20 13:31 UTC, boris-drazic commented on models/experimental/functional_stable_diffusion/tt/ttnn_functional_basic_transformer_block.py
> +    # ttnn.dump_device_memory_state(device)
Can you delete comment?

2024-02-20 13:31 UTC, boris-drazic commented on models/experimental/functional_stable_diffusion/tt/ttnn_functional_downsample_2d.py
> +    return input
Can you put these two functions in utility_functions file?

2024-02-20 13:31 UTC, boris-drazic commented on models/experimental/functional_stable_diffusion/tt/ttnn_functional_transformer_2d.py
> +    return input
Can you put these two functions in utility_functions file?

2024-02-20 13:31 UTC, boris-drazic commented on models/experimental/functional_stable_diffusion/tt/ttnn_functional_upsample_nearest_2d.py
> +    up_output = ttnn.upsample(input, scale_factor)
Can you remove printf?

2024-02-20 20:41 UTC, tt-nshanker commented on tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py
> +            deallocate_input=True,
TODO: fix the variable name

2024-02-21 19:36 UTC, arakhmati requested changes

2024-02-21 19:36 UTC, arakhmati commented on ttnn/cpp/ttnn/operations/binary.hpp
> +                    TT_THROW("Bcast: Unsupported dtype argument.");
"ttnn.add: cannot change dtype when broadcasting");"

2024-02-21 19:36 UTC, arakhmati commented on ttnn/ttnn/operations/core.py
> +        * :attr:`layout`: the layout of either ttnn.ROW_MAJOR_LAYOUT or ttnn.TILE_LAYOUT.
add an entry for dtype

2024-02-21 19:46 UTC, arakhmati approved these changes

2024-02-21 20:29 UTC, mywoodstock approved these changes

2024-02-21 20:30 UTC, mywoodstock commented on tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_condition_model.py
> +    assert_with_pcc(torch_output, ttnn_output, pcc=0.80)
I had reduced this, can you revert?

2024-02-22 08:49 UTC, arakhmati requested changes

2024-02-22 08:49 UTC, arakhmati commented on ttnn/ttnn/operations/binary.py
> +        output = ttnn._ttnn.operations.binary.add(input_tensor_a, input_tensor_b, memory_config=memory_config)
Update the C++ function that is overloaded for scalar to take in `dtype` and add the assert there

2024-02-22 20:20 UTC, arakhmati approved these changes

2024-02-22 20:41 UTC, merged