#5483: Add reduction ops to ttnn
tenstorrent/tt-metal pull request #5485
Opened 2024-02-20 13:18 UTC by KalaivaniMCW

Add min max reduction ops to ttnn
CI test link
Sweep tests:

2024-02-23 19:30 UTC, arakhmati requested changes
For the ttnn reduction ops, remove `keepdim` argument and always keep the same rank as the original tensor

2024-02-26 17:13 UTC, eyonland approved these changes

2024-02-26 17:22 UTC, arakhmati approved these changes

2024-02-27 10:09 UTC, KalaivaniMCW commented
> For the ttnn reduction ops, remove `keepdim` argument and always keep the same rank as the original tensor

I have made the necessary changes

2024-02-27 10:10 UTC, merged