#5509: Add ternary ops to ttnn
tenstorrent/tt-metal pull request #5515
Opened 2024-02-21 08:19 UTC by Aswinmcw

Add support for ternary ops to ttnn
Sweep Test Results:
[addcdiv.csv](https://github.com/tenstorrent-metal/tt-metal/files/14356394/addcdiv.csv)
[addcmul.csv](https://github.com/tenstorrent-metal/tt-metal/files/14356395/addcmul.csv)
[arange.csv](https://github.com/tenstorrent-metal/tt-metal/files/14356396/arange.csv)
[mac.csv](https://github.com/tenstorrent-metal/tt-metal/files/14356399/mac.csv)
[where.csv](https://github.com/tenstorrent-metal/tt-metal/files/14356400/where.csv)

2024-02-21 08:21 UTC, Aswinmcw commented
Slow Dispatch Test: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7985990013
Fast Dispatch Test: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7985988863

2024-02-21 19:45 UTC, arakhmati requested changes
`arange` needs to be moved to `creation.py`. And it must have a mandatory `device` argument and only run on device

2024-02-21 19:46 UTC, arakhmati requested changes

2024-02-21 19:46 UTC, arakhmati commented on ttnn/ttnn/operations/ternary.py
> +        ttnn.validate_input_tensor(
There must be ttnn.validate_input_tensor for all 3 tensors

2024-02-22 04:26 UTC, Aswinmcw commented
Modified the following:
Moved arange from ternary to creation
Added device argument for arange op
Added tensor validation condition for all inputs

2024-02-22 08:46 UTC, arakhmati approved these changes

2024-02-22 09:18 UTC, merged