#5517: Add activation ops to ttnn
tenstorrent/tt-metal pull request #5526
Opened 2024-02-21 19:00 UTC by KalaivaniMCW

Add activation ops to ttnn
CI Test link
Sweep tests:

2024-02-21 19:43 UTC, arakhmati requested changes

2024-02-21 19:43 UTC, arakhmati commented on docs/source/ttnn/api.rst
> +   ttnn/swiglu
Put them in alphabetical order please

2024-02-22 03:30 UTC, KalaivaniMCW commented on docs/source/ttnn/api.rst
> +   ttnn/swiglu
I have made the requested changes.

2024-02-22 08:45 UTC, arakhmati approved these changes

2024-02-22 12:06 UTC, merged