#5394: Add functional version of Mamba architecture
tenstorrent/tt-metal pull request #5948
Opened 2024-03-04 06:32 UTC by kpaigwar

2024-03-04 17:31 UTC, arakhmati requested changes
If you want to put it under `models/demos`, then it has to be re-written using `ttnn`. Without any `import tt_lib`.

If you don't want to update the model right now to use `ttnn`, then please put it under `models/experimental`

2024-03-04 17:32 UTC, eyonland requested changes
Any new models going into models/demo needs to have run_performance.sh updated where the run_perf_models() is updated as well as the run_device_perf_models()

2024-03-04 21:12 UTC, kpaigwar commented
Right now, there is no immediate plan to convert it using ttnn. I will move it to models/experimental. @eyonland this is our functional version, not optimized for performance. Does models in experimental also requires run_performance.sh?

2024-03-05 12:42 UTC, esmalTT commented on models/demos/mamba/README.md
> +python demo/demo.py "What is the capital of France?" "What is the capital of Germany?" --model cpu
```suggestion
python demo/demo.py "What is the capital of France?" "What is the capital of Germany?" --model wh
```

2024-03-05 12:42 UTC, esmalTT commented on models/demos/mamba/tt/model_config.py
> +# SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
We can probably delete this since it is not used and is just copied from elsewhere.

2024-03-06 22:12 UTC, kpaigwar reviewed
moved to experimental

2024-03-06 22:46 UTC, eyonland approved these changes

2024-03-07 11:49 UTC, esmalTT commented on models/experimental/mamba/reference/tokenizer.ipynb
Should we delete this?

2024-03-07 13:39 UTC, boris-drazic approved these changes

2024-03-11 19:44 UTC, arakhmati approved these changes

2024-03-11 19:59 UTC, merged