Npetrovic/ttnn bin ops
tenstorrent/tt-metal pull request #6045
Opened 2024-03-05 22:19 UTC by npetrovic-tenstorrent

Added sweeps and unit tests for:
- ldexp
- logaddexp
- logaddexp2
- pow
- logical and/or/xor

2024-03-05 22:57 UTC, eyonland requested changes
Would you help me understand why we are adding non working unit tests?

2024-03-06 00:08 UTC, npetrovic-tenstorrent commented
> Would you help me understand why we are adding non working unit tests?

These unit tests are expected the fail with LOW PCC error, but still can be executed, so they can be later assigned to corresponding issues related to these operations. Therefore, someone working on the operation fix regarding PCC would be able to focus on the failing test cases which are here isolated, without necessarily running sweeps for all cases which are even passing.

2024-03-07 12:30 UTC, nemanjagrujic approved these changes

2024-03-07 15:39 UTC, boris-drazic approved these changes

2024-03-11 21:22 UTC, arakhmati approved these changes

2024-03-14 14:37 UTC, merged