#5924: Enable unet on wormhole_b0 changes
tenstorrent/tt-metal pull request #6198
Opened 2024-03-08 16:04 UTC by tapspatel

2024-03-09 20:20 UTC, tapspatel commented
Issue: https://github.com/tenstorrent-metal/tt-metal/issues/5924#issuecomment-1981469484
Post-commit pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8216981925

2024-03-09 21:47 UTC, mywoodstock approved these changes

2024-03-09 21:47 UTC, mywoodstock commented on tests/ttnn/unit_tests/operations/test_conv2d.py
> +    breakpoint()
Intended?

2024-03-09 21:47 UTC, mywoodstock commented on tests/ttnn/unit_tests/operations/test_conv2d.py
> +    [ttnn.bfloat8_b],
Testing for bfloat16 weights?

2024-03-11 14:44 UTC, tapspatel commented on ttnn/ttnn/operations/others.py
> +    max_grid_size = (9, 12) if os.getenv("ARCH_NAME", "grayskull") == "grayskull" else (8, 8)  ## (y, x)
I don't have access to the device pointer in this part of the stack trace

2024-03-11 14:44 UTC, tapspatel commented on tests/ttnn/unit_tests/operations/test_conv2d.py
> +    breakpoint()
removed

2024-03-11 14:44 UTC, tapspatel commented on tests/ttnn/unit_tests/operations/test_conv2d.py
> +    [ttnn.bfloat8_b],
added

2024-03-11 16:05 UTC, eyonland commented on ttnn/ttnn/operations/others.py
> +    max_grid_size = (9, 12) if os.getenv("ARCH_NAME", "grayskull") == "grayskull" else (8, 8)  ## (y, x)
@cfjchu , should this information be coming from your Multi Device data structures?

2024-03-11 16:07 UTC, tt-nshanker approved these changes

2024-03-12 17:11 UTC, cfjchu commented on ttnn/ttnn/operations/others.py
> +    max_grid_size = (9, 12) if os.getenv("ARCH_NAME", "grayskull") == "grayskull" else (8, 8)  ## (y, x)
This isn't specific to multi-device, but that's a great point, users shouldn't have to infer grid-size like this. I'll add some changes to make this information about core-grid more readily available.

2024-03-12 17:11 UTC, cfjchu approved these changes

2024-03-12 17:52 UTC, tapspatel commented on ttnn/ttnn/operations/others.py
> +    max_grid_size = (9, 12) if os.getenv("ARCH_NAME", "grayskull") == "grayskull" else (8, 8)  ## (y, x)
Filed an issue for that support: https://github.com/tenstorrent-metal/tt-metal/issues/6308

2024-03-12 18:23 UTC, arakhmati requested changes

2024-03-12 18:23 UTC, arakhmati commented on ttnn/ttnn/operations/others.py
> +    max_grid_size = (9, 12) if os.getenv("ARCH_NAME", "grayskull") == "grayskull" else (8, 8)  ## (y, x)
@tapspatel you can pass in `device` into `_get_upsample_num_shards`and `_get_upsample_shard_grid_from_num_shards` from `input_tensor.device()`

2024-03-13 16:24 UTC, arakhmati approved these changes

2024-03-13 16:25 UTC, merged