#6541: Add optional tensor support for bmm
tenstorrent/tt-metal pull request #6543
Opened 2024-03-19 12:01 UTC by Aswinmcw

Add optional output tensor support for batch matmul

2024-03-21 06:23 UTC, eyonland requested changes
Please add the reference back to the primary ticket in the description.

2024-03-21 06:24 UTC, eyonland commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_bmm.py
>          .cpu()
Please add a test showing that the optional output tensor does not even need to be provided.  And one that shows that the optional output tensor was provided and returned back by the op.

2024-03-21 06:25 UTC, eyonland requested changes
Please add a test showing that the optional output tensor does not even need to be provided.  And one that shows that the optional output tensor was provided and returned back by the op.

2024-03-25 18:02 UTC, eyonland requested changes
Every test needs to show that the op returned back the optional output tensor it was given.

2024-03-25 18:02 UTC, eyonland commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_bmm.py
> +            ttl.operations.primary.moreh_bmm(tt_input, tt_mat2, tt_optional_tensor)
Please add tt_out = ttl.operations.primary.moreh_bmm(tt_input, tt_mat2, tt_optional_tensor)

2024-04-05 03:38 UTC, Aswinmcw commented
Closing this PR as Moreh team will implement

2024-04-05 03:38 UTC, closed without merging