#6591: Add optional output tensor for moreh sum forward and backward
tenstorrent/tt-metal pull request #6596
Opened 2024-03-20 13:50 UTC by bharane-ab

2024-03-21 06:33 UTC, eyonland requested changes
Please add a test showing that the optional output tensor does not even need to be provided.  And one that shows that the optional output tensor was provided and returned back by the op.

2024-03-25 18:22 UTC, eyonland requested changes

2024-03-25 18:22 UTC, eyonland commented on tt_eager/tt_dnn/op_library/moreh_sum/moreh_sum_op.cpp
>      const Tensor& input,
I don't follow why this is being change to a vector?

2024-03-25 18:22 UTC, eyonland commented on tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_sum.py
> +        tt_output_cpu = ttl.operations.primary.moreh_sum(tt_input, tt_output, dims=dims, output_tensor=optional_output)
Is this really a tensor on cpu?

2024-04-03 05:22 UTC, bharane-ab commented
Moreh team is addressing the issue

2024-04-03 05:22 UTC, closed without merging