#5785: Watcher ringbuffer implementation
tenstorrent/tt-metal pull request #6652
Opened 2024-03-21 18:39 UTC by tt-dma

Passing CI: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8379095588

Note that CI currently has n300 gtests disabled, I've run all watcher tests locally on a n300 bm and they pass.

2024-03-21 22:15 UTC, pgkeller requested changes

2024-03-21 22:15 UTC, pgkeller commented on docs/source/tools/watcher.rst
> +rung buffer, and the resulting log is shown below.
typo

2024-03-21 22:15 UTC, pgkeller commented on docs/source/tools/watcher.rst
> +mat result in undefined behaviour.
typo, though don't qualify this w/ may, just say is undefined behavior

2024-03-21 22:15 UTC, pgkeller commented on docs/source/tools/watcher.rst
> +    Core (x=1,y=1):    R,R,R,R,R rmsg:D0G|BNT smsg:GGGG debug_ring_buffer(latest_written_idx=8)=[0x00000021,0x00000021,0x00000022,0x00000023,0x00000024,0x00000025,0x00000026,0x00000027,0x00000028,0x0
let's split these into rows of 8

2024-03-21 22:15 UTC, pgkeller commented on docs/source/tools/watcher.rst
> +            RING_BUFFER_PUSH(idx+1);
let's qualify the name w/ either WATCHER or DEBUG or some such.  Too many ring buffers...

2024-03-21 22:15 UTC, pgkeller commented on tt_metal/hostdevcommon/debug_ring_buffer_common.h
> +// We use a magic value to initialize the rung buffer to, so that we can avoid printing it to the
rung/ring

2024-03-21 22:15 UTC, pgkeller commented on tt_metal/hostdevcommon/debug_ring_buffer_common.h
> +// watcher og if no ring buffer data has been written.
typo

2024-03-21 22:15 UTC, pgkeller commented on tt_metal/hostdevcommon/debug_ring_buffer_common.h
> +    uint32_t current_ptr;
can you set current_ptr to -1 rather than using the magic value?  then writing is *(++current_ptr) = xyz w/ a wrap check before

2024-03-21 22:15 UTC, pgkeller commented on tt_metal/hw/inc/debug/ring_buffer.h
> +    *current_ptr  = (curr_idx + 1) % RING_BUFFER_ELEMENTS;
test for wrap by >= rather than mod (no HW support for mod, so turns into a fn call)

2024-03-22 03:30 UTC, tt-dma commented
All comments should be addressed in latest commit. Ran all n300 watcher tests locally and passing CI: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8384580652

2024-03-22 13:42 UTC, pgkeller approved these changes

2024-03-22 18:50 UTC, aliuTT approved these changes

2024-03-22 18:50 UTC, aliuTT commented on tt_metal/hw/inc/wormhole/eth_l1_address_map.h
> +  static constexpr std::int32_t ERISC_RING_BUFFER_ADDR = COMMAND_Q_BASE - 128;
I changed this on main to start from an address, and increment up

2024-03-22 20:03 UTC, merged