#6654: Add perf tests for ttnn ResNet50
tenstorrent/tt-metal pull request #6673
Opened 2024-03-22 06:45 UTC by eyonland

2024-03-22 22:13 UTC, mywoodstock approved these changes

2024-03-22 22:17 UTC, tt-rkim requested changes

2024-03-22 22:17 UTC, tt-rkim commented on tests/scripts/run_performance.sh
> +#    echo "There are no CNN tests for Javelin yet specified. Arch $tt_arch requested"
Please delete this line - we need to stop the practice of commenting out things we don't need rather than deleting them.

2024-03-22 22:17 UTC, tt-rkim commented on tt_metal/third_party/tt_llk_grayskull
Do you need to rebase onto latest main?

2024-03-22 22:28 UTC, eyonland commented on tt_metal/third_party/tt_llk_grayskull
yes

2024-03-22 22:31 UTC, tt-rkim commented
Give the device perf pipeline a run and I'll be good to go 👍

2024-03-22 22:33 UTC, cfjchu approved these changes

2024-03-25 23:00 UTC, eyonland commented
@tt-rkim , I backed out of making an update to run_perf_models_cnn_javelin()
Are you able to approve?

2024-03-26 11:15 UTC, boris-drazic approved these changes

2024-03-26 13:41 UTC, tt-rkim approved these changes

2024-03-26 14:32 UTC, merged