#6443: Update reciprocal backward
tenstorrent/tt-metal pull request #6910
Opened 2024-03-29 08:31 UTC by VirdhatchaniKN

#6443  Updated logic for backward reciprocal op and updated few backward test files

Issues addressed : 
- **Reciprocal** : 
   - Updated logic to get nan / inf / -inf based on input. 
   - Checked PCC and All close - both passes
   - Updated test file to check for range ( -100, 100 )
- **Test file Updated for the following ops** : 
   - Rsub
   - Unary mul
   - Mul
   - Unary remainder
   - Unary fmod
   - Squared difference
   - Reciprocal

All post-commit tests - [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8478968970)

2024-03-29 11:54 UTC, eyonland requested changes
Please add a test where the input has zeros for tt_lib.tensor.reciprocal_bw

2024-04-01 08:34 UTC, VirdhatchaniKN commented
> Please add a test where the input has zeros for tt_lib.tensor.reciprocal_bw

Sure. I have now updated the test file @eyonland 
All post-commit tests - [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8505884938)

2024-04-03 14:24 UTC, eyonland approved these changes

2024-04-05 01:55 UTC, VirdhatchaniKN commented
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8563540381 - Passed

2024-04-05 01:55 UTC, merged