#515: Add profiler collection side regression tests
tenstorrent/tt-metal pull request #696
Opened 2023-05-17 17:01 UTC by mo-tenstorrent

- Profiler python library uses repo's python requirements
- Profiler test scripts were moved under tests dir
- Small bugfix on trisc main FW markers
- Added profiler regression to scheduled CI regression runs

2023-05-18 00:16 UTC, DrJessop requested changes

2023-05-18 15:39 UTC, tt-rkim requested changes

2023-05-19 14:14 UTC, DrJessop approved these changes
Looks good to me.

2023-05-19 15:26 UTC, tt-rkim approved these changes

2023-05-19 15:41 UTC, merged