Nshanker/refactor resnet50 ttnn
tenstorrent/tt-metal pull request #7028
Opened 2024-04-02 22:00 UTC by tt-nshanker

2024-04-02 22:24 UTC, cfjchu commented on ttnn/ttnn/operations/binary.py
> +    out_in_place: Optional[bool] = False,
Could we change this to `in_place` and add documentation for this function parameter?

2024-04-03 13:54 UTC, eyonland requested changes
Can we replace https://github.com/tenstorrent-metal/tt-metal/blob/main/models/experimental/resnet/tt/ttnn_functional_resnet.py with this version of resnet50 and update
https://github.com/tenstorrent-metal/tt-metal/blob/main/tests/ttnn/integration_tests/resnet/test_performance.py
?

2024-04-03 20:03 UTC, tt-nshanker commented
> Can we replace https://github.com/tenstorrent-metal/tt-metal/blob/main/models/experimental/resnet/tt/ttnn_functional_resnet.py with this version of resnet50 and update https://github.com/tenstorrent-metal/tt-metal/blob/main/tests/ttnn/integration_tests/resnet/test_performance.py ?

I haven't added WH support yet. I will replace the old version with this once WH is ready too and also update test_performance.py

2024-04-05 21:42 UTC, arakhmati requested changes

2024-04-05 21:42 UTC, arakhmati commented on ttnn/ttnn/operations/binary.py
> +    in_place: Optional[bool] = False,
We already have an in-place version. With the underscore at the back.use that and don't modify this

2024-04-06 01:16 UTC, cfjchu approved these changes

2024-04-06 04:05 UTC, arakhmati approved these changes

2024-04-08 14:39 UTC, eyonland approved these changes

2024-04-08 18:29 UTC, merged