Falcon40b prefill bringup
tenstorrent/tt-metal pull request #7059
Opened 2024-04-03 11:35 UTC by johanna-rock-tt

Adds support for falcon40b prefill for variable sequences lengths up to S=2048.
- Uses separate fwd methods for sharded decode (unchanged) and prefill
- Prefill is mostly DRAM interleaved, exception is layernorm which is block sharded for functional reasons

**PCC**
1 layer S=128 and S=2048: 0.99 / 0.99 / 0.99
60 layer S=128: 0.92 / 0.98 / 0.94

**Performance**
60 layer S=128: 1173 tok/s
60 layer S=2048: 1961 tok/s

2024-04-03 13:12 UTC, boris-drazic approved these changes

2024-04-05 15:12 UTC, TT-BrianLiu requested changes
Can we try to merge with the existing falcon40b code? Also, squash the commits as much as possible.

2024-04-09 14:42 UTC, johanna-rock-tt commented
I applied my changes to the existing models/demos/falcon40b code. Still need to run all tests.

2024-04-10 21:52 UTC, TT-BrianLiu requested changes
We should leave program caching in the tests. CI tests currently use program_cache. If we remove, we are testing less in CI

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/demo/demo.py
> +    #     device.enable_program_cache()
Do we have to turn off program cache? Can we enable and leave what is working on `main`?

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/demo/demo.py
> +    #     device.disable_and_clear_program_cache()
Do we have to turn off program cache?

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/demo/demo.py
> +    # use_program_cache, # TODO: remove workaround for avoiding PCC issues when fixed
Do we have to turn off program cache? Also, if we have this, we don't need the manual enable in the demo code.

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_attention.py
> +    # use_program_cache, # TODO: remove workaround for avoiding PCC issues when fixed
Don't remove.

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_causallm.py
>  ):
Don't remove.

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_decoder.py
> +    # use_program_cache, # TODO: remove workaround for avoiding PCC issues when fixed
Don't remove

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_end_to_end.py
>  ):
Don't remove

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_mlp.py
>  ):
Don't remove

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_falcon_model.py
>  ):
Don't remove

2024-04-10 21:52 UTC, TT-BrianLiu commented on models/demos/falcon40b/tests/test_perf_falcon.py
> -    use_program_cache,
Don't remove

2024-04-11 08:51 UTC, johanna-rock-tt commented
> We should leave program caching in the tests. CI tests currently use program_cache. If we remove, we are testing less in CI

Program cache enabled gives very low PCC results and also garbage outputs for the demo. I think it's not an issue for decode but it is for prefill. For longer sequence lengths (S=2048) this results in a PCC of 0.49 for one layer, for shorter ones it's also lower PCC but not that dramatic (0.8-0.9) but even for S=32 the demo output is garbage with program cache enabled.

See [this issue.](https://github.com/tenstorrent-metal/tt-metal/issues/7159)

Suggestion: I can add another test where program cache is enabled to run the decode tests in CI with program cache but I'd keep the tests where it is temporarily disabled - otherwise we can't add prefill to CI at all and also everybody trying out the demo and/or the tests is going to see bad outputs.

2024-04-12 14:56 UTC, TT-BrianLiu approved these changes

2024-04-12 16:54 UTC, tt-rkim approved these changes

2024-04-12 17:03 UTC, cfjchu approved these changes

2024-04-13 10:23 UTC, merged