#7108: Accuracy enhancement for sigmoid using composite structures
tenstorrent/tt-metal pull request #7109
Opened 2024-04-04 14:05 UTC by ruthreshx

Since ckernel returns the low accuracy for the sigmoid, hence we implemented the sigmoid accurate using the composite structure.

2024-04-05 14:08 UTC, tt-aho requested changes
If all the ops being used are unary ops, instead of composite structure I would suggest adding it in `tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.hpp` similar to `log_sigmoid` which specifies a chain of unary ops to run in a single operation.

2024-04-12 04:40 UTC, ruthreshx commented
Hi @tt-aho ,
Please find the updated patch, kindly review thanks!

2024-04-12 18:25 UTC, tt-aho approved these changes

2024-04-15 16:58 UTC, arakhmati approved these changes

2024-04-16 06:10 UTC, merged