#7050: Add yolov4 downsample4 and downsample5 sub-modules
tenstorrent/tt-metal pull request #7112
Opened 2024-04-04 14:51 UTC by saichandax

This is a draft PR for the downsample4 and downsample5 sub-modules implementation of yolov4 and unit test.

ResBlock has been replaced with direct layer implementation instead of Separate class.
Once the sub-module is available from https://github.com/tenstorrent-metal/tt-metal/issues/7051, we will integrate resBlock into Downsample4 and Downsample5 sub-modules.

2024-04-10 23:42 UTC, dvartaniansTT requested changes
Similar to the rest of the PR requests, please generate the torch graph and compare it to the original reference torch graph as well as the auto generated ttnn graph and attach them here. 

example code to generate the torch graph:
`## Example usage
model = DownSample2()

input_tensor = torch.randn(1, 3, 320, 320) # Batch size of 1, 3 channels (RGB), 320x320 input - replace this line with the proper input size for your module
output_tensor = model(input_tensor)

model_graph = draw_graph(
model,
input_size=(1, 3, 320, 320),
dtypes=[torch.float32],
expand_nested=True,
graph_name="DownSample2",
depth=100,
directory=".",
)
model_graph.visual_graph.render(format="pdf")`

original reference graph: 
[REPO_320x320_YOLOv4_PublicRepo.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14938896/REPO_320x320_YOLOv4_PublicRepo.gv.pdf)

2024-04-11 09:49 UTC, ankitmcw commented
Original Downsample 5: [DownSample5.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14944411/DownSample5.gv.pdf)
Reference Downsample 5: ![model_graph](https://github.com/tenstorrent-metal/tt-metal/assets/164470141/3367f8e0-6444-4938-a121-c8aa3b22084b)
TTNN Downsample 5: ![downsample5](https://github.com/tenstorrent-metal/tt-metal/assets/164470141/bb2201eb-e832-4f97-ba73-c0af81752b91)

2024-04-11 15:08 UTC, ankitmcw commented
Original Downsample 4: 
[DownSample4.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14947960/DownSample4.gv.pdf)
Reference Downsample 4: 
![model_graph](https://github.com/tenstorrent-metal/tt-metal/assets/164470141/92287db9-40bb-4bdd-a1aa-4eca5514b4e6)
TTNN Downsample 4: 
![downsample4](https://github.com/tenstorrent-metal/tt-metal/assets/164470141/61e717c1-6fb7-4f77-b428-5035f6e63d34)

2024-04-16 23:21 UTC, dvartaniansTT requested changes
for the most part LGTM. Minor changes needed. please seem my comments

2024-04-16 23:21 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_downsample4.py
> +def test_downsample4(reset_seeds):
This is the expected way for the unit tests: 

`def test_downsample4(device, reset_seeds):`
remove this line `device = ttnn.open_device(device_id=2)`

I know you are sharing the same machine and using different devices/device IDs. That' ok but for the PR please make my suggested changes.

2024-04-16 23:21 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_downsample4.py
> +    ttnn.close_device(device)
you would also need to remove this line. `ttnn.close_device(device)`

2024-04-16 23:21 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_downsample5.py
> +    ttnn.close_device(device)
please apply the same changes I suggested for DS4 here

2024-04-16 23:21 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_downsample5.py
> +    device = ttnn.open_device(device_id=2)
please apply my suggested changed for DS4 here as well.

2024-04-16 23:58 UTC, dvartaniansTT commented
please also follow these for testing:

cd $TT_METAL_HOME
scripts/build_scripts/build_with_profiler_opt.sh
./tt_metal/tools/profiler/profile_this.py -n DS1 -c "pytest tests/ttnn/integration_tests/yolov4/test_ttnn_downsample1.py "

2024-04-17 01:58 UTC, dvartaniansTT commented
> Original Downsample 5: [DownSample5.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14944411/DownSample5.gv.pdf) Reference Downsample 5: ![model_graph](https://private-user-images.githubusercontent.com/164470141/321584993-3367f8e0-6444-4938-a121-c8aa3b22084b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkzNDUsIm5iZiI6MTcxMzMxOTA0NSwicGF0aCI6Ii8xNjQ0NzAxNDEvMzIxNTg0OTkzLTMzNjdmOGUwLTY0NDQtNDkzOC1hMTIxLWM4YWEzYjIyMDg0Yi5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwMTU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWE2YzE4NWU2MDhjMjg0MjMzYmJmNDdjODRhZjhjMDg2NTA1MTQyOGI5ZWRlMzliOTMwNWYxMWQ0ZjMxOGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9RVCyPJo9BmFMFV-AK5UTCbSZgNvWj2k7xUHNU3cbEo) TTNN Downsample 5: ![downsample5](https://private-user-images.githubusercontent.com/164470141/321584980-bb2201eb-e832-4f97-ba73-c0af81752b91.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkzNDUsIm5iZiI6MTcxMzMxOTA0NSwicGF0aCI6Ii8xNjQ0NzAxNDEvMzIxNTg0OTgwLWJiMjIwMWViLWU4MzItNGY5Ny1iYTczLWMwYWY4MTc1MmI5MS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwMTU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWE0YTAxNGUxNmYxMjRlZWE5M2FkZWUyMWE2YzdmZGNlYTI0ZGRiNzAzY2JkZTljOWU2ZjA5ZTgyOWNjNmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T3xy95nERstWgYmsGHz7beCx0R1ckm4h94-bwnjFHkE)

How come the generated graph shows mish activations while the implementation is with ReLU?

2024-04-17 11:38 UTC, ankitmcw commented
Profiler of downsample4:  
[ops_perf_results_DownSample4_2024_04_17_09_34_20.csv](https://github.com/tenstorrent/tt-metal/files/15010252/ops_perf_results_DownSample4_2024_04_17_09_34_20.csv)

Profiler of downsample5: 
[ops_perf_results_DownSample5_2024_04_17_11_35_53.csv](https://github.com/tenstorrent/tt-metal/files/15010254/ops_perf_results_DownSample5_2024_04_17_11_35_53.csv)

2024-04-18 17:49 UTC, dvartaniansTT approved these changes

2024-04-23 17:33 UTC, arakhmati approved these changes

2024-04-25 04:39 UTC, saichandax commented
All post commit : [passed](https://github.com/tenstorrent/tt-metal/actions/runs/8823127736)
Nightly fast dispatch: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/8823126343)

2024-05-19 20:45 UTC, closed without merging