#7051: resblock ttnn submodule
tenstorrent/tt-metal pull request #7121
Opened 2024-04-04 17:39 UTC by saichandax

This is a draft PR for the resBlock sub-module implementation of yolov4 and unit test.

2024-04-04 17:42 UTC, saichandax commented
spdx license checks will be added to the files. Kindly ignore.

2024-04-05 19:57 UTC, eyonland approved these changes

2024-04-10 23:43 UTC, dvartaniansTT reviewed
Similar to the rest of the PR requests, please generate the torch graph and compare it to the original reference torch graph as well as the auto generated ttnn graph and attach them here.

example code to generate the torch graph:
`## Example usage
model = DownSample2()

input_tensor = torch.randn(1, 3, 320, 320) # Batch size of 1, 3 channels (RGB), 320x320 input - replace this line with the proper input size for your module
output_tensor = model(input_tensor)

model_graph = draw_graph(
model,
input_size=(1, 3, 320, 320),
dtypes=[torch.float32],
expand_nested=True,
graph_name="DownSample2",
depth=100,
directory=".",
)
model_graph.visual_graph.render(format="pdf")`

original reference graph:
[REPO_320x320_YOLOv4_PublicRepo.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14938896/REPO_320x320_YOLOv4_PublicRepo.gv.pdf)

2024-04-10 23:44 UTC, dvartaniansTT requested changes
Similar to the rest of the PR requests, please generate the torch graph and compare it to the original reference torch graph as well as the auto generated ttnn graph and attach them here.

example code to generate the torch graph:
`## Example usage
model = DownSample2()

input_tensor = torch.randn(1, 3, 320, 320) # Batch size of 1, 3 channels (RGB), 320x320 input - replace this line with the proper input size for your module
output_tensor = model(input_tensor)

model_graph = draw_graph(
model,
input_size=(1, 3, 320, 320),
dtypes=[torch.float32],
expand_nested=True,
graph_name="DownSample2",
depth=100,
directory=".",
)
model_graph.visual_graph.render(format="pdf")`

original reference graph:
[REPO_320x320_YOLOv4_PublicRepo.gv.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14938896/REPO_320x320_YOLOv4_PublicRepo.gv.pdf)

2024-04-11 10:46 UTC, keerthana-r-mcw commented
![resblock](https://github.com/tenstorrent-metal/tt-metal/assets/164333733/e3d71a3d-fc1a-4ae3-99d7-f9eebae14e7d)
![resblock_ttnn](https://github.com/tenstorrent-metal/tt-metal/assets/164333733/2f602204-9819-4390-94e4-bef8f8bb0100)

2024-04-16 22:59 UTC, dvartaniansTT commented
please generate the torch graph of your torch implementation and compare to the original graph. 
here is the code sample to do so [sample code](https://github.com/tenstorrent/tt-metal/blob/a34b544b7284d8126e9a5b47304fe1ad0ba56a39/tests/ttnn/integration_tests/yolov4/test_ttnn_downsample1.py#L190)

2024-04-16 23:29 UTC, dvartaniansTT commented
> ![resblock](https://private-user-images.githubusercontent.com/164333733/321601318-e3d71a3d-fc1a-4ae3-99d7-f9eebae14e7d.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTA0MTQsIm5iZiI6MTcxMzMxMDExNCwicGF0aCI6Ii8xNjQzMzM3MzMvMzIxNjAxMzE4LWUzZDcxYTNkLWZjMWEtNGFlMy05OWQ3LWY5ZWViYWUxNGU3ZC5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQyMzI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDE1MDc2YTNlZTViYjQzOTIyYWExMmJlN2U1NDkxOGQyZTc3YzJjZjBiOGMxMDIzNDg5ZTcyZDlhMGIzNWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.azqAuKklG0UqdRlmuHBbWMv21xsu4kqK6lzoQhUMpw8) ![resblock_ttnn](https://private-user-images.githubusercontent.com/164333733/321601326-2f602204-9819-4390-94e4-bef8f8bb0100.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTA0MTQsIm5iZiI6MTcxMzMxMDExNCwicGF0aCI6Ii8xNjQzMzM3MzMvMzIxNjAxMzI2LTJmNjAyMjA0LTk4MTktNDM5MC05NGU0LWJlZjhmOGJiMDEwMC5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQyMzI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWExNTQ3MTc4ZDk3Y2M5NDI2MGE4NzVmOTk5ZDQzNjk3Yzg5YWNkOTIzNWUxYmRiNTc3YmU5NGMzOGY1OTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TY008eUh6yZ--cCFj8zzegMg74MfTCddWmBEXWARw8A)

pls add the torch graph as well. torch graph of your implementation

2024-04-16 23:31 UTC, dvartaniansTT requested changes

2024-04-16 23:31 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_resblock.py
> +    ttnn.close_device(device)
remove this line: `ttnn.close_device(device)`

2024-04-16 23:31 UTC, dvartaniansTT commented on tests/ttnn/integration_tests/yolov4/test_ttnn_resblock.py
> +def test_resblock(reset_seeds):
`def test_resblock(device, reset_seeds):`
and remove`device_id = 0`

2024-04-17 06:58 UTC, keerthana-r-mcw commented
[resblock_pytoch.gv.pdf](https://github.com/tenstorrent/tt-metal/files/15007095/resblock_pytoch.gv.pdf)

2024-04-18 17:49 UTC, dvartaniansTT approved these changes

2024-04-25 03:52 UTC, saichandax commented
Nightly fast dispatch: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/8822603139)
All post commit: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/8822593165/job/24223113440)

2024-05-09 03:05 UTC, saichandax commented
post commit: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/9007682768)
nightly fast dispatch: [failed](https://github.com/tenstorrent/tt-metal/actions/runs/9007680687)

2024-05-09 22:27 UTC, saichandax commented
post commit: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/9023890240)
nightly fast dispatch: [passed](https://github.com/tenstorrent/tt-metal/actions/runs/9023878276)

2024-05-09 22:33 UTC, merged