#516: T3000 profiler tests
tenstorrent/tt-metal pull request #7210
Opened 2024-04-08 17:38 UTC by mo-tenstorrent

Adding T3K tests to profiler regression.

2024-04-08 18:00 UTC, mo-tenstorrent commented
Passing profiler regression https://github.com/tenstorrent-metal/tt-metal/actions/runs/8604440157/job/23578556475

2024-04-09 15:14 UTC, tt-rkim requested changes

2024-04-09 15:14 UTC, tt-rkim commented on tests/scripts/run_profiler_regressions.sh
> +    run_addtional_T3000_test
spelling

2024-04-09 15:14 UTC, tt-rkim commented on tests/scripts/run_profiler_regressions.sh
> +    run_addtional_T3000_test
sorry lol but bruh

2024-04-12 18:44 UTC, tt-rkim approved these changes

2024-04-15 13:19 UTC, merged