#7201: Add support for unary ne
tenstorrent/tt-metal pull request #7234
Opened 2024-04-09 10:19 UTC by VirdhatchaniKN

Add support for Unary Not equal ( TTNN migration included)
All post-commit tests : [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8614084124)

2024-04-11 17:09 UTC, eyonland approved these changes

2024-04-15 13:51 UTC, VirdhatchaniKN commented
Test results : 
File : `tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py`
<img width="1252" alt="Screenshot 2024-04-15 at 7 11 13 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/04eb3f9b-a798-4df8-a7a5-62c26dc90757">

File : `tests/ttnn/unit_tests/operations/test_relational.py`
<img width="695" alt="Screenshot 2024-04-15 at 7 14 02 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/35deef88-f7c3-497c-9656-4a7036d1bf66">

2024-04-15 14:19 UTC, tt-aho requested changes

2024-04-15 14:19 UTC, tt-aho commented on tt_metal/include/compute_kernel_api.h
> + * | param0          | The value the output is if the input is greater than 0                     | uint32_t |                                                       | True     |
Fix description of param0

2024-04-15 14:19 UTC, tt-aho commented on tt_metal/include/compute_kernel_api.h
> + * Performs element-wise computation of:  result = 0 if x!=value , where x is each element of a tile
First comment says output is 1 if x != value,
next comment says result = 0 if x!=value

2024-04-16 13:43 UTC, rtawfik01 approved these changes

2024-04-16 15:05 UTC, arakhmati requested changes
What is the difference between the new op and `tt_lib.tensor.ne`?

2024-04-17 07:55 UTC, VirdhatchaniKN commented
> What is the difference between the new op and `tt_lib.tensor.ne`?

`ne` takes in two tensors as input and `unary_ne` takes in a tensor and scalar as input.

2024-04-17 16:19 UTC, tt-aho approved these changes

2024-04-18 10:11 UTC, VirdhatchaniKN commented
TTNN Changes removed

- All post-commit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8734935584) - PASSED
- Fast Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8734936541) - PASSED
- Slow Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8734937638) - PASSED

2024-04-18 14:46 UTC, arakhmati approved these changes

2024-04-22 16:42 UTC, mywoodstock approved these changes

2024-04-24 08:22 UTC, VirdhatchaniKN commented
- All post-commit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8812832050) - PASSED
- Fast Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8812833621) - PASSED
- Slow Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8812835205) - PASSED

2024-04-24 08:22 UTC, merged