#7235: Add support for unary GT and LT
tenstorrent/tt-metal pull request #7261
Opened 2024-04-09 19:12 UTC by bharane-ab

2024-04-11 17:13 UTC, eyonland requested changes
You do not have any description in https://github.com/tenstorrent-metal/tt-metal/issues/7235 or here that references the primary GH issue that is being worked on.
Also, there isn't a single test on these changes.

2024-04-12 04:03 UTC, bharane-ab commented
> You do not have any description in #7235 or here that references the primary GH issue that is being worked on. Also, there isn't a single test on these changes.

Add support for Unary Greater than and unary less than( TTNN migration included)

2024-04-12 23:52 UTC, eyonland approved these changes

2024-04-13 00:21 UTC, eyonland requested changes
We cannot allow ttnn to deviate with the api like this.
"unary_gt": torch.gt,
 "unary_lt": torch.lt,

2024-04-16 21:15 UTC, tt-aho approved these changes

2024-04-18 14:47 UTC, arakhmati approved these changes

2024-04-18 14:57 UTC, rtawfik01 approved these changes

2024-04-22 16:41 UTC, mywoodstock approved these changes

2024-04-24 17:15 UTC, eyonland approved these changes

2024-04-25 12:01 UTC, merged