#7192: Add backward support for complex abs and angle
tenstorrent/tt-metal pull request #7289
Opened 2024-04-10 10:16 UTC by KalaivaniMCW

Add backward support for complex abs and angle

2024-04-12 23:25 UTC, eyonland approved these changes

2024-04-18 13:01 UTC, tt-aho requested changes

2024-04-18 19:03 UTC, KalaivaniMCW commented on tt_eager/tt_lib/csrc/tt_lib_bindings_tensor_backward_ops.cpp
> +                    "is_complex", "True(default) if input is complex tensor", "bool", "True/False", "No"
I've changed it to match the argname `is_complextensor` Thanks.

2024-04-18 19:10 UTC, tt-aho approved these changes

2024-04-20 12:13 UTC, merged