#7296: Update ttnn docs
tenstorrent/tt-metal pull request #7297
Opened 2024-04-10 13:02 UTC by VirdhatchaniKN

Issue #7296 
Updated documentation as required
<img width="805" alt="Screenshot 2024-04-10 at 6 32 07 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/2ee4baa8-2a58-4d84-a00b-46cba1629f9b">

2024-04-13 00:07 UTC, eyonland requested changes
There is no test.
This looks like we are deviating quite a bit from the pytorch api.

2024-04-15 03:05 UTC, VirdhatchaniKN commented
> There is no test. This looks like we are deviating quite a bit from the pytorch api.

Hi @eyonland . The change I have provided is with respect to documentation as these  3 ops in particular need the second input to be a tensor and not scalar. Additionally, even if it is scalar, there is no function to convert the scalar into a tensor. Hence the changes.
Regarding test file, Since there is no change in the implementation, the test files do pass.
Test File : `tests/ttnn/unit_tests/operations/test_math_binary.py` 
<img width="590" alt="Screenshot 2024-04-15 at 8 35 34 AM" src="https://github.com/tenstorrent-metal/tt-metal/assets/138196495/920f9e1d-b55f-4eab-a0cc-07582c47d6dd">

2024-04-17 13:48 UTC, eyonland approved these changes

2024-04-18 07:54 UTC, VirdhatchaniKN commented
All post-commit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8733687200) - PASSED
Fast Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8733688720) - PASSED
Slow Dispatch unit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8733689525) - PASSED

2024-04-18 07:54 UTC, merged