Adding Uneven Block and Width Shard Padding
tenstorrent/tt-metal pull request #7658
Opened 2024-04-19 15:55 UTC by tarafdarTT

Needed to change the concept of device pages to include padding while host does not. 

A sharded buffer in host can be uneven shards, while on device its all even to the maximum shard size. Needed to modify underlying structs to support this. 

Furthermore, removed the number of cores in shard_spec and changed it to num_max_cores. To properly calculate number of cores we need to know the shape of the tensor, the sharding strategy (height, width, block) and the shard_shape. The shard_spec does not store the sharding strategy (that's in memory_layout) so we cannot give the proper minimum number of cores we need. However from the core_grid the shard_spec is storing we can have a maximum number of cores.

2024-04-19 16:15 UTC, tt-aho commented
I don't exactly understand why we are allowing shard spec to hold/specify cores that are not actually going to be used for sharding. This seems to be adding more runtime logic to handle this case where we now have some concept of max number of cores and actual used cores, even though max number of cores seems to be basically irrelevant to sharding since it seems like we only care about actual used cores. This also seems to make comparing shard specs incorrect since we compare the stored grid, so if one tensor is specified with actual grid and another is specified with max grid, then comparison would be incorrect.

If this is to support allowing users to not calculate the actual cores used themselves and allow them to just pass device grid for ease of use, then we should have infra actually determine the actual used cores and store this instead. Ex. interleaved_to_sharded allows users to pass in a grid larger than what is actually used, and then determines the actual cores/grid to use and uses this for the shard spec.

2024-04-19 16:24 UTC, tarafdarTT commented
> I don't exactly understand why we are allowing shard spec to hold/specify cores that are not actually going to be used for sharding. This seems to be adding more runtime logic to handle this case where we now have some concept of max number of cores and actual used cores, even though max number of cores seems to be basically irrelevant to sharding since it seems like we only care about actual used cores. This also seems to make comparing shard specs incorrect since we compare the stored grid, so if one tensor is specified with actual grid and another is specified with max grid, then comparison would be incorrect.
> 
> If this is to support allowing users to not calculate the actual cores used themselves and allow them to just pass device grid for ease of use, then we should have infra actually determine the actual used cores and store this instead. Ex. interleaved_to_sharded allows users to pass in a grid larger than what is actually used, and then determines the actual cores/grid to use and uses this for the shard spec.

Ideally we wouldn't need it, A lot of tests in CI are under that assumption thought.

2024-04-19 16:34 UTC, tarafdarTT commented
@tt-aho Also to add, the issue is that it's inconsistent right now. When doing direct read/writes of sharded tensors the user doesn't have that restriction where the num_cores >= num_shards (this being the exact number we need), however some ops determine the output shards based on the shard_spec (and in this case num_cores == num_shards). 

Having this restriction at least removes one of this inconsistencies, now  at least it's clear that shard_spec will be a possible superset at all times, instead right now where it sometimes is and sometimes isn't.

2024-04-22 15:01 UTC, eyonland requested changes
I'm not seeing how the test_sharded_tensor.py is actually covering the intended update.  Also, can we add a test to the tests/ttnn/unit_tests/ location so that our pipeline catches this?

2024-04-22 19:03 UTC, tarafdarTT commented
> I'm not seeing how the test_sharded_tensor.py is actually covering the intended update. Also, can we add a test to the tests/ttnn/unit_tests/ location so that our pipeline catches this?

Hi Eyon, I added those tests.

2024-04-22 19:25 UTC, tt-aho commented
I think it's okay for allowing users to not have to determine the actual used cores themselves and just pass for example full device grid to our apis, but we shouldn't be storing this superset in the lower level structs. They should only hold the exact cores being used or else we would potentially need to add more handling/cases in ops, etc or as for example what you're currently doing right now with trying to calculate the number of cores used each time we call num_cores.

I understand this issue was introduced before this pr so not required to be addressed here but I think we should try and fix this as soon as we can.
Either provide a new api that takes in the user's target shard specs/shapes and constructs the correct shardpspec object, so the actual constructor would expect the correct cores used, or you could hide it in the lower level construction to minimize impact to user apis but I think we should go with the former and be more explicit.

2024-04-22 20:17 UTC, tarafdarTT commented
> I think it's okay for allowing users to not have to determine the actual used cores themselves and just pass for example full device grid to our apis, but we shouldn't be storing this superset in the lower level structs. They should only hold the exact cores being used or else we would potentially need to add more handling/cases in ops, etc or as for example what you're currently doing right now with trying to calculate the number of cores used each time we call num_cores.
> 
> I understand this issue was introduced before this pr so not required to be addressed here but I think we should try and fix this as soon as we can. Either provide a new api that takes in the user's target shard specs/shapes and constructs the correct shardpspec object, so the actual constructor would expect the correct cores used, or you could hide it in the lower level construction to minimize impact to user apis but I think we should go with the former and be more explicit.

Thanks @tt-aho I think that makes sense. I'll undo the changes I made in this PR for the num_max_cores where I further abstract this, and create an issue to change all remaining tests that we have to issue core ranges that are the exact size, or have those tests call another layer that makes the appropriate core range set like you suggested.

2024-04-23 01:59 UTC, AleksKnezevic approved these changes

2024-04-23 02:25 UTC, kmabeeTT approved these changes

2024-04-23 15:32 UTC, tarafdarTT commented
Will add passing CI pipeline after I rebase and do that.

2024-04-23 16:24 UTC, arakhmati approved these changes

2024-04-23 16:49 UTC, TT-BrianLiu approved these changes

2024-04-23 20:34 UTC, tt-asaigal approved these changes

2024-04-23 20:40 UTC, eyonland approved these changes

2024-04-23 21:35 UTC, tt-aho commented on tt_metal/impl/dispatch/command_queue.cpp
> +            (buffer.buffer_layout() == TensorMemoryLayout::HEIGHT_SHARDED
Why is this rechecked if it is already inside `if (is_sharded(buffer.buffer_layout()))?`

2024-04-23 21:35 UTC, tt-aho commented on tt_metal/impl/dispatch/command_queue.hpp
> +            or ((this->buffer_layout == TensorMemoryLayout::HEIGHT_SHARDED and (buffer.num_pages() != buffer.num_dev_pages())))
Why not use `is_sharded(this->buffer_layout) and ...`

2024-04-23 21:35 UTC, tt-aho commented on tt_metal/impl/dispatch/command_queue.cpp
> +            memcpy(final_src, src, buffer.num_pages() * buffer.page_size());
This change + how it is read seems like it would cause worse perf for this height sharded case compared to before

2024-04-23 21:35 UTC, tt-aho commented on tt_metal/impl/buffers/buffer.cpp
> +uint32_t get_num_cores_from_shape(const TensorMemoryLayout & layout, const uint32_t total_height, const uint32_t total_width, const std::array<uint32_t, 2> & shard_shape) {
Is this function used anywhere? I didn't see it when searching

2024-04-23 22:28 UTC, tt-aho approved these changes

2024-04-23 22:28 UTC, tt-aho commented on tt_metal/impl/buffers/buffer.hpp
> +
Remove forward decl

2024-04-24 00:27 UTC, tarafdarTT commented
working ci pipelines: https://github.com/tenstorrent/tt-metal/actions/runs/8808084943

2024-04-24 00:27 UTC, merged