#7826: Update ttnn doc for abs
tenstorrent/tt-metal pull request #7884
Opened 2024-04-26 13:41 UTC by VirdhatchaniKN

Issue #7826  

**Fix Provided**
- Documentation updated with information regarding supported data type and layout for abs
- Skipped test for unsupported data type and layout

**Sweep test results :** 
- `tests/ttnn/sweep_tests/sweeps/abs.py` - [abs.csv](https://github.com/tenstorrent/tt-metal/files/15131311/abs.csv)

2024-04-26 15:52 UTC, eyonland requested changes
Blocking this for now.   I know this needs to be updated.  Would like to get it instead updated on the C++ side after we migrate.

2024-04-26 15:56 UTC, arakhmati approved these changes

2024-04-30 16:53 UTC, eyonland approved these changes

2024-09-26 03:45 UTC, VirdhatchaniKN commented
Closing PR as documentation structure is currently changed

2024-09-26 03:45 UTC, closed without merging