#0: Added option to filter perf results to within start/stop signposts
tenstorrent/tt-metal pull request #7979
Opened 2024-04-30 18:46 UTC by AleksKnezevic

2024-04-30 18:48 UTC, arakhmati approved these changes

2024-05-02 14:51 UTC, mo-tenstorrent approved these changes

2024-05-03 20:34 UTC, tt-rkim approved these changes

2024-05-03 21:08 UTC, TT-billteng commented on pytest.ini
> +timeout = 102400
Is this an accident?

2024-05-03 21:08 UTC, TT-billteng requested changes
pytest.ini

2024-05-03 21:19 UTC, AleksKnezevic commented on pytest.ini
> +timeout = 102400
Yes, it is.

2024-05-03 21:22 UTC, TT-billteng approved these changes

2024-05-03 21:44 UTC, AleksKnezevic commented on pytest.ini
> +timeout = 102400
Changed

2024-05-03 21:47 UTC, AleksKnezevic commented
> pytest.ini
> 
> Also, can you find a way to not use `SLOW_MATMULS` ?

What do you want me to change about it? I wanted a quick way to disable these MMs for certain pipelines to retain CI coverage while the underlying issue is resolved. I can add more infra to do it via pytest but I'd have to pipe it through all the tests, so it would be a lot of changes for throwaway code.

2024-05-04 00:57 UTC, merged