#7292: Add repeat ttnn sweeps
tenstorrent/tt-metal pull request #8005
Opened 2024-05-01 16:15 UTC by npetrovic-tenstorrent

Add YAML and generation function for TTNN repeat op

2024-05-01 16:19 UTC, arakhmati approved these changes

2024-05-10 14:46 UTC, ttmtrajkovic commented
+@rtawfik01 
are changes in llk modules tt-llk-* intentional or accidental?
Could you please check?

2024-05-10 14:54 UTC, rtawfik01 requested changes

2024-05-10 14:54 UTC, rtawfik01 commented on tt_metal/third_party/tt_llk_grayskull
Please run `git submodule update --init --recursive`. This change will revert a change on main.

2024-05-10 14:54 UTC, rtawfik01 commented on tt_metal/third_party/tt_llk_wormhole_b0
Please run `git submodule update --init --recursive`. This change will revert a change on main.

2024-05-10 16:22 UTC, npetrovic-tenstorrent commented on tt_metal/third_party/tt_llk_grayskull
These changes were note done intentionally, I will do it as proposed.

2024-05-11 07:04 UTC, npetrovic-tenstorrent commented on tt_metal/third_party/tt_llk_wormhole_b0
It was excluded from the commit

2024-05-13 09:41 UTC, ttmtrajkovic approved these changes
LLK modules seem to be untouched now so marking this as approve.

2024-05-14 14:01 UTC, rtawfik01 approved these changes

2024-05-14 19:56 UTC, merged