Mistral demo improvement
tenstorrent/tt-metal pull request #8251
Opened 2024-05-08 13:04 UTC by sraizada-tt

Added support for:
- Longer seq len (1024 tokens)
- bf4 MLP weights
- sharded rm norm 
- attention caching

fyi @mtairum @yieldthought

2024-05-08 18:04 UTC, TT-billteng requested changes
don't think you need to change taskflow for this

2024-05-09 06:23 UTC, arakhmati approved these changes

2024-05-09 08:13 UTC, mtairum commented
Moved temporarily the mistral test above mamba (which was failing) just to confirm that the mistral perf tests are passing.

The logs are all good: https://github.com/tenstorrent/tt-metal/actions/runs/9005127711/job/24740023842

We'll revert the last commit, update the expected times and it will be good to merge.

2024-05-09 10:22 UTC, mtairum commented
Reverted the taskflow (accidently committed) and the CI test order change.
Updated to latest branch. 

The CI pipeline is broken now, but not related to our changes. It's good for merge.

2024-05-09 10:23 UTC, mtairum commented
> don't think you need to change taskflow for this

This was added by accident. Reverted on last push. @TT-billteng can you please review?

2024-05-09 14:21 UTC, tt-rkim approved these changes

2024-05-09 15:05 UTC, TT-billteng approved these changes

2024-05-09 15:06 UTC, TT-billteng commented on models/demos/wormhole/mistral7b/demo/demo.py
> +    logger.info("Caching attention ops..")
is this needed?

2024-05-09 15:06 UTC, TT-billteng commented on models/demos/wormhole/mistral7b/tt/mistral_common.py
> +        print("Cached iter", iter)
clean up

2024-05-09 18:12 UTC, merged