#5389: removed map_launch_op_args_to_execute
tenstorrent/tt-metal pull request #8417
Opened 2024-05-13 22:10 UTC by arakhmati

2024-05-13 22:27 UTC, ayerofieiev-tt approved these changes

2024-05-13 22:28 UTC, ayerofieiev-tt commented
Nice! Thank you!

2024-05-13 22:37 UTC, eyonland requested changes

2024-05-13 22:37 UTC, eyonland commented on ttnn/cpp/ttnn/decorators.hpp
> +                            return detail::map_execute_return_to_vector<concrete_operation_t>(
When you are inside launc_op callback you are on a different thread reaching back to the args on the operator() overload.  This means that the remaining args where not passed by value and so you end up with a bug here.

2024-05-13 22:55 UTC, eyonland approved these changes

2024-05-14 06:12 UTC, cfjchu approved these changes

2024-05-14 07:18 UTC, merged