#5337: make Mixtral multidevice+async
tenstorrent/tt-metal pull request #8511
Opened 2024-05-15 15:11 UTC by sraizada-tt

replacing device loops with ttnn multi device + async API

2024-05-15 16:00 UTC, mtairum commented
Added a commit for some leftover code on my previous merge (oops).

Started all 3 multichip pipelines. We'll have to check that they are all passing the mixtral tests at least.

- https://github.com/tenstorrent/tt-metal/actions/runs/9098906802
- https://github.com/tenstorrent/tt-metal/actions/runs/9098912081
- https://github.com/tenstorrent/tt-metal/actions/runs/9098913480

2024-05-15 17:18 UTC, mtairum requested changes
Please fix this issues before we merge.

2024-05-15 17:18 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_model.py
> +def test_mixtral_model_inference(
Uncomment the pytest parametrizations.

2024-05-15 17:18 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_rms_norm.py
> +    print(tt_output_torch.shape, reference_output.shape)
Remove print

2024-05-15 17:18 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_rms_norm.py
> +    partial_state_dict = {k[24:]: v for k, v in state_dict.items() if (k.startswith("layers.7.attention_norm."))}
Is this intented or a typo?

2024-05-16 08:30 UTC, mtairum commented
New pipelines for the fixes running here:

multi-device unit tests: https://github.com/tenstorrent/tt-metal/actions/runs/9109035704 
multi-device demo: https://github.com/tenstorrent/tt-metal/actions/runs/9109001480
multi-device perf: https://github.com/tenstorrent/tt-metal/actions/runs/9109039877

2024-05-16 11:23 UTC, yieldthought approved these changes

2024-05-17 16:00 UTC, mtairum commented
Running updated pipelines:

https://github.com/tenstorrent/tt-metal/actions/runs/9130971955
https://github.com/tenstorrent/tt-metal/actions/runs/9130974546
https://github.com/tenstorrent/tt-metal/actions/runs/9130975564
https://github.com/tenstorrent/tt-metal/actions/runs/9130976749

After they're all green we should confirm the time it takes to run all `test_mixtral_model.py` tests and adjust them to the correct pipelines and/or reduce the number of tests if needed.

2024-05-20 14:15 UTC, pgkeller reviewed
Says I'm tagged as code owner, but I don't see any files on the list that I know anything about (looks like all .py?). Let me know if that's blocking at some point and I'll approve

2024-05-20 14:53 UTC, tapspatel commented
Added a comment. Rerun pipelines to ensure passing and ill approve.

2024-05-20 17:14 UTC, cfjchu approved these changes
Looks great!

2024-05-21 10:07 UTC, mtairum commented
All pipelines passing here:

- [T3K] T3000 model perf tests: https://github.com/tenstorrent/tt-metal/actions/runs/9161206926
- [T3K] T3000 frequent tests: https://github.com/tenstorrent/tt-metal/actions/runs/9161205037
- [T3K] T3000 unit tests: https://github.com/tenstorrent/tt-metal/actions/runs/9161210132
- [T3K] T3000 demo tests: https://github.com/tenstorrent/tt-metal/actions/runs/9172485831

I'll squash some commits and merge.

2024-05-21 11:06 UTC, mtairum approved these changes

2024-05-21 14:34 UTC, tapspatel approved these changes

2024-05-21 14:39 UTC, merged