#8793: Add forward support for lti
tenstorrent/tt-metal pull request #8795
Opened 2024-05-24 11:54 UTC by mouliraj-mcw

Add LTI op ( less than op , in_place operation)

2024-06-03 14:37 UTC, TT-BrianLiu approved these changes

2024-08-06 13:21 UTC, tt-aho requested changes

2024-08-07 13:14 UTC, tt-aho approved these changes

2024-08-08 04:46 UTC, eyonland requested changes
Please have this reviewed by an MCW colleague prior to posting the PR.

2024-08-09 11:46 UTC, mouliraj-mcw commented
Closing this PR. It will be Handled in [PR link](https://github.com/tenstorrent/tt-metal/pull/8790)

2024-08-09 11:46 UTC, closed without merging