#926: log2, log10 operators support
tenstorrent/tt-metal pull request #927
Opened 2023-06-01 23:51 UTC by muthutt

We add log2, log10 unary operator support for Grayskull and Wormhole using existing SFPU hooks
See details in the git issue #926

2023-06-02 22:55 UTC, tt-aho requested changes
@muthutt I think these corrections need to be made (This is for GS code in `tt_metal/src/ckernels/grayskull/llk_lib` I have not looked if the code for WH is different):

- I think the log_with_base_init functions do not need to take an arg/value. Specifically `log_with_base_tile_init`, `llk_math_eltwise_unary_sfpu_log_with_base_init` passing an argument does not resolve to anything from what I can tell looking at the underlying function it calls (`llk_math_eltwise_unary_sfpu_log_with_base_init`)
- `log_with_base_tile` `llk_math_eltwise_unary_sfpu_log_with_base` The args to the underlying function are in the wrong order. Looking at the function it calls, `llk_math_eltwise_unary_sfpu`, the order of args is dst_index, vector_mode, param0. You need to reorder your args to get the args passed correctly (might need to pass default for vector_mode as well).
- Looking at how log is actually calculated in `tt_metal/src/ckernels/grayskull/common/inc/ckernel_sfpu.h`, in `log_body `function, there is this line for scaling, `result *= s2vFloat16a(log_base_scale_factor);`. It expects the scale factor to be FP16A, but your encoded values for the scale factors `0x3ede5bd9`, `0x3fb8aa3b` are FP32 and need to be converted to FP16A. I think that would be `0x36f2` and `0x3dc5` respectively.

2023-06-03 20:15 UTC, muthutt reviewed
all review changes requested by @tt-aho are posted

2023-06-05 13:29 UTC, tt-rkim requested changes

2023-06-05 19:31 UTC, tt-aho requested changes

2023-06-05 22:04 UTC, tt-aho requested changes

2023-06-07 22:39 UTC, tt-aho requested changes

2023-06-07 23:09 UTC, tt-aho approved these changes
Looks good to me

2023-06-08 13:47 UTC, tt-rkim approved these changes

2023-06-08 16:53 UTC, merged