Mixtral prefill for sequel {128, 1204, 2048}
tenstorrent/tt-metal pull request #9291
Opened 2024-06-07 13:04 UTC by sraizada-tt

2024-06-07 14:35 UTC, yieldthought approved these changes

2024-06-07 14:35 UTC, yieldthought commented
Approved if tests show we haven't broken anything else in CI ^^

2024-06-13 23:14 UTC, ttmchiou commented
Does this pass t3k unit tests?

2024-06-14 08:21 UTC, mtairum commented
@ttmchiou Not yet. We're actively working on this PR And will update the thread when tests are fully integrated and passing.

2024-06-14 13:53 UTC, mtairum requested changes
Initial set of reviews. 

They mainly include:
- Rebase to tip
- Add a few more comments
- Remove tensor deletion (not needed anymore)
- other

I have a few commits in flight. Will update the branch and start closing my comments.

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_attention_prefill.py
> +        del attention_input, attn_mask
Remove this after rebasing to latest tip

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_attention_prefill.py
> +    generation_length = 1
Tested passing locally for 3 iterations 👍

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_decoder_prefill.py
> +    generation_length = 1
Increase this to 2~3 iterations.

Passing local test 👍

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_decoder_prefill.py
> +        del decode_input_b1sh, attn_mask
Remove after rebase

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_model_prefill.py
> +        del decode_input, attn_mask
Remove after rebase

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_model_prefill.py
> +    prompt = prompt * 7
This line is to make sure we have a prompt with more than 2k tokens, right?

Would probably be good to update this to a real 2k+ prompt. Ideally just reading from one of the prompts we use in demo prefill.

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_model_prefill.py
> +    (32,),
I've added a test for 1L as well. We can then choose which pipelines we want to run this test.

2024-06-14 13:53 UTC, mtairum commented on models/demos/t3000/mixtral8x7b/tests/test_mixtral_moe_prefill.py
> +    iterations = 1
Increase to 2 or 3.

2024-06-14 17:53 UTC, mtairum requested changes
We also should have to update the perf test.

2024-06-18 18:30 UTC, ttmchiou commented on tests/scripts/t3000/run_t3000_frequent_tests.sh
> +  pytest models/demos/t3000/mixtral8x7b/tests/test_mixtral_model_prefill.py::test_mixtral_model_inference[wormhole_b0-True-32-128]
can these tests be run using pytest parameters instead of invoking multiple times?

2024-06-18 18:39 UTC, ttmchiou commented on tests/scripts/t3000/run_t3000_unit_tests.sh
> +  pytest models/demos/t3000/mixtral8x7b/tests/test_mixtral_attention_prefill.py
can you confirm if these tests can pass?

2024-06-20 08:53 UTC, closed without merging