#901: Uplift CompileProgram to compile and hash kernels rather than KernelGroup
tenstorrent/tt-metal pull request #939
Opened 2023-06-02 17:32 UTC by abhullar-tt

See test_compile_program.cpp for unit test

**Metal tests to add**
Each test case should clear the `built_kernels` dir before running. Tests should be parameterized on persistent compile cache
- [x] CompileProgram called in a loop
        - Expected: Cache hit loop index > 0
- [x] Call CompileProgram, delete built_kernels dir and then CompileProgram with the same program
        - Expected: Cache miss in both calls and binaries should get generated both times, kernel hashes should be the same across both CompileProgram invocations 
- [x] Call CompileProgram twice with modified kernel/CB parameters
        a) Modify compute kernel compile time args
        b) Modify compute kernel math fidelity
      	c) Modify compute kernel fp32_dest_acc_en
	d) Modify compute kernel math_approx_mode
	e) Modify data movement kernel noc 
	f) Modify circular buffer data format
	g) Modify circular buffer index 
        h) Modify data movement processor type and expect cache hit
        - Expected: Cache miss for initial call and for each modified case (besides h), binaries should get generated, kernel hashes should be different

2023-06-05 19:46 UTC, tt-rkim requested changes
lgtm, just change logger

2023-06-05 19:46 UTC, tt-rkim requested changes
lgtm, just change logger

2023-06-06 17:03 UTC, TT-billteng approved these changes
Looks a lot cleaner than before! Great work :D

2023-06-06 19:26 UTC, tt-rkim approved these changes

2023-06-06 19:26 UTC, merged