#9159: Add support to NLP decode TMs to support batch dim padded to tile
tenstorrent/tt-metal pull request #9399
Opened 2024-06-12 16:28 UTC by cglagovichTT

### Ticket
https://github.com/tenstorrent/tt-metal/issues/9159

### Problem description
With long context lengths, we sometimes have to run decode mode with batch < 32. This means that the attention TMs should be aware of the upadded batch size so they can create output tensors of the correct shape for use in attention.

### What's changed
- Added `unpadded_batch_size` param to `nlp_create_qkv_heads_decode`
- Updated `nlp_concat_heads_decode` to support input batch size < 32.

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

2024-06-12 16:28 UTC, cglagovichTT commented
post commit: https://github.com/tenstorrent/tt-metal/actions/runs/9486271546

2024-06-14 14:17 UTC, TT-BrianLiu requested changes
I believe in `ttnn` you can get the unpadded dims. I think you should switch to `ttnn` shape and not introduce a new variable just to track the original shape.

2024-06-14 14:31 UTC, caixunshiren approved these changes

2024-06-14 16:23 UTC, cglagovichTT commented
great suggestion, @TT-BrianLiu . I removed that extra param and use the ttnn shape to get the unpadded batch size

2024-06-17 14:24 UTC, TT-BrianLiu approved these changes

2024-06-17 17:25 UTC, merged