Adding support for dram sharded matmuls
tenstorrent/tt-metal pull request #9878
Opened 2024-07-02 14:11 UTC by avoraTT

### Ticket
- #9642 

### Problem description
Supporting dram sharded matmuls in MLP for FF2 and FF3

### What's changed
Memory config for FF2/FF3 to support width sharding on DRAM.

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes

2024-07-02 14:12 UTC, avoraTT commented
T3K CI Tests:

Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/9762458471
Demo: https://github.com/tenstorrent/tt-metal/actions/runs/9762461598
Perf: https://github.com/tenstorrent/tt-metal/actions/runs/9762454769

2024-07-05 13:49 UTC, cglagovichTT requested changes

2024-07-05 13:49 UTC, cglagovichTT commented on models/demos/t3000/llama2_70b/tt/llama_mlp_optimized.py
> +        w3_out = tt_lib.operations.primary.matmul(
This should be changed back to `ttnn.matmul`, since this commit comes after the switch to use all ttnn matmul

2024-07-05 13:49 UTC, cglagovichTT commented on models/demos/t3000/llama2_70b/tt/model_config.py
> +            # out_subblock_h=1,  # Must be divisible by per_core_M
Feel free to delete commented lines if they are no longer used

2024-07-08 19:33 UTC, TT-billteng requested changes
Do you need to bump UMD for this?

2024-07-09 19:54 UTC, TT-billteng approved these changes

2024-07-11 11:58 UTC, cglagovichTT approved these changes

2024-07-12 03:44 UTC, merged