#895 Add Swin CPU implementation with HF demo, torch demo
tenstorrent/tt-metal pull request #991
Opened 2023-06-06 15:18 UTC by saichandax

This branch contains the following:

CPU implementation of the Swin model from huggingface transformers. It includes modeling of Swin along with its dependent libraries.
This branch has the demo for torch_cpu and hugging face reference model, along with the test_torch_model file to compare the two.

2023-06-13 16:07 UTC, tt-rkim requested changes
I'm confused on this whole PR. What's the point? There is no TT code.

Are these demos? Or just merging in Pytorch references first?

Also, the files under `demo/` are unnecessary to me.

2023-06-13 19:15 UTC, ashayestehmanesh requested changes

2023-06-14 13:15 UTC, ashayestehmanesh submitted a review, later dismissed
@saichandax 

Please make sure of 3 things before merging
1. all the tests work
2. squash your commits into one commit
3. all the code you are committed is used, do not merge any unused code. 

Thank you :)

2023-06-15 15:13 UTC, farbabi approved these changes

2023-06-15 15:24 UTC, tt-rkim approved these changes

2023-06-15 15:25 UTC, merged